### ISSUE TITLE
InvalidProjectFileException (MSB0001: Internal MSBuild Error: A required NuGet assembly was not found)

### ISSUE THREAD

**Issue by mjrousos** [dotnet/msbuild#6377] opened 2021-04-27 17:55 UTC
### Issue Description
Using recent MSBuild previews, loading projects in units tests (via `new ProjectInstance`) is failing for me with this error:

```
  Error Message:
   Microsoft.Build.Exceptions.InvalidProjectFileException : The expression "[MSBuild]::GetTargetFrameworkIdentifier(net5.0)" cannot be evaluated. MSB0001: Internal MSBuild Error: A required NuGet assembly was not found. Expected Path: C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3  C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets
  Stack Trace:
     at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject[T1,T2](IElementLocation elementLocation, String resourceName, T1 arg0, T2 arg1)
   at Microsoft.Build.Evaluation.Expander`2.Function`1.Execute(Object objectInstance, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation)
   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertyBody(String propertyBody, Object propertyValue, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties, IFileSystem fileSystem)
   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveTypedAndEscaped(String expression, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties, IFileSystem fileSystem)
   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveEscaped(String expression, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties, IFileSystem fileSystem)
   at Microsoft.Build.Evaluation.Expander`2.ExpandIntoStringLeaveEscaped(String expression, ExpanderOptions options, IElementLocation elementLocation)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluatePropertyElement(ProjectPropertyElement propertyElement)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluatePropertyGroupElement(ProjectPropertyGroupElement propertyGroupElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCacheBase projectRootElementCache, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, EvaluationContext evaluationContext, Boolean interactive)
   at Microsoft.Build.Execution.ProjectInstance.Initialize(ProjectRootElement xml, IDictionary`2 globalProperties, String explicitToolsVersion, String explicitSubToolsetVersion, Int32 visualStudioVersionFromSolution, BuildParameters buildParameters, ILoggingService loggingService, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, Nullable`1 projectLoadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Execution.ProjectInstance..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, Nullable`1 projectLoadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Execution.ProjectInstance..ctor(String projectFile)
   at ProjectInstanceRepro.Program.LoadTestProject() in D:\scratch\ProjectInstanceRepro\ProjectInstanceRepro\Program.cs:line 22
   at ProjectInstanceRepro.Program.Main() in D:\scratch\ProjectInstanceRepro\ProjectInstanceRepro\Program.cs:line 17
   at TestProj.UnitTest1.Test1() in D:\scratch\ProjectInstanceRepro\TestProj\UnitTest1.cs:line 12
```

### Steps to Reproduce

I've created a small repro at [mjrousos/ProjectInstanceRepro](https://github.com/mjrousos/ProjectInstanceRepro).

Notice that running the 'ProjectInstanceRepro' app succeeds but running `dotnet test` on either test project (which just invoke ProjectInstanceRepro's main method) fails.

### Expected Behavior
The project instance should load successfully.

### Actual Behavior
The error shown above.

### Versions & Configurations
This appears to repro in both 5.0.300-preview.21180.15 and 6.0.100-preview.2.21155.3.

**Comment by BenVillalobos** [comment] 2021-04-28 15:37
Team Triage: Related to https://github.com/microsoft/MSBuildLocator/pull/115

**Comment by Forgind** [comment] 2021-04-29 19:33
With debugging help from @rainersigwald, it seems the problem is more related to #6126.

The TryLoadAssembly function from MSBuildLocator is invoked several times but never for a NuGet assembly. The last assembly it tries to load is StringTools. After that, it gets [here](https://github.com/dotnet/msbuild/blob/5b9216a75e98e19eba84e04a5f30bd35a68f317a/src/Build/Utilities/NuGetFrameworkWrapper.cs#L30-L32) where it tries to load Nuget.Frameworks.

We inspected the values of BuildEnvironmentHelper.Instance.Mode and BuildEnvironmentHelper.VisualStudio, and they did not match, so we assumed it would go to the else part. BuildEnvironmentHlper.Instance.CurrentMSBuildToolsDirectory seemed correct as well. This all seems right.

Somehow, assemblyDirectory did not get the right value. Rather than a path to the NuGet assembly as was present in CurrentMSBuildToolsDirectory, it was set to "Platform". Then the Assembly.LoadFrom call failed, leading to the InternalErrorException.

Based on that exception, I would have assumed that Platform would be in the error message, but it was not. You can see that it expected the NuGet assembly at the correct path (and it's there, at least on my computer), but it didn't find it, perhaps because assemblyDirectory was briefly reset to "Platform" just for the Assembly.LoadFrom call? That part mystifies me.

@brianrob, do you have any idea what's going on?

**Comment by TanayParikh** [comment] 2021-05-05 19:17
Hello, just wanted to follow-up if there were any updates regarding this issue. This is currently blocking the dotnet/aspnetcore SDK update (https://github.com/dotnet/aspnetcore/pull/32298), and consequently consumption of other bug fixes (ex. https://github.com/dotnet/aspnetcore/issues/32237)

@forgind . @brianrob

**Comment by brianrob** [comment] 2021-05-06 18:30
Sorry @forgind, I missed this in my e-mail.  Just looking briefly at this, it's definitely in a place that got touched in .NET 6.  However, it looks like it also repros with .NET 5 as well per @mjrousos note above.

> This appears to repro in both 5.0.300-preview.21180.15 and 6.0.100-preview.2.21155.3.

Did the loading changes get backported by chance?

**Comment by marcpopMSFT** [comment] 2021-05-06 18:35
@brianrob the same MSBuild is in .net 6 preview 4 and 5.0.300 as we hadn't forked for 17.0 yet.  That'll be different for .NET 6 preview 5 and onward so the change is in both.

**Comment by rainersigwald** [comment] 2021-05-06 18:35
MSBuild 16.10 is in both of those releases, and that's what main was when you checked in. We can consider backing out the change in 16.10/5.0.300 and fixing forward for 17.0/6.0.100 if we can't figure it out quickly.

**Comment by brianrob** [comment] 2021-05-06 20:10
Thanks @marcpopMSFT and @rainersigwald.  It looks like the issue here is that there is already a different version of NuGet.Frameworks.dll loaded into the process in the default assembly load context.  Thus, the second load fails because you can't load the same assembly with a different version into the same assembly load context.

It looks like the initial load happens in the app, and then the app invokes MSBuild, which results in the second load attempt.

Historically, this worked because MSBuild loaded NuGet.Frameworks.dll using LoadFile which is a completely different runtime load context (different from assembly load context).  We switched to using LoadFrom in order to get the performance benefits that come with this (in the case of this change, less jitting).  I am suspicious though that keeping this performance improvement is going to require a bigger change, because MSBuild has taken a dependency on a particular version of NuGet.Frameworks.dll (the one in the sdk directory), but can also be loaded into any arbitrary app that might have loaded a different one.

@rainersigwald, is it reasonable to just use the already loaded NuGet.Frameworks.dll if one is already loaded, or do we have a dependency on this particular version?  Regardless, there is definitely a race here to load the version of NuGet.Frameworks.dll that you want, and so we may need to back this out and re-design.

**Comment by rainersigwald** [comment] 2021-05-06 22:15
Aha, I see a bit more about what's going on. [Microsoft.TestPlatform.ObjectModel](https://www.nuget.org/packages/Microsoft.TestPlatform.ObjectModel/16.8.3) has a dependency on `NuGet.Frameworks (>= 5.0.0)`, and is pulled into the test project. Then that NuGet.Frameworks version is put into the test output folder and loaded when tests run because _the test framework does it_.

So Brian's description is exactly what's happening.

> is it reasonable to just use the already loaded NuGet.Frameworks.dll if one is already loaded, or do we have a dependency on this particular version?

We have a dependency on some APIs that aren't in every conceivable NuGet.Frameworks.dll, though we could _probably_ get by with "any version newer than X" for some value of X barring breaking NuGet changes. But X will vary based on MSBuild version.

I think I'm leaning toward "back out and think harder" since this is causing pain to our ASP.NET friends.

**Comment by rainersigwald** [comment] 2021-05-06 22:16
@brianrob Is it possible to fall back to `LoadFile` if `LoadFrom` fails? I wouldn't mind the perf hit in that case I don't think.

**Comment by rainersigwald** [comment] 2021-05-06 22:45
This also presents a workaround possibility: exactly match the SDK nuget.frameworks version. For the minimized repro and my 300 preview build this wasn't too too hard: https://github.com/mjrousos/ProjectInstanceRepro/pull/1

It's not good in general of course though.

**Comment by brianrob** [comment] 2021-05-06 23:48
I think the answer is yes - we could fall back to `LoadFile`, but there is another potential pitfall here.  There's a race - whoever loads their version of `NuGet.Frameworks.dll` wins.  So, if MSBuild loads first, then whoever tries next will fail, unless it's part of a `Task` in which case it will be loaded into the plugin assembly load context.  I suspect that we need to back this out and re-think.  Ideally, we remove the dependency on `NuGet.Frameworks.dll` from MSBuild because it doesn't version with MSBuild, but that's likely a bigger conversation.  Do you want me to author a revert for this?

**Comment by rainersigwald** [comment] 2021-05-07 00:44
Yes please. Can you base on and target vs16.10?

**Comment by brianrob** [comment] 2021-05-07 04:22
Posted https://github.com/dotnet/msbuild/pull/6423 to revert the changes.

**Comment by BenVillalobos** [comment] 2021-05-12 15:05
Team Triage: Closing as the fix is merged and will flow into main soon.

**Closed by BenVillalobos** 2021-05-12 15:05 UTC
Labels: Initial Investigation, Partner request, bug
