### ISSUE TITLE
MSBuild fails after upgrade to 16.3.2

### ISSUE THREAD

**Issue by Duracell1989** [dotnet/msbuild#4880] opened 2019-11-04 12:42 UTC
Our builds run fine when they're run by MSBuild version 16.3.0.46305
After installing the latest Visual Studio 2019, I got the MSBuild version **16.3.2.50909**
After this upgrade, our build fails with the following error:
```
vbc : error BC31509: Unable to open resource file '<snip>.dll.licenses': Could not find file '<snip>\obj\<snip>\x64\Release\Roser.Shared.dll.licenses'. [<snip>.vbproj]
```
Under the ```My Project``` folder, we have a ```licenses.licx``` (Needed for DevExpress Components).

### Steps to reproduce
I can't share the whole vbproj-file (also, it's very big ~2500 LOC), but I hope this has all the important bits.

project file
```
<PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">x64</Platform>
    <ProductVersion>8.0.50727</ProductVersion>
    <SchemaVersion>2.0</SchemaVersion>
    <OutputType>Library</OutputType>
    <MyType>Windows</MyType>
    <TargetFrameworkVersion>v4.7.1</TargetFrameworkVersion>
    <OldToolsVersion>2.0</OldToolsVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
    <DefineTrace>true</DefineTrace>
    <OutputPath>$(SolutionDir)\<snip>\pub\x64\</OutputPath>
    <Optimize>true</Optimize>
    <DebugType>none</DebugType>
    <PlatformTarget>x64</PlatformTarget>
    <WarningsAsErrors>41999,42016,42017,42018,42019,42020,42021,42022,42032,42036</WarningsAsErrors>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    <Prefer32Bit>false</Prefer32Bit>
    <UseVSHostingProcess>false</UseVSHostingProcess>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
<snip>
<EmbeddedResource Include="My Project\licenses.licx" />
```

Command line
```
.\MSBuild.exe /v:minimal /p:Configuration="Release" /p:Platform=x64 /p:CreatePackageOnPublish=true /p:DeployOnBuild=true /p:autoparameterizationwebconfigconnectionstrings=false /p:AllowedReferenceRelatedFileExtensions=none /target:Build /restore "<snip>.sln"
```
### Expected  behavior
The build succeeded.

### Actual behavior
The builds fails on a license-file error.

### Environment data
`msbuild /version` output:
Microsoft (R) Build Engine version 16.3.2+e481bbf88 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.3.2.50909

OS info:
Windows 10
Version 1903 (OS Build 18362.449)

**Comment by livarcocc** [comment] 2019-11-04 20:58
@BenVillalobos can you take a look?

**Comment by Duracell1989** [comment] 2019-11-12 09:28
@BenVillalobos; This problem is currently blocking multiple builds on our server. Could you provide a way to downgrade the MSBuild (we get it automatically via Visual Studio) - or another workaround?

**Comment by BenVillalobos** [comment] 2019-11-19 21:53
@Duracell1989 Unfortunately because MSBuild is part of visual studio, you can't downgrade it on its own. You can however install a [specific older version of VS](https://docs.microsoft.com/en-us/visualstudio/releases/2019/history#installing-an-earlier-release) if you need to downgrade. 

Without logs the issue is proving difficult to debug. Could you [share a binary log](https://github.com/microsoft/msbuild/blob/master/documentation/wiki/Providing-Binary-Logs.md) of your build? (Please note the warnings in those instructions about confidential information in the logs)

**Comment by Duracell1989** [comment] 2019-11-22 08:59
@BenVillalobos; I can't share the whole binlog (due too company rules); but I've researched the binlog from an old version and compared this to the new version.
Below in the image you see that the newer version doesn't know where to find the `SdkToolsPath` and that is falls back to using NETFX 4.5.1 instead of the newer NETFX 4.7.2
![Binlog difference](https://user-images.githubusercontent.com/18702736/69412148-a6f50480-0d0e-11ea-9360-84add28d36c5.png)

**Comment by Duracell1989** [comment] 2020-01-07 08:36
@BenVillalobos; Can you give an update regarding this issue?

**Comment by BenVillalobos** [comment] 2020-01-10 18:03
@Duracell1989 Current status is that a high priority issue has taken up most of my time as of late. This is still on my to-do list though!

**Comment by BenVillalobos** [comment] 2022-11-02 23:25
Sorry this fell through the cracks! I recall trying to find someone who understood license files but being unable to.

WIthout a binlog or repro project it's difficult to investigate why sdktoolspath isn't being passed anymore. For some sort of investigation, we'd need to see a before/after binlog. Since you have company policy to consider, you can [file a feedback ticket](https://developercommunity.visualstudio.com/spaces/8/index.html) with the binlog attached. Attaching it in a feedback ticket would make it confidential to us.

Closing the issue for now. If this is still an issue and you want to reopen it, I suggest filing the feedback ticket and referencing this issue so it can get routed to this team quicker.

**Closed by BenVillalobos** 2022-11-02 23:25 UTC
