### ISSUE TITLE
PackageReference support for msbuild variables

### ISSUE THREAD

**Issue by asklar** [dotnet/msbuild#6108] opened 2021-02-02 15:07 UTC
https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-References-in-Project-Files.md#adding-a-packagereference-condition

This doc mentions that one can use Conditions in PackageReferences, but then later it says this only works for `targetFramework`.

In my scenario I need the ability to bring in one of two possible nuget packages into my csproj, depending on an msbuild variable (different versions of a package). However when I try to use the variable in the condition, VS seems to always include both packages, which obviously isn't what I need.

Is there a way to achieve this? If not, can this issue be turned into a feature request :)

**Comment by BenVillalobos** [comment] 2021-02-03 16:48
Team Triage: You can create a property within your project, something like `$(NewtonsoftJsonVersion)` and set that based off of a condition. Then in your packagereference, use that as your version. 

Is this what you needed?

**Comment by rainersigwald** [comment] 2021-05-18 14:59
This is a feature request, but for NuGet. I'll duplicate it to their bug.

**Comment by rainersigwald** [comment] 2021-05-18 15:00
Duplicate of https://github.com/NuGet/Home/issues/5895

**Closed by rainersigwald** 2021-05-18 15:00 UTC
Labels: untriaged
