### ISSUE TITLE
net4.0  have higher priority then netstandard1.3

### ISSUE THREAD

**Issue by magol** [dotnet/msbuild#1960] opened 2017-04-10 14:17 UTC
I have a library that target both `netstandard1.3` and `net4.0` as following:
```xml
<TargetFrameworks>netstandard1.3;net4.0</TargetFrameworks>
```
 The library is used by the main application that is targeting `net4.6`

```xml
<PropertyGroup>
  <OutputType>exe</OutputType>
  <!--<TargetFramework>netstandard1.3</TargetFramework>-->
  <TargetFramework>net4.6</TargetFramework>
  <RuntimeIdentifier>win</RuntimeIdentifier>
</PropertyGroup>

<ItemGroup>
  <ProjectReference Include="..\Foo.Library\Foo.Library.csproj" />
</ItemGroup>
```

I expect that the `netstandard1.3` version of the library is used, but instead it uses the `net4.0` version.
If I change the main application to also use `netstandard1.3`, or remove `net4.0` from the library, it uses the right library version. 

Do I something wrong, or is it a bug?

See attached solution for an example.
[MultiTargetProblem.zip](https://github.com/Microsoft/msbuild/files/910332/MultiTargetProblem.zip)

**Comment by jeffkl** [comment] 2017-04-10 14:36
@nguerrera do you know how to get the SDK to choose `netstandard` over full framework for this scenario?

**Comment by nguerrera** [comment] 2017-04-10 17:32
This is by design as it mimics the same behavior as if you'd pack the project to a .nupkg and reference it that way. We call in to NuGet to get the "nearest" target framework, and net4.0 is consider "nearer" to net4.6 than netstandard1.3.

There is an escape hatch to override the automatic selection, which is to provide the SetTargetFramework metadata yourself.

The following should work:

``` xml
<ProjectReference Include="..\Foo.Library\Foo.Library.csproj" SetTargetFramework="TargetFramework=net4.0" />
```

**Comment by magol** [comment] 2017-04-12 11:29
@nguerrera 


 Thanks for your reply, it appreciated.
Is `SetTargetFramework` (and `ProjectReference `) documented on internet somewhere?

This made so that the right version of the library is selected, but now I have issues with `PackageReference`. For example, I have helper methods in the library that are using `Console.WriteLine`. Unfortunately, I get the following error when I use them:

> System.IO.FileNotFoundException occurred
>   HResult=0x80070002
>   Message=Could not load file or assembly 'System.Console, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
>   Source=Foo.Library
>   StackTrace:
>    at Foo.Library.MyLibrary.PrintLine(String text)
>    at FooConsole.Program.Main(String[] args)


Instead of sending an updated zip file with sample code, I have created a repository [hear](https://github.com/magol/MultiTargetLibrary).

**Comment by nguerrera** [comment] 2017-04-17 17:07
The missing System.Console at runtime is likely due to a full .NET Framework targeting project that is not using PackageReference for its nuget references, which prevents nuget dependencies from flowing transitively to it. See https://github.com/NuGet/Home/issues/4488

**Comment by rainersigwald** [comment] 2020-12-21 16:00
Team triage: closing due to age. If you're still seeing this problem, please let us know and we can reactivate it.

**Closed by rainersigwald** 2020-12-21 16:00 UTC
Labels: question
