### ISSUE TITLE
Content file gets deleted after subsequent build of child project

### ISSUE THREAD

**Issue by johnsimons** [dotnet/msbuild#5566] opened 2020-07-30 00:10 UTC
### Issue Description
I have a requirement to package the raw nuget packages as part of the project package.
The package also needs to be copied as a `Content` so that dependent projects get it.
The package name also needs to be renamed to not include the version.

I have something that works quite well, except when the child project is updated and when we build the sln again the content package is deleted from the output directory.

```xml
<Target Name="GetPackageFiles" AfterTargets="ResolveReferences" DependsOnTargets="RunResolvePackageDependencies">
    <Message Text="Collecting nupkg packages to bundle" Importance="high" />
    <ItemGroup>
        <Content Include="@(PackageDefinitions->'%(ResolvedPath)/%(Name).%(Version).nupkg')" Condition="$([System.String]::new('%(Name)').ToLower().Contains('newtonsoft.json'))">
            <Visible>false</Visible>
            <Link>@(PackageDefinitions->'%(Name).nupkg')</Link>
            <Pack>true</Pack>
            <PackagePath>@(PackageDefinitions->'contentFiles/any/any/%(Name).nupkg')</PackagePath>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
</Target>
```

### Steps to Reproduce
[Repro.zip](https://github.com/dotnet/msbuild/files/4997950/Repro.zip)
I have created a repro of the problem.
The sln has 2 projects:
![image](https://user-images.githubusercontent.com/122651/88863156-7c682d80-d245-11ea-98ef-4e1d0dac3bc4.png)

If you build this solution first time, you end-up with the package in the output folder:
![image](https://user-images.githubusercontent.com/122651/88863284-ca7d3100-d245-11ea-9f93-b4235c1aa75c.png)

But then if you modify Test/Class1.cs and build again, the package is deleted.

### Expected Behavior
I was expecting the package to not be deleted from Test output directory

### Actual Behavior
The package is deleted.

**Comment by BenVillalobos** [comment] 2020-08-05 17:16
This may be related to https://devdiv.visualstudio.com/DevDiv/_workitems/edit/941827

**Comment by BenVillalobos** [comment] 2021-05-21 23:00
First pass investigation notes:

It looks like, by design, MSBuild clears out files created in a prior build that weren't created in the current build after a build completes.

Here's the order of operations:
**Successful run**
1. Build test project
2. test references parent, so build parent.
3. parent explicitly copies the nupkg into its output dir
4. test copies parents contents into its output dir
5. Incremental clean runs
	1. Grab all files created last build (none)
	2. Compare to this build.
	3. Delete any that were created before but not this time
6. Your nupkg is fine.

**Your scenario**
1. Build test project
2. test references parent BUT parent built successfully last run
3. no parent build
4. test does not copy parent build outputs
5. Incremental clean runs
	1. Grab all files created last build (parent's generated projects INCLUDING nupkg)
	2. Compare to this build (which didn't grab the nupkg because the parent didn't build)
	3. Delete the diff
6. nupkg is deleted.

I'm not sure if there is any existing infrastructure to _always_ copy certain outputs from transitive references. I'll ask the team.

As a very imperfect & temporary solution you can create a target similar to the one that exists in your parent project that always copies over the nupkg.

**Comment by BenVillalobos** [comment] 2021-06-02 16:46
> I'm not sure if there is any existing infrastructure to always copy certain outputs from transitive references. I'll ask the team.

I asked the team 🙂 See: https://github.com/dotnet/msbuild/issues/1054#issuecomment-847959047

**Comment by BenVillalobos** [comment] 2021-06-02 16:46
Closing this, let us know if it doesn't resolve your issue!

**Closed by BenVillalobos** 2021-06-02 16:46 UTC
Labels: Under Investigation, untriaged
