### ISSUE TITLE
SDK tools path not set correctly for .NET Fx 4.8.1

### ISSUE THREAD

**Issue by mthalman** [dotnet/msbuild#8027] opened 2022-10-06 13:09 UTC
On a machine that has VS Build Tools 17.3 and the .NET Fx 4.8.1 SDK installed, when attempting to build a .NET Fx 4.8.1 project that contains resx files, it fails with the error:

```
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(3873,5): error MSB3086: Task could not find "al.exe" using the SdkToolsPath "" or the registry key "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.8\WinSDK-NetFx40Tools-x86". Make sure the SdkToolsPath is set and the tool exists in the correct processor specific location under the SdkToolsPath and that the Microsoft Windows SDK is installed [C:\app\ClassLibrary1.csproj]
```

This can be worked around by manually setting the `TargetFrameworkSDKToolsDirectory` MSBuild property to `C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8.1 Tools`.

This is the same issue that occurred for .NET Fx 4.8:
* https://github.com/microsoft/dotnet-framework-docker/issues/313
* https://github.com/dotnet/msbuild/pull/4487
* https://github.com/dotnet/msbuild/pull/4895

Here's a repro project: [ClassLibrary1.zip](https://github.com/dotnet/msbuild/files/9725059/ClassLibrary1.zip). You just need to build the Dockerfile in order to reproduce the error.

**Comment by BenVillalobos** [comment] 2022-11-10 18:41
@mthalman which install places the registry key for the arm64 framework install location? I have 481 and latest VS installed on an arm64 machine but don't see it.

**Comment by mthalman** [comment] 2022-11-10 19:04
> @mthalman which install places the registry key for the arm64 framework install location? I have 481 and latest VS installed on an arm64 machine but don't see it.

I don't know anything about the Arm64 aspect of VS. This issue isn't specific to Arm64. I discovered this was broken as a result of running the tests we have for the .NET Framework Docker images. You can see how we install VS Build Tools here: https://github.com/microsoft/dotnet-framework-docker/blob/8c71a8820c73eb96bb58a3140c49c92108c4f8b8/src/sdk/4.8.1/windowsservercore-ltsc2022/Dockerfile#L30-L43

**Comment by BenVillalobos** [comment] 2022-11-11 22:52
I managed to find the right registry key (in the 32-bit reg, not the 64-bit reg), arm64 was misleading and related to another issue similar to this one. 

I'm trying to reproduce this issue but I'm running into `failed to register layer: Error processing tar file(exit status 1): link /Files/Program Files/Common Files/System/ado/en-US/msader15.dll.mui /Files/Program Files (x86)/Common Files/System/ado/en-US/msader15.dll.mui: no such file or directory`, which looks unfamiliar to me and confusing because the file does exist on disk. Does this look familiar to you?

**Comment by BenVillalobos** [comment] 2022-11-11 23:58
Thanks @rainersigwald for helping me figure out what the issue was above, I needed to switch over to windows container mode.

Just verified this is resolved by https://github.com/dotnet/msbuild/pull/7689

Here's the Dockerfile showing that MSBuild.exe.config was overwritten with my custom config from [this commit](d2f8b521bab).

```dockerfile
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8.1-windowsservercore-ltsc2022 AS build

ARG src="MSBuild.exe.config"
ARG target="C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/MSBuild/Current/Bin/amd64/MSBuild.exe.config"

WORKDIR /app
COPY . .

COPY ${src} ${target}

RUN msbuild.exe /restore ClassLibrary1.csproj
```

And here's the log:
```
C:\src\repros\docker-481\ClassLibrary1>docker build .
Sending build context to Docker daemon  1.561MB
Step 1/7 : FROM mcr.microsoft.com/dotnet/framework/sdk:4.8.1-windowsservercore-ltsc2022 AS build
 ---> 553e10a1010b
Step 2/7 : ARG src="MSBuild.exe.config"
 ---> Running in 8f0b72fc62c8
Removing intermediate container 8f0b72fc62c8
 ---> 44cbedcaf6de
Step 3/7 : ARG target="C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/MSBuild/Current/Bin/amd64/MSBuild.exe.config"   
 ---> Running in f06414160fb8
Removing intermediate container f06414160fb8
 ---> c0c8ec310d26
Step 4/7 : WORKDIR /app
 ---> Running in 08a568d13bae
Removing intermediate container 08a568d13bae
 ---> b8a609ef744f
Step 5/7 : COPY . .
 ---> 7908d0ca5ce2
Step 6/7 : COPY ${src} ${target}
 ---> 6826d7291940
Step 7/7 : RUN msbuild.exe /restore ClassLibrary1.csproj
 ---> Running in 55356e6491c2
MSBuild version 17.4.0+18d5aef85 for .NET Framework
Build started 11/11/2022 3:52:01 PM.
Project "C:\app\ClassLibrary1.csproj" on node 1 (Restore target(s)).
_GetAllRestoreProjectPathItems:
  Determining projects to restore...
Restore:
  X.509 certificate chain validation will use the default trust store selected by .NET.
  Restoring packages for C:\app\ClassLibrary1.csproj...
  Generating MSBuild file C:\app\obj\ClassLibrary1.csproj.nuget.g.props.
  Generating MSBuild file C:\app\obj\ClassLibrary1.csproj.nuget.g.targets.
  Writing assets file to disk. Path: C:\app\obj\project.assets.json
  Restored C:\app\ClassLibrary1.csproj (in 242 ms).

  NuGet Config files used:
      C:\Users\ContainerAdministrator\AppData\Roaming\NuGet\NuGet.Config

  Feeds used:
      https://api.nuget.org/v3/index.json
Done Building Project "C:\app\ClassLibrary1.csproj" (Restore target(s)).
Project "C:\app\ClassLibrary1.csproj" on node 1 (default targets).
CoreResGen:
  Processing resource file "Resource1.resx" into "obj\Debug\net481\ClassLibrary1.Resource1.resources".
  Processing resource file "Resource1.en-GB.resx" into "obj\Debug\net481\ClassLibrary1.Resource1.en-GB.resources".
CoreGenerateAssemblyInfo:
Skipping target "CoreGenerateAssemblyInfo" because all output files are up-to-date with respect to the input files.
CoreCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Roslyn\csc.exe /noconfig /unsafe- /checked- /nowarn:1701,1702,IL2121,1701,1702 /fullpaths /nostdlib+ /errorreport:prompt /warn:4 /define:TRACE;DEBUG;NETFRAMEWORK;NET481;NET20_OR_GREATER;NET30_OR_GREATER;NET35_OR_GREATER;NET40_OR_GREATER;NET45_OR_GREATER;NET451_OR_GREATER;NET452_OR_GREATER;NET46_OR_GREATER;NET461_OR_GREATER;NET462_OR_GREATER;NET47_OR_GREATER;NET471_OR_GREATER;NET472_OR_GREATER;NET48_OR_GREATER;NET481_OR_GREATER /highentropyva+ /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8.1\mscorlib.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8.1\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8.1\System.Data.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8.1\System.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\  Creating directory "obj\Debug\net481\en-GB".  C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8.1 Tools\x64\al.exe /culture:en-GB /out:obj\Debug\net481\en-GB\ClassLibrary1.resources.dll /template:obj\Debug\net481\ClassLibrary1.dll /embed:obj\Debug\net481\ClassLibrary1.Resource1.en-GB.resourcesCopyFilesToOutputDirectory:  Copying file from "C:\app\obj\Debug\net481\ClassLibrary1.dll" to "C:\app\bin\Debug\net481\ClassLibrary1.dll".  ClassLibrary1 -> C:\app\bin\Debug\net481\ClassLibrary1.dll
  Copying file from "C:\app\obj\Debug\net481\ClassLibrary1.pdb" to "C:\app\bin\Debug\net481\ClassLibrary1.pdb".
  Creating directory "bin\Debug\net481\en-GB".
  Copying file from "C:\app\obj\Debug\net481\en-GB\ClassLibrary1.resources.dll" to "C:\app\bin\Debug\net481\en-GB\ClassLibrary1.resources.dll".
Done Building Project "C:\app\ClassLibrary1.csproj" (default targets).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.22
Removing intermediate container 55356e6491c2
 ---> a9f57b8f52a8
Successfully built a9f57b8f52a8
```

**Closed** 2022-12-05 20:54 UTC
Labels: bug
