### ISSUE TITLE
[Bug]: TerminalLogger is inconsistent with old logger after hitting Ctrl+C

### ISSUE THREAD

**Issue by MichalPavlik** [dotnet/msbuild#9031] opened 2023-07-13 14:33 UTC
### Issue Description

Old logger shows `Attempting to cancel the build...` message when user is cancelling build. Terminal logger just ends with failed build. This one is probably minor :)

### Steps to Reproduce

Hit Ctrl+C during build.

### Expected Behavior

Cancellation message is written to the log.

### Actual Behavior

Cancellation message is not written to the log.

**Comment by rainersigwald** [comment] 2023-07-13 14:36
Duplicate of #8983

**Closed by rainersigwald** 2023-07-13 14:36 UTC
Labels: bug, needs-triage, Area: Terminal Logger
