### ISSUE TITLE
[Feature Request]: Design and implement progress messages API

### ISSUE THREAD

**Issue by AR-May** [dotnet/msbuild#10415] opened 2024-07-19 13:37 UTC
### Summary

Design and implement a new API for progress reporting for Tasks. 
Consume and show progress messages in new Terminal Logger.

### Background and Motivation

Many messages that are logged by the tasks are ephemeral and reporting the progress of the task. It would be beneficial to create an API to distinguish such messages and be able to process them in the loggers, especially Terminal Logger. After implementing we shall work with other teams to migrate usage of `message-as-progress-reporting` to the new progress message API.

### Proposed Feature

No details yet.

**Comment by maridematte** [comment] 2024-11-06 16:13
Closing as a duplicate of: https://github.com/dotnet/msbuild/issues/6944

**Closed by maridematte** 2024-11-06 16:13 UTC
Labels: Feature Request, triaged, Area: Terminal Logger
