### ISSUE TITLE
[Bug]: Files from referenced assembly are copied despite setting Private to False

### ISSUE THREAD

**Issue by AlexG5T** [dotnet/msbuild#8756] opened 2023-05-13 13:40 UTC
### Issue Description

A minimal sample project that reproduces the issue:

*Main.sln*
```
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 17
VisualStudioVersion = 17.0.31903.59
MinimumVisualStudioVersion = 10.0.40219.1
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "P1", "P1\P1.csproj", "{48CDE3E7-2C01-4AFB-BB03-A42E20C81E10}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "P2", "P2\P2.csproj", "{22FE0983-46BC-40D9-8501-BB33338F7A1B}"
	ProjectSection(ProjectDependencies) = postProject
		{48CDE3E7-2C01-4AFB-BB03-A42E20C81E10} = {48CDE3E7-2C01-4AFB-BB03-A42E20C81E10}
	EndProjectSection
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{48CDE3E7-2C01-4AFB-BB03-A42E20C81E10}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{48CDE3E7-2C01-4AFB-BB03-A42E20C81E10}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{48CDE3E7-2C01-4AFB-BB03-A42E20C81E10}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{48CDE3E7-2C01-4AFB-BB03-A42E20C81E10}.Release|Any CPU.Build.0 = Release|Any CPU
		{22FE0983-46BC-40D9-8501-BB33338F7A1B}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{22FE0983-46BC-40D9-8501-BB33338F7A1B}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{22FE0983-46BC-40D9-8501-BB33338F7A1B}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{22FE0983-46BC-40D9-8501-BB33338F7A1B}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
EndGlobal
```

*P1\P1.csproj*
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <None Include="Test.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
```

*P1\Main.cs*
```
namespace P1 {
  public static class Program {
    public static void Main() { }
  }
}
```

*P1\Test.txt*
```
-
```

*P2\P2.csproj*
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="P1">
      <HintPath>..\P1\bin\Debug\net48\P1.exe</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>
```

*P2\C1.cs*
```
namespace P2 {
  public class C1 { }
}
```

### Steps to Reproduce

Now build the project:

```
dotnet build
```

### Expected Behavior

The expected result is not having Test.txt in the output folder.

When building project one-by-one this doesn't happen:

```
> dotnet build .\P1\P1.csproj
> dotnet build .\P2\P2.csproj
> dir .\P2\bin\Debug\net48\
... prints P2.dll and P2.pdb ...
```

### Actual Behavior

Output folder contains Test.txt.

```
> dir .\P2\bin\Debug\net48\
... prints P2.dll, P2.pdb, and Test.txt ...
```

### Versions & Configurations

```
> dotnet --version
7.0.203
> dotnet --list-sdks
7.0.203 [C:\Program Files\dotnet\sdk]
```

**Comment by AlexG5T** [comment] 2023-05-14 14:18
I've tried to use ProjectReference, but it also does not respect Private completely. If I add a project "P0" and reference it from P1 and then use project reference from P2 (i.e. P2 project-references P1 with Private=False, P1 project-references  P0) then on build dotnet copies P0 binaries to P2's target folder (and does not copy P1's binaries, so Private is respected but not for dependencies).

**Comment by AlexG5T** [comment] 2023-05-14 14:25
@KalleOlaviNiemitalo Thank you for looking into that. Indeed, I've added dependency into solution for sequencing only.

I do not mind using ProjectReference but ideally a non-private reference should not copy anything to the current project. Unfortunately, it does.

**Comment by JanKrivanek** [comment] 2023-05-28 18:58
Related: #4795 (attempt to express build ordering only)

@AlexG5T It sounds that above mentioned case is related to you. In your case you need only `<Private>false</Private>` (to prevent copying of build outputs of P1 into P2 output) and `<ExcludeAssets>all</ExcludeAssets>` (as P1 is and `.exe`, so additional supplemental files need to be explictly removed).
Note those apply to `ProjectReference`. Using a `Reference` for a build output of a project that is a part of the build is not recommended practise (and while build of entire solution behaves unexpectedly here - as it is able to locate `P1.csproj` project via `MSBuildProjectReferenceExistent` metada populated during the build of  `P1.csproj` - it's of a low priority for addressing now as it has recommended workaround - expresing the relationship directly via `ProjectReference`).

So the suggested `P2.csproj`:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../P1/P1.csproj">
      <Private>false</Private>
      <ExcludeAssets>all</ExcludeAssets>
    </ProjectReference>
  </ItemGroup>
</Project>
```

**Comment by AlexG5T** [comment] 2023-05-28 23:16
Thank you for the workaround. `ProjectReference` with `<Private>false</Private>` and `<ExcludeAssets>all</ExcludeAssets>` solved the build ordering without the solution.

**Comment by JanKrivanek** [comment] 2023-05-29 07:40
Closing as duplicate of #4795

**Closed by JanKrivanek** 2023-05-29 07:40 UTC
Labels: bug, Iteration:2023May
