### ISSUE TITLE
How to copy the xml file contained in the imported nuget package to the output directory?

### ISSUE THREAD

**Issue by FalconWu2017** [dotnet/msbuild#8300] opened 2023-01-11 02:56 UTC
In ConsoleApp4.csproj  
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
  </ItemGroup>

</Project>
```   
Output:  
![image](https://user-images.githubusercontent.com/34147999/211707019-4ba30c82-aa9d-4d21-a0eb-9deed179f715.png)  
I want to include file  `Newtonsoft.Json.xml`.   
What should I am going to do?

**Comment by rainersigwald** [comment] 2023-01-11 15:41
Duplicate of dotnet/sdk#9498

**Comment by rainersigwald** [comment] 2023-01-11 15:41
@FalconWu2017 there are some suggestions for you in the tracking issue for this, dotnet/sdk#9498.

**Closed by rainersigwald** 2023-01-11 15:41 UTC
Labels: untriaged

**Comment by baronfel** [comment] 2023-01-11 16:41
Can you take a look at the new [PublishReferencesDocumentationFiles](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#publishreferencesdocumentationfiles) property in the 7.0 SDKs and see if that is what you're looking for @FalconWu2017?
