### ISSUE TITLE
Warning NETSDK1179 is always raised

### ISSUE THREAD

**Issue by nagya** [dotnet/msbuild#7618] opened 2022-05-11 18:31 UTC
### Issue Description

The warning `NETSDK1179` is always raised when the `--runtime` switch is used, even if `--self-contained` or `--no-self-contained` is also used.

### Steps to Reproduce

```
% cat Test1.csproj 
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
</Project>

% dotnet --version
6.0.300

% dotnet build --self-contained --runtime osx-x64  
Microsoft (R) Build Engine version 17.2.0+41abc5629 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /Users/nagya/ms/Test1B/Test1.csproj (in 115 ms).
/usr/local/share/dotnet/sdk/6.0.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1114,5): warning NETSDK1179: One of '--self-contained' or '--no-self-contained' options are required when '--runtime' is used. [Test1.csproj]
  Test1 -> /Users/nagya/ms/Test1B/bin/Debug/net6.0/osx-x64/Test1.dll

Build succeeded.

/usr/local/share/dotnet/sdk/6.0.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1114,5): warning NETSDK1179: One of '--self-contained' or '--no-self-contained' options are required when '--runtime' is used. [Test1.csproj]
    1 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.09
% 


```
### Expected Behavior

No warning.

### Actual Behavior

Warning is raised, which in a typical CI scenario, where warnings are treated as errors, fails the build.

### Analysis

Issue started with .NET 6.0.300, was not present in earlier versions.

### Versions & Configurations

```
% dotnet --version
6.0.300
```

**Comment by acohenOT** [comment] 2022-05-11 18:35
Duplicate of https://github.com/dotnet/sdk/issues/24269

**Comment by acohenOT** [comment] 2022-05-11 18:43
> Not quite, this started in the 6.0.300 stable release, and unconditionally: when the `--self-contained` switch is used, when the `--no-self-contained` switch is used, or when neither switch is used. It's impossible to get warning-free behavior.

It was originally reported in the preview release, but it was not fixed and is now in stable. Either way, the issue is with `dotnet` SDK not `msbuild`.

**Closed** 2022-05-11 18:49 UTC
Labels: bug, needs-triage
