### ISSUE TITLE
[Feature Request]: Enable Terminal Logger integration with other terminal-aware tools

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/msbuild#8773] opened 2023-05-18 17:02 UTC
### Summary

Provide a mechanism for a build to opt-in external executable invocations (ie. the `Exec` task or on `ToolTask`) to have their output included in the TerminalLogger output.

### Background and Motivation

The new Terminal Logger introduced in .NET 8.0.100 Preview 4 is really slick and I really enjoy it. I have noticed one limitation though. When invoking scripts through `Exec`, all output is swallowed. In some cases, the `Exec` task is executing another tool that is also "terminal-aware" and whose output would fit in with the new logger. Also, if the external tool doesn't output errors with a recognized warning/error format, then the build would fail, but the error would not be visible.

In particular, I'm hitting this scenario with dotnet/runtime's usage of the Ninja build system for our native build. Ninja is also terminal-aware, but the mechanism of invoking the script with the `ninja` command through MSBuild ends up blocking the terminal-aware experience. Additionally, when using the new TerminalLogger, the output from the `ninja` command is hidden.

### Proposed Feature

Provide a mechanism (such as a property on `ToolTask`) to signal MSBuild to execute the underlying command such that tools executed by that command recognize their stdout as a smart terminal and that the output is shown to the user.

**Comment by AR-May** [comment] 2023-05-23 13:54
FYI @baronfel

**Comment by baronfel** [comment] 2023-05-23 13:56
Yep! This one is going to take A LOT of design, even more than the proposed issue for signalling progress reporting from tasks. I'm not sure that we should go down a road that makes MSBuild start acting like a virtual TTY to that degree, but am happy to talk more about the use case. There will likely be a number of enhancements to TerminalLogger based on issues and feedback like this, so we're in a 'wait and see' mode for the near future while we gather feedback.

**Comment by maridematte** [comment] 2024-11-06 16:24
Closing as a duplicate of: https://github.com/dotnet/msbuild/issues/8773. Please check the other issue for progress.

**Closed by maridematte** 2024-11-06 16:24 UTC
Labels: backlog, Feature Request, triaged, Area: Terminal Logger, gathering-feedback

**Comment by jkoritzinsky** [comment] 2024-11-06 16:33
@maridematte you closed this issue as a duplicate of itself. Was that intentional?

**Comment by maridematte** [comment] 2024-11-06 16:35
Nop, that was my mistake. It is a dupe of this one: https://github.com/dotnet/msbuild/issues/8875

**Comment by jkoritzinsky** [comment] 2024-11-06 16:36
Sounds good. Thanks for the update!
