### ISSUE TITLE
Number unexpectedly not recognized when in Swedish locale

### ISSUE THREAD

**Issue by danmoseley** [dotnet/msbuild#5502] opened 2020-07-10 01:18 UTC
### Steps to reproduce

Build this with English (US) Windows settings. It will succeed. 
Now go to Control Panel>Region>Change Date/Time/number formats>Formats tab, change to Swedish, OK. No need to reboot or reopen the command prompt.
Now build it again.
```xml
<Project>

  <PropertyGroup>
    <p>abc</p>
  </PropertyGroup>

  <Target Name="t" Condition=" $(p.IndexOf('x')) >= 0 " />
  
</Project>

```
### Expected behavior

Success-  no output - the condition is valid and evaluates to `-1 >= 0` 

### Actual behavior

```
C:\proj\x.proj(7,34): error MSB4086: A numeric comparison was attempted on "$(p.IndexOf('x'))" that evaluates to "-1" instead of a number, in condition " $(p.IndexOf('x')) >= 0 ".
```

### Environment data

`msbuild /version` output:
```
C:\proj>dotnet msbuild /version
Microsoft (R) Build Engine version 16.7.0-preview-20310-07+ee1c9fd0c for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

16.7.0.31007
```
OS info:

Windows 10, 2004

### Comments

We should parse all numbers out of strings in Invariant mode:

https://github.com/microsoft/msbuild/blob/e70a3159d64f9ed6ec3b60253ef863fa883a99b1/src/Build/Evaluation/Conditionals/NumericComparisonExpressionNode.cs#L44
https://github.com/microsoft/msbuild/blob/e70a3159d64f9ed6ec3b60253ef863fa883a99b1/src/Shared/ConversionUtilities.cs#L99

I'm not sure what's going on. Note also, that the negative sign in Sweden is apparently the regular `-`.

cc @maloo

**Comment by maloo** [comment] 2020-07-10 08:35
Thanks for filing the issue. I want to note that decimal point and list separator is different in Swedish regional settings. So if you somehow use double/floats here instead of integers that could be an issue.

**Comment by danmosemsft** [comment] 2020-07-11 01:04
Having trouble reproing on another machine. Repro machine is Windows version 2004  19587.100 and msbuild16.7.0.31007, non repro is 19041.329 and 16.7.0.33088. That may not be relevant.

The key setting seems to be "Regional Format" (in the new style control panel) which corresponds to "Format" in the "Region" dialog -- the two toggle the same setting, but only lazily update to match each other.

@maloo what versions do you have of these? Does building the above project repro for you with Swedish settings?

**Comment by maloo** [comment] 2020-07-11 01:43
@danmosemsft yes, I can repro:
Windows 1909 18363.900
MSBuild 16.7.0.31007

And running $env:DOTNET_SYSTEM_GLOBALIZATION_INVARIANT = 1 before makes the error go away.

**Comment by maloo** [comment] 2020-07-11 01:49
I also tried MSBuild 16.6.0.22303 in dev cmd 2019, and could not repro. So looks like a regression of msbuild (or dotnet).

**Comment by maloo** [comment] 2020-07-11 03:08
I cloned and built msbuild and version 16.8.0.36101 seems to work. Maybe just have forward this issue to dotnet/runtime and ask them to update to 16.8?

**Comment by maloo** [comment] 2020-07-11 03:23
vs16.7 - 16.7.0.36101 also works, no repro. Is there any difference between "standalone msbuild" and msbuild bundled with dotnet?

**Comment by maloo** [comment] 2020-07-11 03:24
I built the net472 base version, so maybe it is dotnet core related?

**Comment by danmosemsft** [comment] 2020-07-11 04:21
Unfortunately building my own copy to the same SHA doesn't give me a repro, and debugging the release version is not helpful so far.

**Comment by danmosemsft** [comment] 2020-07-11 04:56
It's not https://github.com/microsoft/msbuild/issues/5360 because that requires the 2-parameter overload.

**Comment by danmosemsft** [comment] 2020-07-11 04:58
I don't plan to look more, since it's apparently fixed, although it bothers me I don't see how. I will leave this issue open in case there is a test missing that builds (and evaluates conditional expressions and property functions) in a culture with different number formats.

**Comment by danmosemsft** [comment] 2021-02-08 04:01
FYI we have since discovered that when using ICU (which may be the case on some recent Windows ) the Swedish minus sign is not the typical hyphen. So the result in the bug (which may or may not be fixed now) was surely due to parsing without specifying invariant mode.

Eg https://github.com/dotnet/runtime/issues/47524

**Comment by danmoseley** [comment] 2022-09-27 03:08
@rainersigwald I suggest to close this

**Closed** 2022-09-27 13:42 UTC
Labels: bug, Localization

**Comment by MariusGjerd** [comment] 2023-08-03 08:34
This is still an issue on MacOs in Rider when using Dotnet 7, MsBuild 17.x to build Refit 6.x. The Condition they use in refit: `'$([System.Version]::Parse($(_RefitMSBuildMinVersion)).CompareTo($([System.Version]::Parse($(MSBuildVersion)))))' &gt; '0'` will evaluate to 0 and everything will break. The same repository works on Visual Studio for Mac though...

See https://github.com/reactiveui/refit/issues/1387 for other similar reporting

**Comment by hknielsen** [comment] 2024-05-23 08:44
@rainersigwald - we are also running into this issue. Setting `InvariantGlobalization` fixed it, but still seem to be a general issue with `IndexOf`

**Comment by hknielsen** [comment] 2024-05-23 08:58
Ah seem to be fixed in https://github.com/dotnet/msbuild/pull/9874
