### ISSUE TITLE
Hang in GraphConstructionCanLoadEntryPointsFromSolution

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/msbuild#5520] opened 2020-07-16 18:42 UTC
Build: https://dev.azure.com/dnceng/public/_build/results?buildId=733674&view=results hit this hang

```
   Microsoft.Build.Engine.UnitTests: [Long Running Test] 'Microsoft.Build.Graph.UnitTests.GraphLoadedFromSolutionTests.GraphConstructionCanLoadEntryPointsFromSolution', Elapsed: 00:53:01
```

Logs: https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/733674/artifacts?artifactName=CoreOnWindows%20build%20logs&api-version=5.1&%24format=zip

**Comment by Forgind** [comment] 2021-01-04 16:29
Different test name, but this and #5453 seem too similar to be coincidental. Closing as a duplicate of that one.

**Closed by Forgind** 2021-01-04 16:29 UTC
Labels: Area: Our Own Build, flaky-test, testing
