### ISSUE TITLE
Building target "GenerateBindingRedirects" completely

### ISSUE THREAD

**Issue by yuehuang010** [dotnet/msbuild#9527] opened 2023-12-12 22:03 UTC
Creating this issue to track the follow up to reverting #9338.

### Repro: 
Checkout dotnet/msbuild
msbuild /t:restore
msbuild
msbuild /question

### Error:
```
Target Name=GenerateBindingRedirects Project=Microsoft.Build.Framework.csproj
    Errors
        Building target "GenerateBindingRedirects" completely. [C:\source\msbuild\src\Framework\Microsoft.Build.Framework.csproj]
    Input file "C:\source\msbuild\artifacts\obj\Microsoft.Build.Framework\Microsoft.Build.Framework.csproj.nuget.g.targets" is newer than output file "C:\source\msbuild\artifacts\obj\Microsoft.Build.Framework\Debug\net472\Microsoft.Build.Framework.dll.config".
```

### Analysis:
The Target's output isn't updated because the GenerateBindingRedirects task will skip writing to the output if the content are the same.

### Possible Fix:
Remove both the target's Inputs and Outputs parameter.
Or remove the "$(MSBuildAllProjects)" from the Inputs.

**Comment by KirillOsenkov** [comment] 2024-03-07 03:12
Ran into the same thing, broken incrementality because the GenerateBindingRedirects task is smart, and it won't touch the output file if the contents didn't change. However if you have an input that changed, but didn't influence the contents of the output file, you get stuck (since the output file continues to be older than the input that has changed).

I think this is a general problem where if a target declares inputs and outputs, and the task inside it doesn't rewrite the outputs if they haven't changed, you'll have this problem. Not sure if it has an official name.

Perhaps always touch the output file and rely on the Inputs/Outputs mechanism? But the problem is if any of the reference dlls have changed, you probably want to recompute binding redirects, since it's impossible to capture all inputs of RAR in the Inputs of the target.

I also notice there's the $(SuggestedBindingRedirectsCacheFile) and the _GenerateSuggestedBindingRedirectsCache target, perhaps there's something more sophisticated going on?

**Comment by KirillOsenkov** [comment] 2024-03-07 03:14
Duplicate of #9337

**Closed** 2024-04-09 13:39 UTC
