### ISSUE TITLE
Ctrl+C to cancel a build while Copy task is retrying crashes MSBuild

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#6752] opened 2021-08-12 03:52 UTC
When the Copy task is in retry loop when a destination file is locked, pressing Ctrl+C will crash MSBuild because we'll not respect OperationCanceledException:

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4679,5): warning MSB3026: Could not copy "C:\Users\kirill\.nuget\packages\nerdbank.streams\2.6.81\lib\netstandard2.0\Nerdbank.Streams.dll" to "C:\bin\Debug\Nerdbank.Streams.dll". Beginning retry 9 in 1000ms. The process cannot access the file 'C:\bin\Debug\Nerdbank.Streams.dll' because it is being used by another process. The file is locked by: " (11864)"

System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.Tasks.Copy.CopyParallel(CopyFileWithState copyFile, Int32 parallelism, List`1& destinationFilesSuccessfullyCopied)
   at Microsoft.Build.Tasks.Copy.Execute(CopyFileWithState copyFile, Int32 parallelism)
   at Microsoft.Build.Tasks.Copy.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

**Comment by KirillOsenkov** [comment] 2021-08-12 03:59
I mean, the process does terminate as a result, as desired... so it kinda accomplishes the goal, just a tad eagerly

**Comment by danmoseley** [comment] 2022-04-11 00:10
dupe of #3891

**Closed by danmoseley** 2022-04-11 00:10 UTC
Labels: up-for-grabs, Area: Tasks, grab-next
