### ISSUE TITLE
[Bug]: Condition attribute is ignored in legacy csproj files when referenced from an SDK csproj file 

### ISSUE THREAD

**Issue by MovGP0** [dotnet/msbuild#8889] opened 2023-06-15 14:41 UTC
### Issue Description

When an SDK style csproj file references an legacy csproj file, that references other projects conditionally based on the build target, the condition in the legacy project file is ignored.

When the SDK style project file is backported to an legacy csproj file format, the build works fine.

### Steps to Reproduce

**Sdk.csproj**
```xml
<Project Sdk="Microsoft.NET.Sdk">
<!-- ... -->
<ItemGroup>
    <ProjectReference Include="..\Legacy\Legacy.csproj" />
  </ItemGroup>
</Project>
```

**Legacy.csproj**
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
<!-- ... -->
<ItemGroup Condition=" '$(Configuration)|$(Platform)' == 'False|False' ">
    <ProjectReference Include="..\Legacy2\Legacy2.csproj"  Condition=" '$(Configuration)|$(Platform)' == 'False|False' " />
  </ItemGroup>
</Project>
```

### Expected Behavior

The `Condition` attribute should be honored.

### Actual Behavior

The condition is ignored and the build breaks because it can't build the `Legacy2` project.

### Analysis

Our current workaround is to use legacy .csproj file format only.

### Versions & Configurations

MSBuild version 17.6.3+07e294721 for .NET Framework
17.6.3.22601

Visual Studio Version 17.6.3

**Comment by AR-May** [comment] 2023-06-20 14:01
@JaynieBai, could you please reproduce it and collect binlog?

**Comment by JaynieBai** [comment] 2023-07-04 09:17
[ConsoleApp5.zip](https://github.com/dotnet/msbuild/files/11947215/ConsoleApp5.zip)
```mermaid
flowchart LR
    ClassLibrary1[ ClassLibrary1] --> ClassLibraryLegacy2
    ClassLibraryLegacy2[ClassLibraryLegacy2] --> ClassLibraryLegacy3[ClassLibraryLegacy3]
```
Here the ClassLibraryLegacy3 projectreference condition in project ClassLibraryLegacy2 is false all the time. So, when using ClassLibraryLegacy3 in ClassLibrary1 should report error. But when build with visual studio, it references the ClassLibraryLegacy3 successfully.

**Repro steps: **  
1.  Download the solution.
2.  Open the solution with Visual studio.
3.  Right click the solution and restore NuGet packages.
4.   Find the project.assets.json file in the ClassLibrary1 including the ClassLibraryLegacy3.dll, this is not expected.
5.   Delete the project.assets.json file in the ClassLibrary1 and run dotnet restore or NuGet restore with command.
6.    Find the project.assets.json file in the ClassLibrary1 not including the ClassLibraryLegacy3.dll, this is expected.

 I think this should be a NuGet issue.

**Comment by nkolev92** [comment] 2023-07-05 18:09
@JaynieBai 

Visual Studio in general has a limitation that item conditions are not respected. 

See details: https://github.com/NuGet/NuGet.Client/pull/5293/files.

**Comment by JaynieBai** [comment] 2023-07-06 02:24
Close this since this is an intentional design in NuGet restore in Visual Studio.

**Closed by JaynieBai** 2023-07-06 02:24 UTC
Labels: Partner:NuGet

**Comment by MovGP0** [comment] 2023-07-10 06:09
The NuGet restore is working fine. It's the build that makes problems.

**Comment by JaynieBai** [comment] 2023-07-12 06:45
> It's the build that makes problems.
The build has problems since condition is not  respected in VS when NuGet Restore https://github.com/NuGet/Home/issues/12729#issue-1790050248
