### ISSUE TITLE
Non-string resources require the System.Resources.Extensions assembly at runtime, but it was not found in this project's references.

### ISSUE THREAD

**Issue by Rackover** [dotnet/msbuild#5787] opened 2020-10-08 12:11 UTC
This issue has been reported before, I believe here : https://github.com/dotnet/msbuild/issues/2221
However unlike presented in this thread, it still appears past versions 16.3+ of MSBuild. I'm personally running `Microsoft (R) Build Engine version 16.7.0+7fb82e5b2 for .NET`

### Issue Description
My windows form app can be built successfully using Visual Studio 2019, but:

- Cannot be built with dotnet msbuild from command line
- Cannot be built with dotnet publish from command line
- Cannot be built with "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe" from command line.

### Steps to Reproduce

Here are the arguments I used for all three of them:
`-target:Publish /p:Configuration=Release /p:GenerateResourceUsePreserializedResources=True /p:OutDir="../Build"`

### Expected Behavior

The app builds successfully to the target folder.

### Actual Behavior

All three of them output some version of the following text:
```
error MSB3822: Non-string resources require the System.Resources.Extensions assembly at runtime, but it was not found in this project's references. [my.csproj]
```

However, none of my .resx in my windows form project have any image. Only one contains non-string content, of the following nature:
![image](https://user-images.githubusercontent.com/33836535/95455900-d2a4cb80-096e-11eb-9dcf-85c1bead2488.png)
The other .resx i have seems to be doing fine without any non-string resource, but not this one - deleting these elements lead to malfunction.

Moreover, if I do try to embed the "System.Resources.Extensions" that is being mentioned here, my app does build, but said window cannot be opened.
`<PackageReference Include="System.Resources.Extensions" Version="4.7.1" />`

![image](https://user-images.githubusercontent.com/33836535/95456675-fae0fa00-096f-11eb-84db-ad717bbf936a.png)

### Analysis
Tried every version of System.Resources.Extensions from the top, the application seems to work correctly with `<PackageReference Include="System.Resources.Extensions" Version="4.6.0" />` for reasons unknown to me.
This is still not a good solution. I feel like I shouldn't have to include this undesired library.

### Versions & Configurations
`Microsoft (R) Build Engine version 16.7.0+7fb82e5b2 for .NET`
Windows 10 running Microsoft Visual Studio 2019

**Comment by rainersigwald** [comment] 2020-10-14 20:21
Requiring version 4.6.0 will be fixed by https://github.com/dotnet/runtime/issues/39078 when the 5.0.0 version of `System.Resources.Extensions` is released.

This reference is required when using `GenerateResourceUsePreserializedResources`, which is the default for .NET Core projects and you're specifying explicitly. It uses a form of deserialization that avoids a number of build-time problems.

> none of my .resx in my windows form project have any image

Did you see something that suggested that images are relevant here? It should only really matter whether the resources are strings or not.

> I feel like I shouldn't have to include this undesired library.

You can continue to build your application using the older resource-embedding techniques if you build from Visual Studio or `msbuild.exe` and target .NET Framework.

**Comment by Rackover** [comment] 2020-10-16 09:34
Doesn't msbuild.exe equivalent `dotnet msbuild` ? I thought one was a shortcut for the other.

I'm trying again with targetting specifically my NET framework version (471) and removing the generation of preserialized resources, but I still cannot build.

`dotnet msbuild -target:Publish /p:Configuration=Release /p:OutDir="../Build" /p:TargetFramework=net471`

```
C:\Program Files\dotnet\sdk\3.1.402\Microsoft.Common.CurrentVersion.targets(3036,5): error MSB4216: Could not run the "GenerateResource" task because MSBuild could not create or connect to a task host with runtime "CLR4" and architecture "x86".  Please ensure that (1) the requested runtime and/or architecture are available on the machine, and (2) that the required executable "C:\Program Files\dotnet\sdk\3.1.402\MSBuild.exe" exists and can be run. [C:\THE_LAST_STAND\[CODE SOURCES]\TLS Save Encoder & Decoder\TLS Savegame Tool\TLS Savegame Tool.csproj]
C:\Program Files\dotnet\sdk\3.1.402\Microsoft.Common.CurrentVersion.targets(3058,7): error MSB4028: The "GenerateResource" task's outputs could not be retrieved from the "FilesWritten" parameter. Object does not match target type. [C:\THE_LAST_STAND\[CODE SOURCES]\TLS Save Encoder & Decoder\TLS Savegame Tool\TLS Savegame Tool.csproj]
```

**Comment by rainersigwald** [comment] 2020-10-16 14:46
> Doesn't msbuild.exe equivalent `dotnet msbuild` ? I thought one was a shortcut for the other.

No, that's not correct. `MSBuild.exe` has some functionality that isn't able to run on .NET Core. That's usually for two reasons:

1. It calls a tool or an API that isn't available on .NET Core, or
2. A project uses functionality that is implemented by installing things into Visual Studio.

Can you share a project that has the error you're seeing?

**Comment by Rackover** [comment] 2020-10-16 14:47
I cannot share it publicly. Is there a way to send it to you privately?

**Comment by rainersigwald** [comment] 2020-10-16 15:12
@Rackover Yes; you can file feedback at [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) and include confidential-to-Microsoft attachments. Please link the issue here so I can expedite routing it to our team.

**Comment by Rackover** [comment] 2020-10-16 15:27
I have submitted an issue, number #1224160 under .NET category.
https://developercommunity.visualstudio.com/content/problem/1224160/non-string-resources-require-the-systemresourcesex.html

I do not know if it has been made confidential to microsoft or not - I do not think so because I see an upvote button ☹️ 
That is of little importance, to be honest - but I would love the issue & the files to be deleted once you no longer need them.

**Comment by rainersigwald** [comment] 2020-10-16 15:33
I'm not sure either but I have now downloaded the attachment so you can remove it.

**Comment by rainersigwald** [comment] 2020-10-16 15:35
Your project is not a new SDK-style project (with `<Project Sdk="Microsoft.NET.Sdk">` as its first line, so it cannot be built with `dotnet msbuild` and you must continue to use `msbuild.exe` to build it.

**Comment by AraHaan** [comment] 2021-02-13 21:26
The issue here is for me on the .NET 6 SDK it only errors when building my .NET Framework 4.7.2 target, but compiles fine on my net5.0-windows target oddly enough.

However the package should not be required for the .NET Framework TFM's due to that crap being built into System.Windows.Forms.dll itself on all versions of the .NET Framework. @rainersigwald

And only TFM's my winforms project targets is oddly enough only ``net472;net5.0-windows``, however I need to use the .NET 6 SDK due to bugs in the .NET 5 SDK related to resolving my metapackage that has both .NET 5, and .NET 5-windows targets inside.

**Comment by AraHaan** [comment] 2021-02-22 11:43
cc: @BenVillalobos 

This is unacceptable to require this for .NET Framework targets as well, I would expect for .NET Core 3/3.1/.NET 5/6 builds to fail if the assembly is not referenced but .NET Framework *should* be grandfathered in as when I build with Visual Studio 2019 everything just works:tm:.

However this change to the .NET 6 SDK breaks build for cli interfaces because it *shoves* an package down your throat for .NET Framework targets that should definately not be required as non-string resouce support is built into System.Windows.Forms.dll (if I remember right) in the .NET Framework itself.

funny thing is that my project multitargets net472 and net5.0-windows (is a winforms exe too) and oddly enough does not set that property explicitly nor does it add the package. Guess which framework it errors on? You guessed it .NET Framework 4.7.2 should it should not error on since the non-string resource support is built into the framework (net472).

In this case the package just to hack the build into working again becomes an useless dependency designed to try to bloat our code and make it load a dependency in which it *should* not require when running .NET Framework builds on the multitargeted project.

Why multitarget an winforms exe you ask?

Well lets say anything can happen between .NET 5, .NET 6 and I use the .NET 4.7.2 TFM to verify if something is a regression or not.

**Comment by DaveCousineau** [comment] 2021-04-23 23:53
I must have found myself here a dozen times or more by now.

I think there is a bug when building using `dotnet` where this error is generated even when building a .NET Framework project.

My command is:
```
dotnet publish
-o <location>
-f net40
-r win-x86
-c Release
--self-contained
-v m
```

and I have conditional `ItemGroup` and `PropertyGroup` tags that have the necessary tags:

`<GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>`

and

`<PackageReference Include="System.Resources.Extensions" Version="4.7.0" />`

when building for .netcoreapp3.1

but I get the error even when building for .NET 4, where these shouldn't be required afaik.

**Comment by AraHaan** [comment] 2021-04-24 05:08
I will be making an nuget based .NET SDK that will set them for users eventually.

But in order to use it would will have to set it to that on the ``Sdk=`` attribute on the ``Project`` node on the very first like in an csproj with the package's version like so ``/1.0.0`` then it will fetch it from nuget.org.

**Comment by rainersigwald** [comment] 2021-04-26 14:41
> but I get the error even when building for .NET 4, where these shouldn't be required afaik (and in fact, can't be used I think).

This isn't correct; the package reference **is** required when building for .NET 4.

There are two aspects of non-string resources:

1. **Building** projects that use the resources, that is
  a. Reading the resources in their source form,
  a. Transforming (serializing) them into a destination form, and
  a. Embedding that into the built assembly.
2. Consuming the resources **at runtime**, that is
  a. Reading the embedded resources, and
  a. Deserializing the resource into a .NET object for your code to use.

The problems here arise because of _differences in serialization/deserialization_ between .NET Core/5.0+ and .NET Framework 4.x. 

In **.NET Framework 4.x**, non-string resources are serialized and deserialized using [`BinaryFormatter`](https://docs.microsoft.com/dotnet/api/system.runtime.serialization.formatters.binary.binaryformatter), which [cannot be made secure](https://docs.microsoft.com/dotnet/standard/serialization/binaryformatter-security-guide). 

In .NET Core/5.0+, we use different techniques. But that means that **we cannot write .NET 4.x-compatible resources from a .NET 5.0 build process**, because we don't use BinaryFormatter. We can easily serialize resources using the new serialization techniques, but they can't be read in the usual way at runtime.

Fortunately, the new more secure deserialization techniques can work on .NET 4.x with the addition of a new assembly that teaches the older framework how to handle them. That's why the new reference is required when targeting .NET 4.x from a `dotnet build` process.

**Comment by rainersigwald** [comment] 2021-04-26 14:43
@AraHaan 

> I will be making an nuget based .NET SDK that will set them for users eventually.

I don't think an SDK is necessary here; it's a property and a PackageReference, which you can set through a normal NuGet package. However, the package would then be tied to a version of `System.Resources.Extensions`, so I don't think there's much benefit in having a single package to do this rather than the existing one-package-and-one-property approach.

**Comment by DaveCousineau** [comment] 2021-04-26 16:01
k thanks, but what if .NET Framework 4.x is .NET Framework 4.0? I get 'System.Resources.Extensions' is not compatible with net40.

**Comment by rainersigwald** [comment] 2021-04-26 16:07
@DaveCousineau You may wish to request support for that TargetFramework in the https://github.com/dotnet/runtime repo.

**Comment by AraHaan** [comment] 2021-04-26 19:14
> @AraHaan
> 
> > I will be making an nuget based .NET SDK that will set them for users eventually.
> 
> I don't think an SDK is necessary here; it's a property and a PackageReference, which you can set through a normal NuGet package. However, the package would then be tied to a version of `System.Resources.Extensions`, so I don't think there's much benefit in having a single package to do this rather than the existing one-package-and-one-property approach.

The issue is the property does not work even when placed directly inside the csproj, and only applies when placed in a Directory.Build.targets, due to this many users do not know about this and they give up so that is why I decided to make one for those who do not know they can just change 1 line (as opposed to adding 6~10 lines) and needing to create a new file that most people never worked with before.

You might think, "but it will apply in Directory.Build.props" I tried that manually myself, it does not do anything at all, it only works when placed in ``Directory.Build.targets``.

As such the default .NET SDK presets it, I see no reason why projects should explicitly set it and I feel the proper functionality is for the WindowsDesktop Sdk to reference the package unconditionally as well as set the property whenever an .NET Framework TFM is referenced.

And this is because a lot of codebases either:
- refuse to make the change and consider it an .NET Sdk issue itself and as such should be set under the .NET Sdk for them.
- dumb that they would have to do it manually, they want an Sdk to set it for them so they do not have to set it and create ``Directory.Build.targets`` for every single project they have. Imagine they got over 1k projects each getting this issue.
- It could have been avoided by only adding ~10 lines of code in the WindowsDesktop Sdk itself (which now gets automatically included with the .NET 5 and 6 SDK's despite using older TFMs.

Search all the repositories on github using them, I can garentee you this: all of them think it's dumb to have to do it manually as opposed to it being an implicit ``PackageReference`` provided from the WindowsDesktop Sdk.
Also that ``PackageReference`` can just as easily be wildcarded to ``*-*`` like how my Sdk does that is why I will push it as an Sdk change instead of shoving the change down their throat and forcing them to provide it and cluttering their codebase in the process and making it less readable and them less able to find what they need in a timely basis.

**Comment by rainersigwald** [comment] 2021-04-26 19:49
> The issue is the property does not work even when placed directly inside the csproj

Can you please elaborate, @AraHaan? I can successfully embed an image with this project:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Resources.Extensions" Version="5.0.0" />
  </ItemGroup>

</Project>
```

Which just sets the property and adds the reference.

**Comment by AraHaan** [comment] 2021-04-26 19:55
> > The issue is the property does not work even when placed directly inside the csproj
> 
> Can you please elaborate, @AraHaan? I can successfully embed an image with this project:
> 
> ```
> <Project Sdk="Microsoft.NET.Sdk">
> 
>   <PropertyGroup>
>     <OutputType>Exe</OutputType>
>     <TargetFramework>net48</TargetFramework>
>     <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
>   </PropertyGroup>
> 
>   <ItemGroup>
>     <PackageReference Include="System.Resources.Extensions" Version="5.0.0" />
>   </ItemGroup>
> 
> </Project>
> ```
> 
> Which just sets the property and adds the reference.

I tried that before when a project of mine targeting both net472 and net5.0-windows.

**Comment by rainersigwald** [comment] 2021-04-26 20:07
I'm seeing everything work as I expect with `6.0.100-preview.3.21202.5`:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net472;net5.0-windows</TargetFrameworks>
    <RootNamespace>_5787</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>

    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Resources.Extensions" Version="5.0.0" />
  </ItemGroup>

</Project>
```

```sh-session
❯ dotnet build
Microsoft (R) Build Engine version 16.10.0-preview-21181-07+073022eb4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored S:\repro\dotnet\msbuild\issues\5787\5787.csproj (in 103 ms).
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  5787 -> S:\repro\dotnet\msbuild\issues\5787\bin\Debug\net5.0-windows\5787.dll
  5787 -> S:\repro\dotnet\msbuild\issues\5787\bin\Debug\net472\5787.exe

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.81

```

So if you see this again can you file a new bug with a repro project, please? It sounds like you might have a different issue than some folks here.

**Comment by AraHaan** [comment] 2021-04-26 20:42
ok

**Comment by rainersigwald** [comment] 2021-12-02 15:22
> > @DaveCousineau You may wish to request support for that TargetFramework in the https://github.com/dotnet/runtime repo.

This is now tracked by dotnet/runtime#62282.

> Then what is the point of multi-targeting by making it an Sdk style project then if they are forced to just msbuild just for 1 TFM that is within x total TFM's needed by the project?

You can use MSBuild.exe to build for all TFMs; you don't have to maintain multiple builds.

Since it sounds like things are behaving as expected given the current `System.Resources.Extensions` targeting, I'm going to close this issue.

**Closed by rainersigwald** 2021-12-02 15:22 UTC

**Comment by DataJuggler** [comment] 2023-06-24 11:43
I just updated to Visual Studio 17.6.4 and a project that has been working for months started giving me this error.

![image](https://github.com/dotnet/msbuild/assets/26331133/8a8037ca-fd39-48b7-bac2-88d8e4e80852)

**Comment by rainersigwald** [comment] 2023-06-26 14:10
@DataJuggler please file a new issue with details.

**Comment by pflajszer** [comment] 2023-10-26 12:32
Not sure what package @DataJuggler  meant, but I've experienced it in .NET 7 unit test project. Adding System.Resources.Extensions @7.0.0 resolved it

**Comment by DataJuggler** [comment] 2023-10-26 13:21
Yes, I added System.Resources.Extensions also. I forgot to update this thread.

**Comment by darrylsepeda** [comment] 2023-11-01 09:37
Hi @DataJuggler , may I know how do you add the package?
I added in ln 43 - 44 in this csproj https://codesandbox.io/s/unruffled-sound-9svqyj?file=/file.csproj, but I still encounter error MSB3822.

**Comment by DataJuggler** [comment] 2023-11-01 12:04
Hi used NuGet Package Manager GUI in Visual Studio 2022.

**Comment by darrylsepeda** [comment] 2023-11-02 07:16
@rainersigwald you were right, the errors were gone when I used 4.7.2 SDK (so I assume need to use the correct SDK to avoid this error).

but this is becoming weird..

Now I encounter this error (using SDK 4.7.2):
 C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.CSharp.CurrentVersion.targets(317,5): error MSB4019: The imported project "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets" is correct, and that the file exists on disk.

but if I install C# and VB Roslyn compilers, MSB3822 errors reappear.
Sorry, I'm not quite sure how to pass cli param -bl to VS
