### ISSUE TITLE
[Bug]: DestinationSubDirectory not working for "dotnet build"

### ISSUE THREAD

**Issue by znakeeye** [dotnet/msbuild#8803] opened 2023-05-26 14:45 UTC
### Issue Description

In a simple console project, let's reference a library and change its output folder using the less-documented **`DestinationSubDirectory`** metadata:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FooLib\FooLib.csproj"
                      DestinationSubDirectory="Libs\" />
  </ItemGroup>

</Project>
```
It works as expected when building in Visual Studio. However, when we issue `dotnet build` it will bloat the output folder. Using **MSBuild version 17.5.0+6f08c67f3**.
```
dotnet build PublishBloatTest.csproj --configuration Release --output .\artifacts
```

**Impact**
The `DestinationSubDirectory` setting is an excellent feature which makes deployment of our complex plugin-based application a lot easier. However, when built via our pipelines we face the above issue. So far, the only workaround we have found is to have an undesirable post-build action where we delete bloat from the output folder.

### Steps to Reproduce

1. Create a console project `MyApp`.
2. Create a library project `FooLib`.
3. Reference `FooLib` and set `DestinationSubDirectory="Libs\"` on the `ProjectReference`.
4. Run `dotnet build MyApp.csproj --configuration Release --output .\artifacts`

### Expected Behavior

`FooLib.dll` is only written to the `Libs` folder.

### Actual Behavior

`FooLib.dll` is written to both the root and the `Libs` folder, causing significant bloat in the published app.

### Versions & Configurations

```
MSBuild version 17.5.0+6f08c67f3 for .NET Framework
17.5.0.10706

...

Microsoft Visual Studio Professional 2022
Version 17.5.2
VisualStudio.17.Release/17.5.2+33502.453
```

**Comment by JaynieBai** [comment] 2023-06-02 09:18
[VS.binlog.txt](https://github.com/dotnet/msbuild/files/11633507/VS.binlog.txt)

[dotnet.binlog.txt](https://github.com/dotnet/msbuild/files/11633716/dotnet.binlog.txt)
Compare the binlogs above and find that if set `--output  .\artifact`s when build project references it will copy binaries (FooLib.dll) to the output directory. But when build with VS, it will build project references into its default output if not set in project file. 
It means, if set `--output  .\artifacts` when build with command, both of the parent project and project reference's output directory are the same.
![image](https://github.com/dotnet/msbuild/assets/26814373/2756f37b-2cbb-4997-8c86-a974e715225a)

**Comment by znakeeye** [comment] 2023-06-02 09:26
> [VS.binlog.txt](https://github.com/dotnet/msbuild/files/11633507/VS.binlog.txt)
> 
> [dotnet.binlog.txt](https://github.com/dotnet/msbuild/files/11633716/dotnet.binlog.txt) Compare the binlogs above and find that if set `--output .\artifacts` when build project references it will copy binaries (FooLib.dll) to the output directory. But when build with VS, it will build project references into its default output if not set in project file. It means, if set `--output .\artifacts` when build with command, both of the parent project and project reference's output directory are the same if the OutDir is not defined in the project file ![image](https://user-images.githubusercontent.com/26814373/242841306-2756f37b-2cbb-4997-8c86-a974e715225a.png)

Any conclusion from this? Should we consider this a bug, and is there a workaround?

**Comment by JaynieBai** [comment] 2023-06-02 09:34
@znakeeye You could set project reference project's property OutDir to be the different directory with .\artifacts directory.

**Comment by znakeeye** [comment] 2023-06-02 09:44
Right. If I add the following to `FooLib.csproj` it will no longer bloat the root folder:
```xml
<OutDir>bin</OutDir>
```
Maybe some generic workaround could be applied in `Directory.build.props`?

**Comment by JaynieBai** [comment] 2023-06-05 08:47
> Maybe some generic workaround could be applied in `Directory.build.props` or `Directory.build.targets`?

Yes, you can set global properties of the dependent projects in the `Directory.build.props` in order not to bloat the root folder.

**Comment by znakeeye** [comment] 2023-06-05 09:19
So is this a bug?

Ideally, a workaround should extend on the build using some target. Not sure which one though. Is it even possible?

I guess setting some property means setting `<OutDir>bin</OutDir>` for all projects and hope that nobody specifies `--output bin`. Not a super stable solution.

**Comment by JaynieBai** [comment] 2023-06-07 09:15
> So is this a bug?

This is not a bug.

> Ideally, a workaround should extend on the build using some target. Not sure which one though. Is it even possible?

There is such target to change the global property.

> I guess setting some property means setting `<OutDir>bin</OutDir>` for all projects and hope that nobody specifies `--output bin`. Not a super stable solution.

It depends on your choices. If want all the outputs in the same directory, you can specify `--output bin`. If want in the different directories, set the property OutDir specifically.

**Comment by znakeeye** [comment] 2023-06-07 11:02
In my view, it is a bug.

`VS` and `MsBuild` should behave in the same way. When building in Visual Studio, the folder is not bloated. When building using `dotnet build` it is bloated. Why the difference?

**Comment by JaynieBai** [comment] 2023-06-08 01:46
> In my view, it is a bug.
> 
> `VS` and `MsBuild` should behave in the same way. When building in Visual Studio, the folder is not bloated. When building using `dotnet build` it is bloated. Why the difference?

Your VS and MsBuild  have the different output directories.  VS project uses the default directory bin.  But dotnet build set the global output directory with setting --output

**Comment by JaynieBai** [comment] 2023-06-12 07:20
Close this issue since this is not bug.

**Closed by JaynieBai** 2023-06-12 07:20 UTC
Labels: bug, needs-triage
