### ISSUE TITLE
[Bug]: Microsoft.Build.Utilities.Core 17.11.4 NuGet package is broken

### ISSUE THREAD

**Issue by avivanoff** [dotnet/msbuild#10532] opened 2024-08-16 17:07 UTC
### Issue Description

Microsoft.Build.Utilities.Core 17.11.4 NuGet package depends on Microsoft.NET.StringTools 17.11.4 that does not exist.

### Steps to Reproduce

Create a project and add a reference to Microsoft.Build.Utilities.Core 17.11.4 NuGet package.

### Expected Behavior

Build should succeed.

### Actual Behavior

Build fails.

**Comment by baronfel** [comment] 2024-08-16 17:10
duplicate of https://github.com/dotnet/msbuild/issues/10526

**Closed by baronfel** 2024-08-16 17:10 UTC
Labels: bug
