### ISSUE TITLE
GraphBuild doesn't pick up .wapproj packaging project from a solution

### ISSUE THREAD

**Issue by LingC-GH** [dotnet/msbuild#8164] opened 2022-11-15 07:31 UTC
### Issue Description
GraphBuild doesn't pick up .wapproj packaging project from a solution

My VS solution file has several .csproj projects, one .vcxproj project and one **.wapproj** project.  When I use GraphBuild parameter to build the solution, the .csproj & .vcxproj projects are built, but the .wapproj project is not built. Looks like it is not in the graph output.

The main reason for using GraphBuild parameter is to speed up the build process. Is there a way to include .wapproj in MSBuild with GraphBuild parameter?

**Comment by rainersigwald** [comment] 2022-11-15 20:53
Duplicate of #5159

**Closed by rainersigwald** 2022-11-15 20:53 UTC
Labels: bug, needs-triage
