### ISSUE TITLE
InvalidOperationException during dotnet/aspnetcore CI build

### ISSUE THREAD

**Issue by Pilchie** [dotnet/msbuild#5232] opened 2020-04-03 17:05 UTC
### Steps to reproduce
During a public CI [build](https://dev.azure.com/dnceng/public/_build/results?buildId=587171&view=logs&j=84e1ef63-b880-5b9e-d854-397c4b952259&t=fa5725a6-a173-58a1-b999-aaff2bc14461&l=1368)

### Actual behavior

``` text
2020-04-03T08:49:30.3408029Z MSBUILD : error MSB4166: Child node "2" exited prematurely. Shutting down. Diagnostic information may be found in files in "/home/vsts/work/1/s/artifacts/log/Release" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.
2020-04-03T08:49:30.3410914Z MSBUILD : error MSB4166: /home/vsts/work/1/s/artifacts/log/Release/MSBuild_pid-4813_20bafc37a8e9403caee491b90df127a3.failure.txt:
2020-04-03T08:49:30.3412045Z MSBUILD : error MSB4166: UNHANDLED EXCEPTIONS FROM PROCESS 4813:
2020-04-03T08:49:30.3412907Z MSBUILD : error MSB4166: =====================
2020-04-03T08:49:30.3413600Z MSBUILD : error MSB4166: 4/3/2020 8:49:16 AM
2020-04-03T08:49:30.3414179Z MSBUILD : error MSB4166: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
2020-04-03T08:49:30.3415018Z MSBUILD : error MSB4166:    at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
2020-04-03T08:49:30.3415962Z MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.BinaryTranslator.BinaryWriteTranslator.TranslateDictionary[D,T](D& dictionary, NodePacketValueFactory`1 valueFactory)
2020-04-03T08:49:30.3416860Z MSBUILD : error MSB4166:    at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.Microsoft.Build.BackEnd.ITranslatable.Translate(ITranslator translator)
2020-04-03T08:49:30.3417711Z MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.BinaryTranslator.BinaryWriteTranslator.Translate[T](List`1& list, NodePacketValueFactory`1 factory)
2020-04-03T08:49:30.3418586Z MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.LogMessagePacket.TranslateTargetFinishedEvent(ITranslator translator, TargetFinishedEventArgs finishedEvent)
2020-04-03T08:49:30.3419376Z MSBUILD : error MSB4166:    at Microsoft.Build.Shared.LogMessagePacketBase.WriteToStream(ITranslator translator)
2020-04-03T08:49:30.3420292Z MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
2020-04-03T08:49:30.3421155Z MSBUILD : error MSB4166: ===================
2020-04-03T08:49:30.3421610Z MSBUILD : error MSB4166: 
2020-04-03T08:49:30.3422021Z MSBUILD : error MSB4166: 
```

### Environment data
`msbuild /version` output:

OS info:
Linux ARM64.

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):
Invoked by dotnet CLI, not sure what version is in arcade right now.

**Comment by rynowak** [comment] 2020-04-03 17:50
Special callout that this was ARM64. 

The log file referred to in the error message doesn't have much more info in it:

```txt
UNHANDLED EXCEPTIONS FROM PROCESS 4813:
=====================
4/3/2020 8:49:16 AM
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at Microsoft.Build.BackEnd.BinaryTranslator.BinaryWriteTranslator.TranslateDictionary[D,T](D& dictionary, NodePacketValueFactory`1 valueFactory)
   at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.Microsoft.Build.BackEnd.ITranslatable.Translate(ITranslator translator)
   at Microsoft.Build.BackEnd.BinaryTranslator.BinaryWriteTranslator.Translate[T](List`1& list, NodePacketValueFactory`1 factory)
   at Microsoft.Build.BackEnd.LogMessagePacket.TranslateTargetFinishedEvent(ITranslator translator, TargetFinishedEventArgs finishedEvent)
   at Microsoft.Build.Shared.LogMessagePacketBase.WriteToStream(ITranslator translator)
   at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
===================

```

**Comment by ladipro** [comment] 2020-04-20 13:32
ARM64 -> smells like a memory consistency issue. May have the same or similar root cause as #5296

**Comment by danmosemsft** [comment] 2020-08-10 20:59
@rainersigwald  this is not ARM specific so I think it shouldn't have that label. Is this another one to be fixed by changing to the immutable dictionary?

**Comment by benaadams** [comment] 2020-08-10 21:52
Happened on x64 also https://github.com/dotnet/runtime/issues/40626

**Comment by danmosemsft** [comment] 2020-08-10 22:18
Change I was referring to was https://github.com/dotnet/msbuild/pull/5279 and I assume there's a CopyOnWriteDictionary here ...

**Comment by rainersigwald** [comment] 2020-10-02 17:21
Optimistically closing this hoping that the `ImmutableDictionary` change in #5279 fixes it. If you see this on 16.8+, please comment and we can reopen.

**Closed by rainersigwald** 2020-10-02 17:21 UTC
Labels: Partner request, bug
