### ISSUE TITLE
Choose language of output messages

### ISSUE THREAD

**Issue by benvillalobos** [dotnet/msbuild#6115] opened 2021-02-03 17:16 UTC
Original issue: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1251531

Could you please add some option to MSBuild to allow us to choose the localization of the output error message ? (ex : environment variable, cli switch, etc)

 
English messages are more easily searchable on the internet and generally have better meaning (French translation is incomprehensible).

 
For now, choosing localization implies messing up Visual Studio installation files, or cryptic and often unsuccessful change of console code page. (ex https://stackoverflow.com/questions/2286216/how-to-change-msbuild-error-message-language).

 
cl.exe localization works differently (sigh) ; thus we can have mixed English/French messages during a build...

 
In visual studio, compiler tools locale should be uncorrelated with GUI locale (there is currently only one setting for language in Tools > Options > Environment > International Settings).

 
Please note that localized messages or not only incomprehensible, they do not integrate well with external tools like Qt and CMake and lead to encoding errors (https://bugreports.qt.io/browse/QTCREATORBUG-316).

**Comment by Nirmal4G** [comment] 2021-02-16 10:33
One way this could be done is by adding a parameter to logger parameters. That way you can choose console messages in one language, binlog messages in another language and so on. But we have to make MSBuild lookup localizations every single time and that might be performance and allocation intensive.

**Comment by kkivi** [comment] 2021-07-24 12:10
This bug make development impossible.

**Comment by danmoseley** [comment] 2021-07-24 15:00
Is the problem that there isn't an error code to search for? Or that the message content varies for a specific code?

**Comment by aheusel** [comment] 2022-02-11 08:48
We decided to choose java over c# because of this matter. It renders the  platform unusable.

**Comment by dominoFire** [comment] 2022-11-05 04:14
I think this issue is related https://github.com/dotnet/msbuild/issues/1596

**Comment by f-alizada** [comment] 2023-12-20 08:34
Hello. 
Yes, @dominoFire thank you it is a duplicate of https://github.com/dotnet/msbuild/issues/1596 which is closed and 
MSBuild currently detects DOTNET_CLI_UI_LANGUAGE env var, hence closing the issue. 
@benvillalobos please feel free to [file a issue](https://github.com/dotnet/msbuild/issues/new/choose) or reopen this one if behavior is different for you.

**Closed by f-alizada** 2023-12-20 08:34 UTC
Labels: help wanted

**Comment by Nirmal4G** [comment] 2023-12-22 06:22
@f-alizada It is related to #1596 but that is a bugfix and this is a feature request. This says that even in single build, when there is multiple logging involved, then each log should have it's own language. Totally different from the mentioned issue.
