### ISSUE TITLE
Update vs to Version 17.4.0 Preview 2.0 from PREVIEW 1 cause errors in publish worker service 

### ISSUE THREAD

**Issue by danies8** [dotnet/msbuild#8023] opened 2022-10-05 07:56 UTC
I reported on this bug:
https://github.com/dotnet/msbuild/issues?q=is%3Aissue+author%3A%40me+is%3Aclosed
but still not get solution what to do ?
Please provide solution to solve the issue?
Thanks in advance.

**Comment by rainersigwald** [comment] 2022-10-06 16:32
Duplicate of #7995

**Closed by rainersigwald** 2022-10-06 16:32 UTC
Labels: bug, needs-triage

**Comment by danies8** [comment] 2022-10-06 16:39
In which version it will be fix ?
