### ISSUE TITLE
[Bug]: OverflowException in BinaryLogger

### ISSUE THREAD

**Issue by jeffkl** [dotnet/msbuild#9308] opened 2023-10-06 02:09 UTC
### Issue Description

I was using the binary logger on a very large set of projects and saw this error:

```
MSBUILD : error MSB4015: The build stopped unexpectedly because the "ReusableLogger" logger failed unexpectedly during shutdown.
System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.IO.BufferedStream.Write(Byte[] array, Int32 offset, Int32 count)
   at Microsoft.Build.Logging.BuildEventArgsWriter.WriteBlob(BinaryLogRecordKind kind, Byte[] bytes)
   at Microsoft.Build.Logging.BinaryLogger.Shutdown()
   at Microsoft.Build.BackEnd.Logging.LoggingService.ShutdownLogger(ILogger logger)
```

This caused the build to fail.

### Steps to Reproduce

I'd imagine its hard to reproduce this but I'm sure we can create a unit test that would create the circumstances that leads to the exception.

### Expected Behavior

A failure in the binary logger should not cause the build to fail.

### Actual Behavior

MSBuild can either use a large type for numbers or guard against unexpected failures in the binary logger and log a warning instead of failing the build.

### Versions & Configurations

```
MSBuild version 17.6.3+07e294721 for .NET Framework
17.6.3.22601
```

**Comment by JanKrivanek** [comment] 2023-10-10 13:59
@jeffkl - just curious - this seem to be caused by attempt to attach files that are after zipping over 2GB - is that an intended and wanted scenario in your case?

We'll still investigate and make sure it's either fixed or better error is provided. But I was wondering if you might get there due to some other error (e.g. accidently including binary files)

**Comment by JanKrivanek** [comment] 2023-10-10 14:13
Oh righ @KalleOlaviNiemitalo
Though there is still limitation for 2GB of the total size of the embedded zipped stream

**Comment by JanKrivanek** [comment] 2023-10-10 15:20
@jeffkl - can you update to 17.7?

**Comment by JanKrivanek** [comment] 2023-11-01 13:18
Fixed in the latest version

**Closed by JanKrivanek** 2023-11-01 13:18 UTC
Labels: bug
