### ISSUE TITLE
[NETSDKE2E][Loc] Unit of time in build text is missing when creating project in CLI. 

### ISSUE THREAD

**Issue by vdanche** [dotnet/msbuild#9971] opened 2024-04-03 06:11 UTC
1.install 8.0.300-preview.0.24202.22 sdk on Loc OS. e.g German/Chinese
2.dotnet new console in CLI and then dotnet build
3.Check the text message during dotnet build.

Expected Result:
The text message display well.

Actual Result:
Unit of time in build text is missing when creating project in CLI. 

German:
![image](https://github.com/dotnet/sdk/assets/65637796/0dbef927-8ce1-4125-9bf2-cb0fbc7af136)
Chinese:
![image](https://github.com/dotnet/sdk/assets/65637796/f16943aa-1f8b-456d-93dd-0089534f9a20)

En(not repro)
![image](https://github.com/dotnet/sdk/assets/65637796/547854c5-ec01-4fe1-8884-9b37146904e4)

dotnet --info
.NET SDK:
 Version:           8.0.300-preview.0.24202.22
 Commit:            0fbd1cb569
 Workload version:  8.0.300-manifests.3097af8b
 MSBuild version:   17.10.0+4f6b1bb28

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.300-preview.0.24202.22\

已安装 .NET 工作负载:
没有要显示的已安装工作负载。

Host:
  Version:      8.0.2
  Architecture: x64
  Commit:       1381d5ebd2

.NET SDKs installed:
  8.0.300-preview.0.24202.22 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by marcpopMSFT** [comment] 2024-04-03 17:09
That string comes from the msbuild resources.

**Comment by baronfel** [comment] 2024-04-03 17:14
This is a dupe of one we're already tracking - let me see if I can find it.

**Comment by AR-May** [comment] 2024-04-04 15:00
Team triage: this seems to be related, but not quite a duplicate. @JaynieBai could you log the loc bug?

**Comment by JaynieBai** [comment] 2024-04-08 06:53
This should be singular and plural translation issue. Chinese translation is correct in my opinion. But German ErrorCount seems lack of the plural word. Have file a loc bug https://ceapex.visualstudio.com/CEINTL/_workitems/edit/961919

**Comment by AR-May** [comment] 2024-06-26 12:01
Closing as it is a duplicate to the main loc issue.

**Closed by AR-May** 2024-06-26 12:01 UTC
Labels: needs-investigation, triaged
