### ISSUE TITLE
Embedded Resource name changes unexpectedly if file-scoped namespaces are used

### ISSUE THREAD

**Issue by martincostello** [dotnet/msbuild#6853] opened 2021-09-15 16:02 UTC
### Issue Description

If a class has the same name and namespace as a `.resx` file and it it used to key into the resources of the assembly via `IStringLocalizer`, when the class is changed to use a C# file-scoped namespace instead of a "normal" C# namespace, the name of the resource in the assembly changes (the namespace prefix is lost), causing resource lookups in the existing code to fail.

_Apologies if this is the wrong repo, I wasn't sure if this was an issue with MSBuild or Roslyn, and it didn't seem to be an issue with the localisation infrastructure in the runtime repo._

### Steps to Reproduce

Clone the following repository, and then run `dotnet run`: https://github.com/martincostello/FileScopedNamespacesResourcesRepro

This repro project is adapted from an internal line-of-business application that I migrated to use file-scoped namespaces, after which our localisation tests started to fail.

### Expected Behavior

The resource string for each culture is printed to the console.

### Actual Behavior

The _name_ of the resource string is printed to the console for each culture.

### Analysis

It appears that the use of file-scoped namespaces _somehow_ influences how the manifest resource name is computed. This then causes the code's expectation of where the resource is to not match the compiled assembly, causing the resource lookup to fail.

#### "Normal" namespace

![resources-with-normal-namespace](https://user-images.githubusercontent.com/1439341/133467534-8b4efb7c-67d1-44d6-8e2a-900a0886c704.png)

#### File-scoped namespace

![resources-with-file-scoped-namespace](https://user-images.githubusercontent.com/1439341/133467684-525db43f-01c5-45d8-95d0-00c8746a1ea6.png)

### Versions & Configurations

.NET SDK `6.0.100-rc.1.21458.32`

**Comment by rainersigwald** [comment] 2021-09-15 20:52
Duplicate of #6828

**Comment by rainersigwald** [comment] 2021-09-15 20:52
Thanks for filing!

**Closed by rainersigwald** 2021-09-15 20:52 UTC
Labels: bug, needs-triage
