### ISSUE TITLE
Exec tasks warns: bash : warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

### ISSUE THREAD

**Issue by safern** [dotnet/msbuild#4194] opened 2019-02-21 19:32 UTC
### Steps to reproduce

Create an MSBuild project, that calls the `Exec` task to any bash script and run it in an environment where LC_ALL is not configured i.e a fresh ubuntu:16.04 docker container.

```
docker run -ti --rm ubuntu:16.04
apt-get update
apt-get install libicu-dev
```

dotnet SDK will need to be installed.

Project file
```xml
<Project>
  <Target Name="RunExec">
    <Exec Command="./helloworld.sh" />
  </Target>
</Project>
```

helloworld.sh contents:
```bash
#!/usr/bin/env bash
echo 'Hello World'
```

Directory contents:
```
/
- project.csproj
- helloworld.sh
```

Command line
```
dotnet msbuild /t:RunExec
```
### Expected  behavior
```
Hello World
```

### Actual behavior
```
bash : warning : setlocale: LC_ALL: cannot change locale (en_US.UTF-8) [/home/project.csproj]
  Hello World
```

### Environment data
`msbuild /version` output: 15.9.20.62856
`dotnet SDK version`: 2.2.103

OS info: `Ubuntu 16.04 docker container.`

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc): `dotnet CLI`

I noticed that LC_ALL is set when calling the `Exec` task in Unix:
https://github.com/Microsoft/msbuild/blob/f136edbfecec171d73cb4c7fe1c936f6b2bf60a5/src/Tasks/Exec.cs#L597

cc: @ericstj @cdmihai @rainersigwald

**Comment by jaredpar** [comment] 2020-04-01 16:36
Confirmed that this can be fixed by doing the following:

```
> apt install locales locales-all
```

**Comment by rainersigwald** [comment] 2020-04-03 12:06
I think we could potentially have avoided this by specifying `C.UTF-8` instead of `en_US.UTF-8`, because [`man 3 setlocale`](http://man7.org/linux/man-pages/man3/setlocale.3.html) says

> The locale "C" or "POSIX" is a portable locale; it exists on all conforming systems.

I don't have enough understanding to figure what that would change or break, though. Any UNIX loc experts who can say it's a good or bad idea floating by?

**Comment by safern** [comment] 2020-04-03 17:39
@wfurt might have an idea.

**Comment by safern** [comment] 2020-04-03 17:40
Also @janvorli

**Comment by wfurt** [comment] 2020-04-03 18:03
The answer may depend on what version of .NET core you use. 2.x will refuse to do case insensitive string companions even if explicitly asked. For 3+, this should just work. Rest of the OS should really not care. The locale and lang primarily impacts error message and date/time formats.  

Long run, I thing 'C' would be preferable as language and country agnostic and available also on Alpine.

**Comment by jaredpar** [comment] 2020-04-03 18:57
I understand this is potentially a breaking change but given we're in the .NET 5 release this would be the right time to issue one. Essentially do breaks on major releases vs. point ones. 

I also don't understand what the real impact of such a change would be though hence it's easy for me to say "just change it" :smile:

**Comment by janvorli** [comment] 2020-04-03 19:48
Any idea why msbuild forces the locale? It seems weird, I would expect it to just keep the existing locale set by the system.

**Comment by rainersigwald** [comment] 2020-04-07 12:29
Setting the locale was required on Windows, in order to support non-system-codepage-representable paths. I suspect we carried that over even though it may not be strictly necessary?

@cdmihai any chance you remember details on the context of 3042e7cc9e86a51e64cf7bcb5f14c4a7ed2629c5 from 5 years ago? It was a fix for #251, but my read of that is it was more about the encoding for writing the file. That _should_ match the runtime environment, but on non-Windows OSes, generally "not specified" and "UTF-8" are the same (right?).

**Comment by dashesy** [comment] 2022-03-24 23:19
I recently got an error from a docker trying to build a package, because PackageVersion was detected like this

```text
PackageVersion=1.10.0-dev-20220324-1029-/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8);0d9030e7
```

which is invalid. So this is not just a warning.

**Comment by mthalman** [comment] 2022-11-15 15:45
Is this something that can be targeted to fix for .NET 8? This is problematic in the .NET container images because they are locale-neutral. So in that environment, this scenario produces a warning or even an error if warnings are treated as errors.

**Comment by tmds** [comment] 2023-11-02 21:17
> I think we could potentially have avoided this by specifying C.UTF-8 instead of en_US.UTF-8, because [man 3 setlocale](http://man7.org/linux/man-pages/man3/setlocale.3.html) says

This is a good option. It will get rid of the warnings and still set the encoding to UTF-8.

**Comment by tmds** [comment] 2023-11-03 07:42
> IIRC, POSIX requires support for "C" but not for "C.UTF-8".
But maybe "C.UTF-8" is regardless supported in those operating systems that MSBuild targets.

I think we can assume UTF-8 is available.

> Setting the locale was required on Windows, in order to support non-system-codepage-representable paths. I suspect we carried that over even though it may not be strictly necessary?

Also, I assume the answer to this is: yes.

But since it was set previously, it seems best to continue setting this to an "english" locale to avoid breaking anyone that parses the output of the tool.

The options are: set it to `C.UTF-8`/`C`/``/not override it. I think all are worth considering. I went for the first as I think it's the smallest change that fixes this issue and I don't expect it to cause new issues. I'm fine with any of the other options if someone has a stronger preference for it.

**Comment by tmds** [comment] 2023-11-03 10:02
> The UTF-8 encoding being available does not mean that a "C.UTF-8" locale is available.

Right.

I expect it to be uncommon for a system to support `C` but not allow `C.UTF-8`.

Do you think we should use `C` instead of `C.UTF-8`?

**Comment by tmds** [comment] 2023-11-03 12:55
Those should work file as they accepted `en_US.UTF-8`, they should accept `C.UTF-8` too.

**Comment by tmds** [comment] 2023-11-03 14:35
ok, based on that, we better use `C` or not set it.
I'll update the PR to use `C` without the UTF-8 encoding.

**Comment by tmds** [comment] 2023-11-03 14:51
@KalleOlaviNiemitalo does macOS print an error like bash does when setting an unsupported locale?
```
$ /bin/sh -c 'export LC_ALL=foo'
/bin/sh: line 1: warning: setlocale: LC_ALL: cannot change locale (foo): No such file or directory
/bin/sh: line 1: warning: setlocale: LC_ALL: cannot change locale (foo): No such file or directory
```

**Comment by tmds** [comment] 2023-11-03 15:34
> If possible, it would be best to leave LANG and LC_ALL unchanged, so that if the tool outputs any messages, then they can be in the developer's preferred language.

This is also an option. It will cause messages to change from English to the system locale. If someone is parsing the output, it may cause the parsing to break.

I used the `C` locale to avoid that, but I think this is an acceptable option.

>  then perhaps MSBuild could first check whether the environment variables already specify UTF-8 according to the C runtime library, and change them only if they don't.

From our discussion, we don't have a good way to pick a locale that implies UTF-8.
I don't think we should try to enforce UTF-8.

We have these options left: either use `C` (to keep English), or leave it unchanged (to use the system locale).

https://github.com/dotnet/msbuild/pull/9391 is currently doing the first, but I can change it to the latter if that is the preferred option.

**Comment by tmds** [comment] 2023-11-03 15:41
I was referring to the _and change them only if they don't._ part.

**Comment by tmds** [comment] 2023-11-03 15:46
Yes, they will need to set it if they depend on it. While with the current behavior it was always enforced.
So to the users that depend on it, this is a breaking change.

**Comment by tmds** [comment] 2023-11-03 16:16
As I said, I find it an acceptable option to not set these envvars. I just want to point out will cause the output to change based on the system locale.

On Windows, I believe the output is always using the system locale? So probably, this wont cause much breaking.

**Comment by wfurt** [comment] 2023-11-03 16:29
macOS seems to have `C` e.g. without utf8.  The problem with `C` is that older versions for .NET could not do case insensitive comparisons (AFAIK). And that broke many things. 

https://github.com/dotnet/runtime/issues/27376

**Comment by tmds** [comment] 2023-11-03 16:45
>  The problem with C is that older versions for .NET could not do case insensitive comparisons (AFAIK). And that broke many things.

Was this problem WSL specific, or addressed in a later version of .NET?

I can't reproduce this with .NET 6, .NET 7, or .NET 8 on Fedora.

**Comment by wfurt** [comment] 2023-11-03 16:48
I don't think it was WSL specific. @tarekgh is probably best person to comment on this.

**Comment by tarekgh** [comment] 2023-11-03 17:08
When using `C` locale, .NET will ignore it and use Invariant culture at that time. This is a change we made long ago. The reason for the change as indicated before is that `C` locale is unusable and doesn't support casing and has limited collation capabilities.

**Comment by tmds** [comment] 2023-11-04 07:47
I've pushed it to https://github.com/dotnet/msbuild/pull/9391. Let's see what CI makes of it.

**Comment by tmds** [comment] 2023-11-09 12:32
> Our main is currently flowing into 8.0.200 builds as well as 9.0.100 builds so I think we should be cautious and revert for now. Sorry for the confusion!

No problem.

The PR that got merged and reverted was:

```diff
diff --git a/src/Tasks/Exec.cs b/src/Tasks/Exec.cs
index df817422bfd..95f43a488bb 100644
--- a/src/Tasks/Exec.cs
+++ b/src/Tasks/Exec.cs
@@ -590,7 +590,7 @@ protected internal override void AddCommandLineCommands(CommandLineBuilderExtens
             {
                 commandLine.AppendSwitch("-c");
                 commandLine.AppendTextUnquoted(" \"");
-                commandLine.AppendTextUnquoted("export LANG=en_US.UTF-8; export LC_ALL=en_US.UTF-8; . ");
+                commandLine.AppendTextUnquoted(". ");
                 commandLine.AppendFileNameIfNotNull(batchFileForCommandLine);
                 commandLine.AppendTextUnquoted("\"");
             }
```

This is a good option because:

- We're no longer setting something that may be unsupported (fixes this issue).
- .NET assumes Unix platforms to have UTF-8 as the default encoding, so we can do the same rather than try to enforce it.
- We're now using the system locale on Unix for the tool process. This is the same as how it behaves on Windows.
- While most tools should work fine under any locale, a user may set the envvars to control the locale in the unlikely event there is a tool that doesn't.

We can create a new PR for this when the `main` branch becomes 9.0 only.

@rainersigwald @mthalman would you consider backporting this (could be 8.0.2xx+) to address the issues this causes in container images? We have some customers running into this problem (with Red Hat images).

**Comment by rainersigwald** [comment] 2023-11-09 15:55
I think I agree that that's a good option, and I'm willing to take it for 8.0.200 personally, though to be extra cautious I might want to put it under a changewave (so it can be easily disabled if it does cause problems for someone). The revert IMO is about making sure we have the right conversation and an explicit decision.

**Comment by mthalman** [comment] 2023-11-09 16:36
Note that our container images are always based on the latest feature band. So once we have 8.0.200 GA, that's what will be used in the SDK container image. There would be no supported images with 8.0.1xx at that point.

So yes, having an escape hatch to get back to the previous behavior would be a good thing.

**Comment by omajid** [comment] 2023-11-14 15:23
> I might want to put it under a changewave (so it can be easily disabled if it does cause problems for someone)

Could you help me understand what a changewave is? Asking me to RTFM (with a link to the fine manual) would be great :)

**Comment by tmds** [comment] 2023-11-16 10:01
> I'm willing to take it for 8.0.200 personally, though to be extra cautious I might want to put it under a changewave

I intend to work on this next week.

**Comment by tmds** [comment] 2023-11-23 09:31
> I recall reading that source-build is always based on the earliest feature band; but apparently that is no longer true for .NET 8.0, which uses the https://github.com/dotnet/dotnet repository. So operating system packagers would also get 8.0.200 eventually.

Yes, the design doc is here: https://github.com/dotnet/source-build/blob/main/Documentation/planning/multi-sdk-band-support.md.

Maintainers can choose to only build the 1xx band. That's our current plan for RHEL/Fedora.
We'll be backporting this fix (in some form) in our 1xx packages.

**Comment by mthalman** [comment] 2023-11-27 14:35
Supporting multiple SDK bands is the goal for .NET 9. But that won't apply to .NET 8 which will still only support 8.0.1xx for source build.

**Closed** 2023-12-11 15:46 UTC
