### ISSUE TITLE
Control CopyLocal of transitive dependencies with single Metadata

### ISSUE THREAD

**Issue by felix-ri** [dotnet/msbuild#7865] opened 2022-08-08 11:22 UTC
### Goal
- The goal is to use a single ItemMetadata on the ProjectReference to control, whether the referenced Project and all its dependencies are copied to the output or not (this includes Nugets as well as other Projects).

### Usecase
- an Application with Plugins, where the Plugins should compile against some API Projects
- in a single Solution
- the API Projects themselves have references to other Projects/Nugets (also transitively)
- the Plugins should not Copy any API Projects/Nugets into their build directory. (as they are already present in the Application)

### Steps to Reproduce
- I uploaded my [sample project](https://github.com/felix-ri/Msbuild-Bug-3)
- the reference chain is: PluginA => LibA =>LibB
- both libs also have Nugets
- I tried to achieve my goal by adding `<Private>false</Private>` and `<ExcludeAssets>runtime</ExcludeAssets>` to the ProjectReference
- to simplify this, I added the `<KopiLokal>true</KopiLokal>` MetaData Attribute to the ProjectReference 
- and set the Private and ExcludeAssets in a Target, that executes as InitialTargets
- Initially, I tried to use ItemDefinitionGroup to set the defaults for Private and ExcludeAssets to false and runtime and override them in the Task
- but then, when building with VS, it couldn't find the dlls of the nugets (it searched in the outputs of the Libs and not in the nuget packages directory)

### Expected Behavior
- when KopiLokal true, all Nugets and Libs are in the output
- when KopiLokal false, none of the Nugets and Libs are in the output
- I used KopiLokal, because I don't know if there is already a Metadata CopyLocal
- Also I expect the build to produce the same output, when built from Visual Studio and from `dotnet build` CLI

### Actual Behavior
- when building with CLI, LibB is still in the output directory
- when building with VS
  - LibB is still in the output directory 
  - all nugets are also copied to the output directory

### Build Environment
- Microsoft Visual Studio Professional 2022 (2) (64-bit) - Current Version 17.2.5
- Microsoft (R) Build Engine version 17.2.0+41abc5629 for .NET
- The dotnet sdk version is 6.0.302

### Questions
- What is the intended way to control the copylocal behaviour of References (Project and Package) (direct and transitive)?

**Comment by Forgind** [comment] 2022-08-10 21:08
You should be able to set CopyToOutputDirectory to Never, but I found an open issue that that doesn't work:
#4795

Closing this as a duplicate, but feel free to ping on the other issue. (I added needs-triage to it just now, so we'll hopefully pick it up in the next triage meeting.) Thanks for the report!

**Closed by Forgind** 2022-08-10 21:08 UTC
Labels: needs-triage

**Comment by felix-ri** [comment] 2022-08-11 06:50
- CopyToOutputDirectory didn't help. 
- I also don't think CopyToOutputDirectory works on ProjectReferences.
- My problem isn't, that I can't prevent the direct ProjectReference from being in the Output dir.
- My problem is, that I can't prevent the indirect Project and PackageReferences from being in the Output dir. (with Metadata on the first reference)

**Comment by rainersigwald** [comment] 2022-08-11 13:58
Duplicate of #4371

**Comment by rainersigwald** [comment] 2022-08-11 13:59
@felix-ri please see #4371 for details about that scenario.

**Comment by rainersigwald** [comment] 2022-08-11 20:26
@felix-ri can you try `ExcludeAssets="runtime"`?

**Comment by felix-ri** [comment] 2022-08-12 08:21
This has the same effect as `<IncludeAssets>compile</IncludeAssets>`: LibB is still in the output.

**Comment by felix-ri** [comment] 2022-08-16 09:18
however putting the `ExcludeAssets="runtime"` in a ItemDefinitionGroup works:
```
<ItemDefinitionGroup>
	<ProjectReference>
		<Private>false</Private>
		<ExcludeAssets>runtime</ExcludeAssets>
	</ProjectReference>
</ItemDefinitionGroup>
```
Should it matter, if it's declared on the ItemGroup (specific ProjectReference) or on an ItemDefinitionGroup (generally for all ProjectReferences)?
