### ISSUE TITLE
Update vs to Version 17.4.0 Preview 2.0 from PREVIEW 1 cause errors in publish worker service

### ISSUE THREAD

**Issue by danies8** [dotnet/msbuild#8041] opened 2022-10-11 06:36 UTC
I reported on this bug:
https://github.com/dotnet/msbuild/issues?q=is%3Aissue+author%3A%40me+is%3Aclosed
@rainersigwald & @Forgind Can I go one version back, to vs version 17.4 preview 1
After I build it in vs 17.4 preview 2 ?
Thanks in advance.

**Comment by rainersigwald** [comment] 2022-10-11 13:48
Please stop filing duplicate issues when you feel you haven't gotten a response quickly enough.

**Comment by rainersigwald** [comment] 2022-10-11 13:49
Duplicate of #7995

**Closed by rainersigwald** 2022-10-11 13:49 UTC
Labels: bug, needs-triage
