### ISSUE TITLE
Office VSTO project fails to find runtime assembly references using msbuild with Build Tools for Visual Studio 2022 17.2

### ISSUE THREAD

**Issue by acohenOT** [dotnet/msbuild#7617] opened 2022-05-11 18:29 UTC
### Issue Description

After updating Build Tools for Visual Studio 2022 from 17.1.x to 17.2, Office VSTO project fails to build without manually specifying the ReferenceAssemblies\v4.0 directory.

### Steps to Reproduce

1. Create an Office VSTO project.
2. On a Windows environment that has Build Tools for Visual Studio 2022 installed with the "Office/SharePoint development" workload, build the project on the command line `msbuild MyProject.csproj`

### Expected Behavior

Build successful

### Actual Behavior

```
error CS0234: The type or namespace name 'RibbonCollectionBase' does not exist in the namespace 'Microsoft.Office.Tools.Ribbon' (are you missing an assembly reference?) 
error CS0234: The type or namespace name 'FormRegionCollectionBase' does not exist in the namespace 'Microsoft.Office.Tools.Outlook' (are you missing an assembly reference?) 
error CS0234: The type or namespace name 'OutlookAddInBase' does not exist in the namespace 'Microsoft.Office.Tools.Outlook' (are you missing an assembly reference?) 
error CS0234: The type or namespace name 'FormRegionCollectionBase' does not exist in the namespace 'Microsoft.Office.Tools.Outlook' (are you missing an assembly reference?) 
```

### Analysis

The same command works in the same environment with Build Tools for Visual Studio 2022 17.1.x (latest version).

In 17.2, the workaround appears to be to specify the reference path.

`msbuild MyProject.csproj -p:ReferencePath:"C:\Program Files\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\ReferenceAssemblies\v4.0"`

### Versions & Configurations

Microsoft (R) Build Engine version 17.2.1+52cd2da31 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

17.2.1.25201

Windows Server 2016 Standard x64 version 1607
OS Build 14393.5125

The issue does not occur when using when using msbuild with the full Visual Studio 2022 Enterprise IDE on Windows 11.

**Comment by maxschaf** [comment] 2022-05-19 11:28
we face the same issue

**Comment by BenVillalobos** [comment] 2022-05-26 17:04
Can someone provide a repro project?

Friendly ping @v-codyguan can you repro once that's provided?

**Comment by TomcatBB** [comment] 2022-06-08 12:04
We are also running into this issue. Hope MS will fix this soon.

**Comment by BenVillalobos** [comment] 2022-07-14 16:47
Team Triage: We suspect this is a build tools authoring error. Closing this as a duplicate of https://developercommunity.visualstudio.com/t/Build-Tools-2022:-warning-MSB3245:-Could/10093000

**Closed** 2022-07-28 16:47 UTC
Labels: bug, needs-triage, needs-investigation
