### ISSUE TITLE
Cannot build using project as the target

### ISSUE THREAD

**Issue by pepone** [dotnet/msbuild#6499] opened 2021-05-28 09:18 UTC
### Issue Description

After updating Visual Studio to version 16.10.0 can no longer build a solution targets using /t:<target-name>

### Steps to Reproduce

Create a solution with 2 C++ console projects `foo` and `bar` and save it, go to the console and try to build each project with `msbuild foo.sln /t:foo` and `msbuild foo.sln /f:bar`

### Expected Behavior

You should be able to build the projects with `/t:<project-name>`

### Actual Behavior

The build fails with an error

```
msbuild foo.sln /t:bar
Microsoft (R) Build Engine version 16.10.0+4242f381a for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
Build started 5/28/2021 11:10:53 AM.
Project "C:\Users\ppgut\source\repos\foo\foo.sln" on node 1 (bar target(s)).
ValidateSolutionConfiguration:
  Building solution configuration "Debug|x64".
Project "C:\Users\ppgut\source\repos\foo\foo.sln" (1) is building "C:\Users\ppgut\source\repos\foo\foo\foo.vcxproj" (2) on node 1 (bar target(s)).
C:\Users\ppgut\source\repos\foo\foo\foo.vcxproj : error MSB4057: The target "bar" does not exist in the project.
Done Building Project "C:\Users\ppgut\source\repos\foo\foo\foo.vcxproj" (bar target(s)) -- FAILED.

Project "C:\Users\ppgut\source\repos\foo\foo.sln" (1) is building "C:\Users\ppgut\source\repos\foo\bar\bar.vcxproj" (3) on node 1 (bar target(s)).
C:\Users\ppgut\source\repos\foo\bar\bar.vcxproj : error MSB4057: The target "bar" does not exist in the project.
Done Building Project "C:\Users\ppgut\source\repos\foo\bar\bar.vcxproj" (bar target(s)) -- FAILED.

Done Building Project "C:\Users\ppgut\source\repos\foo\foo.sln" (bar target(s)) -- FAILED.


Build FAILED.
```

The attached file contains a solution with two projects that can be used to reproduce the issue.

[foo.zip](https://github.com/dotnet/msbuild/files/6559769/foo.zip)

**Comment by larde** [comment] 2021-05-28 13:49
FYI a workaround was found here: https://stackoverflow.com/questions/67729222/msbuild-error-msb4057-after-updating-to-vs-2019-16-10-0

**Comment by rainersigwald** [comment] 2021-05-28 17:02
Duplicate of #6373

**Comment by rainersigwald** [comment] 2021-05-28 17:02
(The fix will be in Visual Studio 16.10.1, available ASAP.)

**Closed by rainersigwald** 2021-05-28 17:02 UTC
Labels: bug, untriaged

**Comment by rhuijben** [comment] 2021-05-29 08:26
Having the same issue. Reinstalled my PC in an attempt to resolve it. Finally confirmation that this will be resolved soon

Severe issue that passed release QA

**Comment by guitarjorge24** [comment] 2021-06-07 06:41
I've tried 6 or 7 times to download older versions of Visual Studio like 16.9.6 and 16.9.5 but have not been able to download them successfully. I keep getting this error:
![image](https://user-images.githubusercontent.com/12472021/120970794-e260f380-c739-11eb-83fb-9dbdb9072143.png)

Anyone has seen this or know how to fix this?
