### ISSUE TITLE
AspireHost doesn't seem to respect some MSBuild properties?

### ISSUE THREAD

**Issue by En3Tho** [dotnet/msbuild#10344] opened 2024-06-25 13:22 UTC
Recently I've been migrating my personal projects to use artifacts output with my custom provided path:

Here is what I've added to my `Directory.Build.props`:
```msbuild
<PropertyGroup>
        <UseArtifactsOutput>true</UseArtifactsOutput>
        <ARTIFACTS_PATH_DOTNET Condition=" '$(ARTIFACTS_PATH_DOTNET)' == '' ">$(MSBuildThisFileDirectory)artifacts</ARTIFACTS_PATH_DOTNET>
        <ARTIFACTS_PATH_DOTNET Condition=" '$(ARTIFACTS_PATH_DOTNET)' != '' ">$(ARTIFACTS_PATH_DOTNET)\$(SolutionName)</ARTIFACTS_PATH_DOTNET>
        <ArtifactsPath>$(ARTIFACTS_PATH_DOTNET)</ArtifactsPath>
    </PropertyGroup>
```

When build is done artifacts are published to folder I've chosen in `ARTIFACTS_PATH_DOTNET` env variable for example:
`ARTIFACTS_PATH_DOTNET\MySolution\bin\MyApp\debug` - this is expected

But when I start app host it seems to miss `SolutionName` and start process like this and fails:
`'ARTIFACTS_PATH_DOTNET\bin\MyApp\debug\MyApp.exe'`

What can I do to fix this? I can obviosuly replace `$(SolutionName)` with a concrete one but it is not ideal I guess.

**Comment by baronfel** [comment] 2024-07-08 23:59
SolutionName will only exist if the solution is being built - we do not recommend that any project specific logic try to take it into account as a result. I expect that since Aspire's default mode of operation is watch/run on the AppHost it will never work as expected.

**Comment by En3Tho** [comment] 2024-07-09 06:49
The issue here is that running apphost using ide works as expected out of the box but apphost itself can't find related projects because it doesn't seem to be getting the right variable due to how it works/builds.

Workaround for this is simple but it just wasn't an expected behavior.

If this can't really be fixed then I guess this can be closed.

**Comment by AR-May** [comment] 2024-07-09 14:05
As @baronfel pointed out, this behavior is by design. I am closing this issue, however, please do not hesitate to reopen if further discussion is needed.

**Closed by AR-May** 2024-07-09 14:05 UTC
