### ISSUE TITLE
MSB3644 says .NETFramework version 5

### ISSUE THREAD

**Issue by timheuer** [dotnet/msbuild#5807] opened 2020-10-16 16:16 UTC
### Issue Description
When attempting to use `dotnet build` on a .NET 5 project when the SDK is not present it shows a weird error message with terminology that isn't branding correct:

```
error MSB3644: The reference assemblies for .NETFramework,Version=v5.0 were not found.
```
Observe `.NETFramework,Version=v5.0`

I would not expect this to say '.NETFramework'

**Comment by rainersigwald** [comment] 2020-10-22 20:49
We started working on this issue as #5826 before we saw this one, sorry.

**Comment by rainersigwald** [comment] 2020-10-22 20:49
Duplicate of #5826

**Closed by rainersigwald** 2020-10-22 20:49 UTC
Labels: bug, untriaged
