### ISSUE TITLE
AfterBuild Target doesen't work

### ISSUE THREAD

**Issue by Takoooooo** [dotnet/msbuild#5986] opened 2020-12-22 12:45 UTC
### Issue Description

I tried in different ways but anything doesn't seem to work inside `<Target Name="AfterBuild" >` block.
Originally I wanted to execute my shell script after the build. I tried in different ways, like that
`
<Target Name="AfterBuild" >  
    <Exec Command="sh copy_plugins.sh" />
</Target>
`
I tried saving my project, rebuilding but it doesn't work for me. After that, I decided to try in this way to test whether Target executes anything or not
`
 <Target Name="AfterBuild" >
    <Message Importance="high" Text="test"/>
  </Target>
`
`dotnet msbuild`  haven't printed anything 
![image](https://user-images.githubusercontent.com/53405089/102889096-ae7f6380-4462-11eb-8dba-642aa41319bb.png)
(you can repro this even on a simple console app),also, build output
![image](https://user-images.githubusercontent.com/53405089/102889223-eb4b5a80-4462-11eb-9a12-a7e5a79572ee.png)
I think expected behavior and actual are obvious.

### Steps to Reproduce
That's everything you need
`
 <Target Name="AfterBuild" >
    <Message Importance="high" Text="test"/>
  </Target>
`

### Versions & Configurations
msbuild -version? 16.8.2.56705
Visual Studio? 16.8.3,also tested on Visual Studio Mac,Rider,Rider on Mac
Tested on osx-x64,win-x64

**Comment by rainersigwald** [comment] 2020-12-22 20:06
Duplicate of #1680

**Closed by rainersigwald** 2020-12-22 20:06 UTC
Labels: bug, untriaged

**Comment by rainersigwald** [comment] 2020-12-22 20:09
@Takoooooo There's a detailed explanation in https://github.com/dotnet/msbuild/issues/1680 as well as suggested changes to your project to make this work. The Visual Studio UI for adding these events should generate correct changes to your project file, too (if you like using the UI).
