### ISSUE TITLE
Microsoft.NET.StringTools not properly loading into separate ALC

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#9572] opened 2023-12-22 12:38 UTC
### Context

This is based on the https://github.com/dotnet/msbuild/issues/9538
Microsoft.NET.StringTools is not being loaded into separate AssemblyLoadContext properly in the C# DevKit leading to regression issues in case of changes in functionality of StringTools.

### Details

The Microsoft.NET.StringTools.dll is located in the sdk folder along with the othe MSBuild assemblies that are trying to load it, however it fails to be loaded into nondefault ACL, fallbacking to the default ACL which already has StringTools loaded into separate ACL:

![image](https://github.com/dotnet/msbuild/assets/3809076/8c1e300c-248a-441b-8aaa-31f0bb02260a)

### Possible investigation steps

1) Load Microsoft.Build.dll into custom Assembly Load Context
2) Execute code that will lead to pulling other binaries - e.g. simple evaluation of a Project should do:

```csharp
var path = "some\csrpoj\path.csproj";
var toolsVersion = "Current";
var xml = Microsoft.Build.Construction.ProjectRootElement.Open(path);
var rootProj = new Microsoft.Build.Evaluation.Project(xml, Microsoft.Build.Evaluation.ProjectCollection.GlobalProjectCollection.GlobalProperties, toolsVersion);
```

3) Inspect the ACL being used for all involved MSBuild assemblies. If you decide to use ETW for investigation, you can:

    1. Collect the counters via (need to be started before the scenario execution and ctrl-c after scenario done):
    ```
    .\PerfView.exe collect /NoGui /Providers=Microsoft-Windows-DotNETRuntime /NoNGenRundown /Merge:False /DataFile:msbuild-alc-etw /BufferSize:8096 /CircularMB:8096
    ```

    2. And then filter-in the `Microsoft-Windows-DotNETRuntime/AssemblyLoader` EventTypes and `Microsoft.NET.StringTools` (and possbily `Microsoft.Build` as well) data. For easier viewing you can setup `AssemblyName ActivityID Success *` columns.

    ![image](https://github.com/dotnet/msbuild/assets/3809076/fff08295-901a-484e-9d8f-b9656a687928)

**Comment by Forgind** [comment] 2023-12-23 01:20
I only briefly glanced at this issue, but is CSDK using MSBuildLocator? MSBuildLocator specifies loading our assemblies into the _default_ ALC:
https://github.com/microsoft/MSBuildLocator/blob/0bd7d2689d9e0e03a4b0e5bcdccf053f61887f90/src/MSBuildLocator/MSBuildLocator.cs#L253

**Comment by JanKrivanek** [comment] 2023-12-27 11:31
> I only briefly glanced at this issue, but is CSDK using MSBuildLocator? MSBuildLocator specifies loading our assemblies into the _default_ ALC: https://github.com/microsoft/MSBuildLocator/blob/0bd7d2689d9e0e03a4b0e5bcdccf053f61887f90/src/MSBuildLocator/MSBuildLocator.cs#L253

I do not know. But it's a good lead indeed! Should definitely be investigated as part of this item.

From my uninformed point of view - forcing the Default ALC should be used only if necessary and in such case accompanied with checking and leading to explicit fast failing if attempted to workaround. Though at this point such ship might already have sailed.

**Comment by Forgind** [comment] 2023-12-27 16:55
We're generally more willing to accept breaking changes in MSBuildLocator than MSBuild proper, but we can also avoid a breaking change if we have a separate API that permits you to specify your ALC and falls back to the default 🙂 That isn't quite the same as what you're proposing, but if that really is the root of the problem, CSDK should be able to opt in, which would mitigate the issue from their perspective.

**Comment by ladipro** [comment] 2024-01-09 15:29
Making an explicit `LoadFromAssemblyPath` call with the desired path "fixes" it in that subsequent by-name binds get correctly resolved to this explicitly loaded assembly.

`alc.LoadFromAssemblyPath(@"C:\temp\ALCTwoAssemblies\ClassLib2\bin\Debug\net8.0\ClassLib.dll");`

This could potentially be a workaround for CDK.

**Comment by Forgind** [comment] 2024-01-09 18:03
LoadFromAssemblyPath leads to more JITting, doesn't it? Relative to Load?

Is it intentional for it to be added to the default ALC? Another possible option might be to ensure it's never added to the default ALC and use multiple not-default ALCs, though that might be a bit unwieldy.

**Comment by vitek-karas** [comment] 2024-01-09 20:59
> @vitek-karas, is this by design? It's caught us by surprise here and cascaded into a user impacting issue in https://github.com/dotnet/msbuild/issues/9538.

The behavior as shown by the repro project you shared is by design. 

The detailed description of the algorithm used by the runtime is here: https://learn.microsoft.com/en-us/dotnet/core/dependency-loading/loading-managed#algorithm
But in short, the `Resolving` event is raised as a fallback (almost) last chance. If the custom ALC should allow "duplicate" loading of assemblies which are also in Default, it needs to do so in the `Load` override, not in the `Resolving` event. The `Load` override is the first thing called, there the custom ALC can implement any behavior it wants we regard to what is loaded into it (call LoadFromAssemblyPath), or what is loaded from Default (return null).

I don't know where the actual code discussed in this issue live, so I can't comment on the specifics unfortunately.

**Comment by ladipro** [comment] 2024-01-09 21:14
@vitek-karas thank you! The code in question lives in CPS (not open source). I'm closing this issue and will continue in AB#1937630.
cc @lifengl

**Comment by Pilchie** [comment] 2024-01-09 21:14
✅ Successfully linked to Azure Boards work item(s):
- [Bug 1937630](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1937630)

**Closed** 2024-01-09 21:14 UTC
Labels: Iteration:2024January
