### ISSUE TITLE
Accidentally enumerating the entire drive with globs and a non-existing root directory

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#6459] opened 2021-05-17 02:51 UTC
Build this project:

```
<Project DefaultTargets="Build">

  <ItemGroup>
    <File Include="$(NonExistent)\**\*" />
  </ItemGroup>

  <Target Name="Build">
  </Target>

</Project>
```

I think there should be some sort of safeguard, because currently this enumerates the entire drive.

**Comment by KirillOsenkov** [comment] 2021-05-17 02:52
I'm impressed that it takes 48 seconds, logs 1.5 million items and succeeds.

But in a more real scenario it failed the build with 0 errors 0 warnings because the copy task tried to copy a file from some system directory and got access denied.

**Comment by KirillOsenkov** [comment] 2021-05-17 03:44
Filed a separate issue for failing the build with 0 errors when evaluator crashes:
https://github.com/dotnet/msbuild/issues/6460

**Comment by rainersigwald** [comment] 2021-05-21 22:15
In the past, we've considered logging this case: https://github.com/dotnet/msbuild/issues/3204. We've been scared of fixing it for fear of breaking someone who's doing it "on purpose". But maybe now that we have changewaves we should just do it for 17.0.

**Comment by rainersigwald** [comment] 2021-05-21 22:17
Duplicate of https://github.com/dotnet/msbuild/issues/1083

**Closed by rainersigwald** 2021-05-21 22:17 UTC
Labels: Feature - Globbing
