### ISSUE TITLE
Allow to share ProjectElementRootCache between ProjectCollection

### ISSUE THREAD

**Issue by xoofx** [dotnet/msbuild#7107] opened 2021-12-01 08:23 UTC
Hello!

This is a feature improvement/request. A `ProjectCollection` is creating internally a `ProjectRootElementCache` instance, but when working on a build server, we need to have a way to share the same cache for all `ProjectCollection` configurations that we need to create. Today, it's impossible to achieve this without hacking into through `System.Reflection` to share the cache.

How could we best bring this feature?

Could we add a constructor to `ProjectCollection` that would take another `ProjectCollection` to reuse the same `ProjectRootElementCache` ?

Something like this by adding a `ProjectCollection sharedCache = null` last parameter?

```c#
public ProjectCollection(IDictionary<string, string> globalProperties,
                            IEnumerable<ILogger> loggers,
                            IEnumerable<ForwardingLoggerRecord> remoteLoggers,
                            ToolsetDefinitionLocations toolsetDefinitionLocations,
                            int maxNodeCount,
                            bool onlyLogCriticalEvents,
                            bool loadProjectsReadOnly,
                            ProjectCollection sharedCache = null)
{
    // 
}
```

cc: @KirillOsenkov

**Comment by KirillOsenkov** [comment] 2021-12-01 22:23
I've been meaning to file this since forever, thanks for filing it!

MSBuild team, please if possible let's treat this with higher priority (not urgency, but priority) because this may unlock a lot of value for a class of MSBuild hosts. @xoofx is on to some very interesting prototyping and it would be wonderful if we could support that effort if we can.

For reference:
https://twitter.com/xoofx/status/1466082683889586177

**Comment by rainersigwald** [comment] 2021-12-02 15:25
> when working on a build server, we need to have a way to share the same cache for all `ProjectCollection` configurations that we need to create.

Can you elaborate on this a bit please? I don't think I object to the idea in theory but I'm not sure I understand the use case.

**Comment by xoofx** [comment] 2021-12-02 19:53
> Can you elaborate on this a bit please? I don't think I object to the idea in theory but I'm not sure I understand the use case.

Let's say that for example a server receive a request to build Release, and then Debug, I would like to maintain a state of e.g ProjectCollections that would use the same cache for the XML projects loaded (because they are identical). So for example:

- ProjectCollection for Release
- ProjectCollection for Debug

Both pointing to the same underlying `ProjectRootElementCache`.

Later, this project collection are used to propagate the cache to BuildParameters (with the `BuildParameter(ProjectCollection)` [constructor](https://github.com/dotnet/msbuild/blob/9bcc06cbe19ae2482ab18eab90a82fd079b26897/src/Build/BackEnd/BuildManager/BuildParameters.cs#L231))

while retrieved internally in BuildParameters here:

https://github.com/dotnet/msbuild/blob/9bcc06cbe19ae2482ab18eab90a82fd079b26897/src/Build/BackEnd/BuildManager/BuildParameters.cs#L914


but with the existing API, it's not possible to maintain different ProjectCollection concurrently in memory that could share the same `ProjectRootElementCache`, so I assume that all XML msbuild files are going to be deserialized multiple times.

Hence why I would like to have a way to share this cache across these ProjectCollection instances.

**Comment by xoofx** [comment] 2021-12-05 16:01
The PR #7122 proposes a fix for this problem by introducing a new type `ProjectCollectionRootElementCache` that serves as a holder for a `ProjectRootElementCache`. It allows also to create `ProjectRootElementCache` with auto reload which was not possible before

**Comment by rokonec** [comment] 2023-02-06 12:10
@xoofx We apologize for letting this PR unattended for so long.
I believe we have already addressed a root cause of that and the changes are already merged in the main.

https://github.com/dotnet/msbuild/blob/fc3ab4c5e2a486abb8fc66aede7ec8e3eb91fe08/src/Build/Definition/ProjectCollection.cs#L302-L316

as a part of #7655

Please feel free to reopen, if these changes are not sufficient for your needs.

**Closed by rokonec** 2023-02-06 12:10 UTC
Labels: needs-design
