### ISSUE TITLE
[Broken Build]: MSBuild and Packages with Content Files

### ISSUE THREAD

**Issue by maddinthegreat** [dotnet/msbuild#8681] opened 2023-04-20 11:58 UTC
### Issue Description

I have a problem with MSBuild an packages.

I have an application referencing an assembly which references a package, which has "contentFiles" in it like:

Main App A -> Assembly B -> Package C with assemblies and content files (exe + json)!

These content files are executables who are needed by the main application to run (remote api with pipes / proxy).

Problem: 

MSBuild copies these exe-content files included in the package referenced by Assembly B not to the output folder of Main App A. They are only written to the output folder of Assembly B.

Is there a solution or workaround?

Package C content:

<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/3RqdK5JK/2023-04-20-13-49-15-Nu-Get-Package-Explorer-Legacy-Wrapper-1-0-60.png' border='0' alt='2023-04-20-13-49-15-Nu-Get-Package-Explorer-Legacy-Wrapper-1-0-60'/></a>

Regards

### Steps to Reproduce

Build an application referencing an assembly which references a package with content files in it.

### Expected Behavior

Main application output folder has content files of an **Package C** in it.

### Actual Behavior

Main application does not have  content files of **Package C**  referenced by **Assembly B** in it's output folder.

### Ask us questions

Which setting mus i do in the .csproj to achieve my goal?

**Comment by JaynieBai** [comment] 2023-04-24 10:00
Can't repro as follows. 
1. Create project B Domain.csproj  reference ContentFilesExample
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ContentFilesExample" Version="1.0.2">
    </PackageReference>
  </ItemGroup>

</Project>
```
2. Create project A reference project B
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net7.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj">
    </ProjectReference>
  </ItemGroup>

</Project>
```
3. Build the solution and find the content files tools/run.cmd and tools/run.sh are in the project A and project B output folder.

**Comment by maddinthegreat** [comment] 2023-04-24 20:17
**Project B** is **not** a project reference, but a package reference!
Project B + Project C are both packages!

Regards

**Comment by JaynieBai** [comment] 2023-04-25 02:42
This issue should be related with https://github.com/NuGet/Home/issues/4837#issuecomment-673193030

**Comment by maddinthegreat** [comment] 2023-04-25 03:11
> This issue should be related with [NuGet/Home#4837 (comment)](https://github.com/NuGet/Home/issues/4837#issuecomment-673193030)

If you don't know the answer or don't understand the problem so when why you answer?

The packages are being built by MSBuild and they are still existent so why in God's name is this a problem of Nuget?

The ContentFiles of Package C are not copied to output folder of the main application.

**Comment by rainersigwald** [comment] 2023-04-25 14:55
@maddinthegreat remember the [code of conduct](https://dotnetfoundation.org/about/policies/code-of-conduct) and demonstrate empathy and kindness toward other people. Your last message fell short of that.

**Comment by rainersigwald** [comment] 2023-04-25 14:56
Duplicate of https://github.com/NuGet/Home/issues/4837#issuecomment-673193030

**Comment by rainersigwald** [comment] 2023-04-25 14:57
Since NuGet controls what parts of packages are presented to MSBuild, I agree with @JaynieBai that this belongs in the linked issue.

**Closed by rainersigwald** 2023-04-25 14:56 UTC
Labels: needs-triage
