### ISSUE TITLE
(OutputPath) Property Break / Regression in Recent 5.0 Sdk Patch

### ISSUE THREAD

**Issue by Cooksauce** [dotnet/msbuild#7041] opened 2021-11-17 05:45 UTC
### Issue Description
A recent 5.0 Sdk patch changes the `$(OutputPath)` property on Windows & Linux. MacOS appears unaffected.

The break is that `$(OutputPath)` used to contain the trailing path separator (ie `path/to/build/`).
Now it does not include the trailing separator `path/to/build`.

This breaks custom build targets.

* This can be worked around... but the inconsistency between OS's may warrant a look.

### Steps to Reproduce
MacOS:
* Create new dotnet project from any template (with Docker enabled)
* Add build target:
```
  <Target Name="PrintOutputPath" BeforeTargets="BeforeBuild">
    <Message Importance="high" Text="Output Path: '$(OutputPath)'" />
  </Target>
```
* Build In MacOS terminal
Output (trimmed): `Output Path: 'bin/Release/net5.0/'`
* Build In Docker container (image: `mcr.microsoft.com/dotnet/sdk:5.0`)
Output (trimmed): `Output Path: '/app/build'`

-- This reproduces in latest image `mcr.microsoft.com/dotnet/sdk:5.0.403`
-- Windows also appears to have this 'no trailing separator' behavior

### Expected Behavior
`$(OutputPath)` should include the trailing slash to avoid breaking custom build targets/tools

### Actual Behavior
`$(OutputPath)` does not include trailing slash on Windows & Linux

### Ask us questions
Given the inconsistency between OS's I'm guessing this was not intentional?

**Comment by Forgind** [comment] 2021-11-18 00:50
I think this is a dupe of #5965, but this has a nicer repro, and that one has more useful details around where the bug originated. My sense is that there's some important difference between `<MyProperty Condition="!HasTrailingSlash('$(MyProperty)')">$(MyProperty)\</MyProperty>` and `<MyProperty>$([MSBuild]::EnsureTrailingSlash('$(MyProperty)'))</MyProperty>`, but I can't figure out what it is by code inspection.

**Comment by Forgind** [comment] 2021-12-09 17:50
Any chance you can provide a binlog of the version where it doesn't print a slash? What version are you using? I tried your repro on Windows, using current main to build it, and it printed it out with a slash.

**Comment by marcpopMSFT** [comment] 2022-01-07 17:58
Close as needs more info. Please provide an https://aka.ms/binlog and reactivate if you still see this.

**Closed by marcpopMSFT** 2022-01-07 17:58 UTC
Labels: needs-more-info
