### ISSUE TITLE
[MSBuild]::MakeRelative fails with "Invalid URI: The hostname could not be parsed." when using opening from WSL2

### ISSUE THREAD

**Issue by rlabrecque** [dotnet/msbuild#6310] opened 2021-03-30 02:21 UTC
### Issue Description

When you have a VS2019 C# project inside a WSL2 container and try to open it, you can end up with this error:

```
\\wsl$\Debian\home\user\Redacted\Redacted.csproj : error  :
The expression "[MSBuild]::MakeRelative(\\wsl$\Debian\home\user\Redacted, \\wsl$\Debian\home\user\Redacted\obj\project.assets.json)" cannot be evaluated.
Invalid URI: The hostname could not be parsed.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\NuGet\16.0\Microsoft.NuGet.targets
```

Note: This might be a problem with UNC paths in general, or may be the damn dollar sign in \\wsl$\, haven't dug that far into it.

### Versions & Configurations

Windows 10H2
WSL2
Visual Studio 2019 Version 16.9.2

**Comment by danmoseley** [comment] 2021-03-30 03:03
See https://github.com/dotnet/runtime/issues/36595

**Comment by rlabrecque** [comment] 2021-03-30 04:23
Perfect, thanks. I believe I have seen the WSL2 team also mentioning a switch away from \\wsl$\ as well.

Feel free to close this if you want, there should be enough info here for the next person to search for this ticket.

**Comment by danmoseley** [comment] 2021-03-30 04:48
It's not my repo, but since the issue is in my repo, I will be bold and close this..

**Closed by danmoseley** 2021-03-30 04:48 UTC
Labels: bug, untriaged
