### ISSUE TITLE
Repo local issue: msbuild non-deterministically fails to build

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/msbuild#11100] opened 2024-12-06 11:20 UTC
```
      Microsoft.Build -> D:\a\_work\1\vmr\src\msbuild\artifacts\bin\Microsoft.Build\Release\net472\Microsoft.Build.dll
    D:\a\_work\1\vmr\.dotnet\sdk\10.0.100-alpha.1.24555.54\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error : The process cannot access the file 'D:\a\_work\1\vmr\src\msbuild\artifacts\obj\Microsoft.Build.Framework\Release\Microsoft.Build.Framework.17.13.0-ci-24606-01.nuspec' because it is being used by another process. [D:\a\_work\1\vmr\src\msbuild\src\Framework\Microsoft.Build.Framework.csproj::TargetFramework=net472]
##[error].dotnet\sdk\10.0.100-alpha.1.24555.54\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) The process cannot access the file 'D:\a\_work\1\vmr\src\msbuild\artifacts\obj\Microsoft.Build.Framework\Release\Microsoft.Build.Framework.17.13.0-ci-24606-01.nuspec' because it is being used by another process.
      Successfully created package 'D:\a\_work\1\vmr\src\msbuild\artifacts\bin\Microsoft.Build.BuildCheck.UnitTests\CustomChecks\Microsoft.Build.Framework.17.13.0-ci-24606-01.nupkg'.
    D:\a\_work\1\vmr\.dotnet\sdk\10.0.100-alpha.1.24555.54\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error : The process cannot access the file 'D:\a\_work\1\vmr\src\msbuild\artifacts\bin\Microsoft.Build.BuildCheck.UnitTests\CustomChecks\Microsoft.Build.17.13.0-ci-24606-01.nupkg' because it is being used by another process. [D:\a\_work\1\vmr\src\msbuild\src\Build\Microsoft.Build.csproj::TargetFramework=net9.0]
##[error].dotnet\sdk\10.0.100-alpha.1.24555.54\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) The process cannot access the file 'D:\a\_work\1\vmr\src\msbuild\artifacts\bin\Microsoft.Build.BuildCheck.UnitTests\CustomChecks\Microsoft.Build.17.13.0-ci-24606-01.nupkg' because it is being used by another process.
      Successfully created package 'D:\a\_work\1\vmr\src\msbuild\artifacts\bin\Microsoft.Build.BuildCheck.UnitTests\CustomChecks\Microsoft.Build.17.13.0-ci-24606-01.nupkg'.
```

from https://dev.azure.com/dnceng-public/public/_build/results?buildId=887994&view=logs&j=af161a59-3ba0-595e-b1dd-589f209b7277&t=169bd431-100e-5e1f-71a2-8f0b618112dd&l=320

Looks like Microsoft.Build packages are created in parallel multiple times (the CustomChecks unit tests seem to create the packages again).

This caused the VMR build to fail.

**Comment by ViktorHofer** [comment] 2024-12-06 11:23
@mmitche here's another case of a project that shouldn't even build inside the VMR by default (test) but its target still runs: https://github.com/dotnet/msbuild/blob/6ca999210ce0e6541d92532874b732c4fceee8de/src/BuildCheck.UnitTests/Microsoft.Build.BuildCheck.UnitTests.csproj#L53

That's because the SuppressAllTargets / `ExcludeFrom*` can handle these scenarios when there's a BeforeTargets / AfterTargets hook defined.

**Comment by YuliiaKovalova** [comment] 2024-12-10 10:17
I close it as a dupe of https://github.com/dotnet/msbuild/issues/11090

**Closed by YuliiaKovalova** 2024-12-10 10:17 UTC
