### ISSUE TITLE
[NETSDKE2E]Redundant messages are displayed in terminal output when running .NET 9.0 project.

### ISSUE THREAD

**Issue by vdanche** [dotnet/msbuild#9809] opened 2024-03-01 08:54 UTC
### Issue Description

Redundant messages are displayed in terminal output when running .NET 9.0 project.

### Steps to Reproduce

1. Install Net 9.0.100-preview.2.24129.7 SDK on window11-x64.
2. in CLI, dotnet new console -o testconsole
3. cd testconsole and then dotnet build
4. after dotnet build, run "dotnet run" and then check if log info can be displayed well.

### Expected Behavior

For step4,
There is no build log displaying and the result can be displayed directly in CLI.

### Actual Behavior

Build info displays again even though we have built project in step3.
![image](https://github.com/dotnet/msbuild/assets/65637796/e59d32c7-c10d-45b6-b51b-6a97408176de)

**Comment by vdanche** [comment] 2024-03-01 09:04
For net8.0 SDK, The build info will not be displayed again if we had built project before and then run project.
![image](https://github.com/dotnet/msbuild/assets/65637796/da539cec-f7dc-41d1-8a2e-5fd1fbd03947)

**Comment by v-ainigao** [comment] 2024-03-01 09:26
This issue also repro's on arm64/mac/Linux OS.

**Comment by baronfel** [comment] 2024-03-01 14:04
`dotnet run` should be passing the `quiet` verbosity here, but I believe the core problem is that Terminal Logger doesn't respect `quiet` verbosity. I think the way to go here would be for `run` to opt into the older console logger specifically.

**Comment by AR-May** [comment] 2024-03-18 15:28
Yes, I just checked once more - the redirection detection works as expected there and TL is not used in this case.

**Comment by AR-May** [comment] 2024-03-18 15:59
I am closing this issue as a duplicate of #9654 then.

**Closed** 2024-03-19 08:14 UTC
Labels: bug, needs-triage

**Comment by vdanche** [comment] 2024-04-11 08:40
This issue not repro on 9.0.100-preview.4.24210.38
![image](https://github.com/dotnet/msbuild/assets/65637796/de5762fc-c213-470d-8ff3-319c6bfcdcb5)
