### ISSUE TITLE
Feature-Request: Evaluate Property via Command-Line

### ISSUE THREAD

**Issue by Scordo** [dotnet/msbuild#5725] opened 2020-09-09 13:21 UTC
### Wanted

Provide a way to evaluate a property of a msbuild script via msbuild.exe

### Motivation

We often have to read property values of msbuild scripts via powershell to automate different kind of tasks.
Simple example: Read a compound property "Version" ($(Major).$(Minor).$(Build).$(Revision) from a provided *.csproj file to automatically increment Versions and other stuff.

### Current Problem
Currently we do load Microsoft.Build.dll into Powershell 5.1 and evaluate the property using the API.
This broke with the latest 16.7 version, see: https://twitter.com/DotNetExpert/status/1293172276293251073

So our current workaround is a proxy-script which gets passed the wanted msbuild script file and the properties to evaluate and prints the values in a custom target. This works in Powershell 5.1 and 7.X.

### The suggested way

Provide a new command-line switch to evaluate properties. Here are possible scenarios:

**Scenario 1: "Magic Target"**
* Description: A new "magic target" like "_PropertyEvaluation" is introduced and a new switch like "/ep" or "evaluateproperty" which produces the later following output
* CMD-Line: msbuild.exe MyMsbuildScript.csproj /t _PropertyEvaluation /ep:Version /ep:Major
* Output: 
```
Version=1.2.3.4
Major=1
```

**Scenario 2: New cmdline-switch**
* Description: A new cmdline-switch like "/evaluate" is introduced and a new switch like "/ep" or "evaluateproperty" which produces the later following output
* CMD-Line: msbuild.exe MyMsbuildScript.csproj /evaluate /ep:Version /ep:Major
* Output: 
```
Version=1.2.3.4
Major=1
```

Thanks and regards!
Jens

**Comment by Scordo** [comment] 2020-09-09 13:30
After doing a a less detailed search through the issues I found an issue which suggests the same: https://github.com/dotnet/msbuild/issues/3911

**Comment by rainersigwald** [comment] 2020-12-02 21:09
Duplicate of #3911

**Closed by rainersigwald** 2020-12-02 21:09 UTC
