### ISSUE TITLE
Incorrect (windows) assemblies are copied for a Xamarin.iOS application

### ISSUE THREAD

**Issue by spouliot** [dotnet/msbuild#6072] opened 2021-01-22 18:29 UTC
### Issue Description

The `_CopyFilesMarkedCopyLocal` task from `msbuild` incorrectly gives us the win-specific assemblies to copy. This makes the build fail at a later stage.

```
Target "_CopyFilesMarkedCopyLocal" in file "/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Microsoft.Common.CurrentVersion.targets":
  Using "Copy" task from assembly "/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/../iOS/Xamarin.iOS.Tasks.dll".
  Task "Copy"
    Copying file from "/Users/poupou/.nuget/packages/mongodb.driver/2.11.6/lib/netstandard2.0/MongoDB.Driver.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/MongoDB.Driver.dll".
    Copying file from "/Users/poupou/.nuget/packages/mongodb.driver.core/2.11.6/runtimes/win/native/snappy64.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/snappy64.dll".
    Copying file from "/Users/poupou/.nuget/packages/mongodb.driver.core/2.11.6/runtimes/win/native/snappy32.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/snappy32.dll".
    Copying file from "/Users/poupou/.nuget/packages/mongodb.bson/2.11.6/lib/netstandard2.0/MongoDB.Bson.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/MongoDB.Bson.dll".
    Copying file from "/Users/poupou/.nuget/packages/dnsclient/1.3.1/lib/netstandard2.1/DnsClient.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/DnsClient.dll".
    Copying file from "/Users/poupou/.nuget/packages/mongodb.driver.core/2.11.6/runtimes/win/native/libzstd.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/libzstd.dll".
    Copying file from "/Users/poupou/.nuget/packages/mongodb.driver.core/2.11.6/lib/netstandard2.0/MongoDB.Driver.Core.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/MongoDB.Driver.Core.dll".
    Copying file from "/Users/poupou/.nuget/packages/mongodb.libmongocrypt/1.0.0/lib/netstandard1.5/MongoDB.Libmongocrypt.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/MongoDB.Libmongocrypt.dll".
    Copying file from "/Users/poupou/.nuget/packages/sharpcompress/0.23.0/lib/netstandard2.0/SharpCompress.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/SharpCompress.dll".
    Copying file from "/Users/poupou/.nuget/packages/system.buffers/4.4.0/lib/netstandard2.0/System.Buffers.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/System.Buffers.dll".
    Copying file from "/Users/poupou/.nuget/packages/system.io.compression/4.3.0/runtimes/win/lib/netstandard1.3/System.IO.Compression.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/System.IO.Compression.dll".
    Copying file from "/Users/poupou/.nuget/packages/system.net.http/4.3.0/runtimes/win/lib/netstandard1.3/System.Net.Http.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/System.Net.Http.dll".
    Copying file from "/Users/poupou/.nuget/packages/system.runtime.interopservices.runtimeinformation/4.3.0/runtimes/win/lib/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/System.Runtime.InteropServices.RuntimeInformation.dll".
    Copying file from "/Users/poupou/.nuget/packages/system.security.cryptography.algorithms/4.3.0/runtimes/win/lib/netstandard1.6/System.Security.Cryptography.Algorithms.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/System.Security.Cryptography.Algorithms.dll".
    Copying file from "/Users/poupou/.nuget/packages/system.security.cryptography.encoding/4.3.0/runtimes/win/lib/netstandard1.3/System.Security.Cryptography.Encoding.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/System.Security.Cryptography.Encoding.dll".
    Copying file from "/Users/poupou/.nuget/packages/system.security.cryptography.x509certificates/4.3.0/runtimes/win/lib/netstandard1.6/System.Security.Cryptography.X509Certificates.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/System.Security.Cryptography.X509Certificates.dll".
    Copying file from "/Users/poupou/.nuget/packages/system.text.encoding.codepages/4.5.1/runtimes/win/lib/netstandard2.0/System.Text.Encoding.CodePages.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/System.Text.Encoding.CodePages.dll".
    Copying file from "/Users/poupou/.nuget/packages/xamarin.essentials/1.5.3.2/lib/xamarinios10/Xamarin.Essentials.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/Xamarin.Essentials.dll".
    Copying file from "/Users/poupou/.nuget/packages/xamarin.essentials/1.5.3.2/lib/xamarinios10/Xamarin.Essentials.pdb" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/Xamarin.Essentials.pdb".
  Done executing task "Copy".
  Using "Touch" task from assembly "/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/../iOS/Xamarin.iOS.Tasks.dll".
  Task "Touch"
    Creating "/Users/poupou/Projects/bugs/gh10337/obj/iPhoneSimulator/Debug/gh10337.csproj.CopyComplete" because "AlwaysCreate" was specified.
  Done executing task "Touch".
Done building target "_CopyFilesMarkedCopyLocal" in project "gh10337.csproj".
```

More details at https://github.com/xamarin/xamarin-macios/issues/10337
A similar issue: https://github.com/xamarin/xamarin-macios/issues/5265

### Steps to Reproduce

1. Create a new Xamarin multiplatform app with Xamarin iOS.
2. Consume MongoDB.Driver nuget: https://www.nuget.org/packages/MongoDB.Driver/2.11.5
3. Rebuild application

### Expected Behavior

Successful build

### Actual Behavior

Build fails with
```
MTOUCH : error MT0009: Error while loading assemblies: /Users/poupou/.nuget/packages/mongodb.driver.core/2.11.6/runtimes/win/native/libzstd.dll.
```

### Ask us questions

I'm not sure if the issue is with the nuget package, nuget itself or msbuild.

However the Xamarin.iOS SDK is being given the wrong set of assemblies and cannot produce a valid application from them.

**Comment by pasha-o** [comment] 2021-01-23 21:02
can you please get more eyes on this - I reported this issue mid-2020 and we can't deploy to iOS since then

**Comment by DmitryLukyanov** [comment] 2021-02-01 20:00
Hey, is there a raw estimation of when this issue can be triaged?

**Comment by BenVillalobos** [comment] 2021-02-03 16:56
@nkolev92 is this a NuGet issue?

**Comment by nkolev92** [comment] 2021-02-04 02:17
Not sure, can someone please attach an assets file?

**Comment by DmitryLukyanov** [comment] 2021-02-04 12:50
[assets.zip](https://github.com/dotnet/msbuild/files/5925749/assets.zip)
`project.assets.json` for a regular console app (with netcoreapp31) on mac is almost the same as on windows with the difference in paths and target frameworks (on windows: netcoreapp30, on mac: netcoreapp31)

**Comment by mrward** [comment] 2021-02-04 13:02
I believe this is a mono/msbuild problem. The msbuild restore adds win runtimes to the project.assets.json file incorrectly. Looking at the assets.zip file in the comment above you can see the win runtimes added at the end of the file on the mac, but not on Windows.

https://github.com/mono/mono/issues/15569

**Comment by neminush** [comment] 2021-03-17 11:09
I ran into a similar to this problem [macOS/iOS can't build x86/x64 when NuGet has runtimes](https://github.com/xamarin/xamarin-macios/issues/5265) with Visual Studio for Mac 8.9.2 (build 0) and early versions.

/Users/Neocriss/Documents/iLive.Mobile/ILive/ILive.iOS/MTOUCH: Error MT0009: Error while loading assemblies: /Users/Neocriss/.nuget/packages/harfbuzzsharp/2.6.1.7/runtimes/win-x86/native/libHarfBuzzSharp.dll. (MT0009) (ILive.iOS)

I added the following lines to the file 'ILive.iOS.csproj':
```
<RestoreProjectStyle>PackageReference</RestoreProjectStyle>
<RuntimeIdentifiers>osx;osx-x86;osx-x64</RuntimeIdentifiers>
```
then the problem disappeared.

**Comment by DmitryLukyanov** [comment] 2021-03-23 21:19
it helps for me too

**Comment by Tyri0n** [comment] 2021-05-06 12:49
fixed for me too - many thanks @neminush

**Comment by rainersigwald** [comment] 2021-09-16 16:47
Based on the above, this is a NuGet restore issue.

**Comment by rainersigwald** [comment] 2021-09-16 16:48
This issue was moved to NuGet/Home#11239

**Comment by aortiz-msft** [comment] 2021-09-27 20:16
This seems like a dupe of https://github.com/mono/mono/issues/15569. Also, NuGetRuntimeIdentifier is not something NuGet has ever defined, we just read RuntimeIdentifiers and RuntimeIdentifier.

**Closed** 2021-11-11 17:59 UTC
Labels: needs-triage
