### ISSUE TITLE
[Bug]: Item include wildcards can endup unexpanded

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#8770] opened 2023-05-18 07:04 UTC
### Issue Description

An Item defined as:

```
<MessageSchemaFile Include="..\**\*.mpl" />
```

Ends up unexpanded after evaluation:

<img width="200" alt="image" src="https://github.com/dotnet/msbuild/assets/3809076/52dae71c-4798-4823-8594-b66b75416900">

One of the causes leading to this is nonexistence of files that could have been matched, though the Item should endup empty in such case (which is an observed behavior in simplified case - so there must be something else comming into play)

Binlogs of success and failed cases: [Internal link] [binlogs](https://microsoft.sharepoint.com/:f:/t/ManagedLanguagesIDE/EugFMglu3gVHp9HPx3isScsB-Vfwu8jJum4awIs4Y1khXA?e=HyVWDr) 
Logs of successful and failed runs: [Internal links] [success - Item expanded](https://cloudbuild.microsoft.com/stamp/DM_S13/dir?path=%5CDS4PNPF00007D5D%5Cd:%5Cdbs%5Csh%5Cddvsm%5C0517_014732%5Csrc%5Cedev%5Cdiagnostics%5Cintellitrace%5CTraceLog%5Cdll%5CLogs%5CRetail%5CX86&stampId=DM_S13); [failed - item stayed as literal](https://cloudbuild.microsoft.com/stamp/DM_S13/dir?path=%5CDS4PNPF000087A4%5Cd:%5Cdbs%5Csh%5Cddvsm%5C0505_155916%5Csrc%5Cedev%5Cdiagnostics%5Cintellitrace%5CTraceLog%5Cdll%5CLogs%5CRetail%5CX86&stampId=DM_S13)

### Versions & Configurations

MSBuild version = "17.6.0-preview-23122-03+f93b24b5a"

**Comment by rainersigwald** [comment] 2023-05-18 13:41
Likely a duplicate of https://github.com/dotnet/msbuild/issues/406.

**Closed** 2023-05-23 13:49 UTC
Labels: bug, needs-triage
