### ISSUE TITLE
-targets flag doesn't list targets, seems to be trying to do a complete compile

### ISSUE THREAD

**Issue by DerekSMorin** [dotnet/msbuild#7994] opened 2022-09-21 13:04 UTC
The -targets flag doesn't list targets, seems to be trying to do a complete compile

msbuild Reliability.sln -targets

Expect a list of targets, but it starts compiling everything.

MSBuild version 17.3.1+2badb37d1 for .NET Framework
17.3.1.41501

I'm talking about this flag:

  -targets[:file]
                     Prints a list of available targets without executing the
                     actual build process. By default the output is written to
                     the console window. If the path to an output file
                     is provided that will be used instead.
                     (Short form: -ts)
                     Example:
                       -ts:out.txt

**Comment by rainersigwald** [comment] 2022-09-21 14:29
Duplicate of #7697

**Closed by rainersigwald** 2022-09-21 14:29 UTC
Labels: bug, needs-triage
