### ISSUE TITLE
msbuild writes error logs into the repo working directory

### ISSUE THREAD

**Issue by tmat** [dotnet/msbuild#6800] opened 2021-08-31 21:49 UTC
Bunch of log files like these appear in the repo working directory:
`MSBuild_Logs\MSBuild_pid-6644_09c03ae13d3e4f07b39f92093364dacd.failure`

```
UNHANDLED EXCEPTIONS FROM PROCESS 6644:
=====================
8/31/2021 9:37:31 AM
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
   at System.IO.Pipes.PipeStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.IO.Pipes.PipeStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
===================
```

Two issues here - first, the exception itself and the fact that msbuild pollutes the repository sources (it's easy to overlook and add them to a commit).
These logs should be written somewhere else, e.g. to a temp directory.

```
>msbuild /version
Microsoft (R) Build Engine version 17.0.0-preview-21426-01+16307632a for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

17.0.0.42601
```

**Comment by rainersigwald** [comment] 2021-09-02 15:39
Duplicate of #6772

**Closed by rainersigwald** 2021-09-02 15:39 UTC
Labels: bug, needs-triage
