### ISSUE TITLE
Can I use/refer project's built assembly in inline task?

### ISSUE THREAD

**Issue by Denis535** [dotnet/msbuild#6811] opened 2021-09-03 17:39 UTC
I'm trying to use my project's built assembly in inline task (For example: I need to make some validation or generate documentation). But it leads to an error ((

Is it even possible?

```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <Target Name="MyTarget" AfterTargets="AfterBuild">
        <MyTask />
    </Target>

    <UsingTask TaskName="MyTask" TaskFactory="RoslynCodeTaskFactory" AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll">
        <ParameterGroup>
        </ParameterGroup>
        <Task>
            <Reference Include="C:\Users\Den\Desktop\ConsoleApp1\ConsoleApp1\bin\Debug\netstandard2.0\ConsoleApp1.dll" />
            <Using Namespace="System" />
            <Code Type="Fragment" Language="cs">
                <![CDATA[
                var type = typeof( Program );
                ]]>
            </Code>
        </Task>
    </UsingTask>

</Project>
```

```
Error	MSB4018		The "MyTask" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'ConsoleApp1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'ConsoleApp1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at InlineCode.MyTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

=== Pre-bind state information ===
LOG: DisplayName = ConsoleApp1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files (x86)/Microsoft Visual Studio/2019/Preview/MSBuild/Current/Bin/
LOG: Initial PrivatePath = NULL
Calling assembly : (Unknown).
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\MSBuild.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: The same bind was seen before, and was failed with hr = 0x80070002.
```

**Comment by Denis535** [comment] 2021-09-05 07:29
This is old problem:
https://stackoverflow.com/questions/9455354/msbuild-inline-task-reference-non-standard-microsoft-assemblies

**Comment by Denis535** [comment] 2021-09-05 08:41
Unfortunately `RoslynCodeTaskFactory` has some bug (( You should use `CodeTaskFactory`.

    <UsingTask TaskName="MyTask" TaskFactory="CodeTaskFactory" AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll">
        <ParameterGroup>
        </ParameterGroup>
        <Task>
            <Reference Include="netstandard, Version=2.0.0.0" />
            <Reference Include="C:\Users\Den\Desktop\ConsoleApp1\ConsoleApp1\bin\Debug\netstandard2.0\ConsoleApp1.dll" />
            <Using Namespace="System" />
            <Code Type="Fragment" Language="cs">
                <![CDATA[
                var type = typeof( Program );
                Log.LogMessage( MessageImportance.High, type.Name );
                ]]>
            </Code>
        </Task>
    </UsingTask>

**Comment by rainersigwald** [comment] 2021-09-09 16:15
Duplicate of #5106

**Closed by rainersigwald** 2021-09-09 16:15 UTC
Labels: needs-triage
