### ISSUE TITLE
Text log format doesn't distinguish between item metadata and new items

### ISSUE THREAD

**Issue by jachin84** [dotnet/msbuild#3966] opened 2018-11-29 01:20 UTC
I'm attempting to create an ItemGroup with some additional metadata and when the metadata spans multiple lines I get empty items created. 

### Steps to reproduce
**Project file**
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" DefaultTargets="BuildAll" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
  </PropertyGroup>

  <!-- This Item Group defines all the Web Projects that need to be built and deployed -->
  <ItemGroup>
    <ProjectsFiles Include="Project1" />
    <ProjectsFiles Include="Project2" />
    <ProjectsFiles Include="Project3" />
  </ItemGroup>

  <Target Name="BuildAll" >
    <Message Text="Building Projects" Importance="high"/>

    <!-- Work out the correct project properties -->
    <ItemGroup>
      <_ProjectsFiles Include="@(ProjectsFiles)">
        <AdditionalProperties>
        AutoParameterizationWebConfigConnectionStrings=false;
        _PackageTempDir=Out\Dir;
        </AdditionalProperties>
      </_ProjectsFiles>
    </ItemGroup>

    <MSBuild Projects="$(MSBuildThisFileFullPath)"
             BuildInParallel="true"
             ContinueOnError="false"
             Targets="OutputMessage"
             Properties="ProjectName=%(ProjectsFiles.Identity)" />

  </Target>

  <Target Name="OutputMessage">
    <Message Text="Building Project $(ProjectName)" Importance="high"/>
  </Target>
</Project>
```

### Expected  behavior
![image](https://user-images.githubusercontent.com/2740855/49192874-b7f38a00-f3c8-11e8-89a7-84ae814dea05.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/2740855/49192885-c2ae1f00-f3c8-11e8-9058-07e6cb5e2e3a.png)

### Environment data
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

15.9.20.62856

OS info:
Windows 10 1809

**Comment by dasMulli** [comment] 2018-11-29 05:57
I believe this is a bug in the log viewer rather than msbuild. cc @KirillOsenkov 

```xml
    <Message Importance="high" Text="@(_ProjectsFiles->'%(Identity): %(AdditionalMetadata)')" />
```
or similar are fine.

**Comment by jachin84** [comment] 2018-11-29 06:33
I think you might be right.

**Comment by rainersigwald** [comment] 2018-11-29 16:13
This issue was moved to KirillOsenkov/MSBuildStructuredLog#224

**Comment by KirillOsenkov** [comment] 2018-11-29 18:58
First of all, thanks for the very detailed bug report and an easy to reproduce issue.

Unfortunately this is one of the few places in MSBuild where logging doesn't have enough structure. The log message has this exact text:

```
Added Item(s): 
    _ProjectsFiles=
        Project1
                AdditionalProperties=
        AutoParameterizationWebConfigConnectionStrings=false;
        _PackageTempDir=Out\Dir;
        
        Project2
                AdditionalProperties=
        AutoParameterizationWebConfigConnectionStrings=false;
        _PackageTempDir=Out\Dir;
        
        Project3
                AdditionalProperties=
        AutoParameterizationWebConfigConnectionStrings=false;
        _PackageTempDir=Out\Dir;
       
```

The viewer is already using various heuristics to recover structure here:
https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/fc35c5ad00fae83a0683aed1f3387b6bcd2d95e7/src/StructuredLogger/Construction/ItemGroupParser.cs#L17

However by looking at the text above the indentation of 8 spaces for the multiline metadata really leaves us no way of knowing that it's the continuation of the metadata value from the previous line.

Ideally the log message would have a more structured representation of items and metadata, however I'm afraid it's not doable because of backwards compatibility. 

Lets keep the issue open on the MSBuild side as well to see if we can improve logging of added items with multiline metadata. Maybe emitting text delimiters?

**Comment by KirillOsenkov** [comment] 2018-11-29 19:21
I've at least fixed the empty items in the viewer, however the metadata value is still not parented under the metadata because the indentation in the text log is wrong:
![image](https://user-images.githubusercontent.com/679326/49246067-deb1c080-f3c8-11e8-9df8-ef56c91d84c1.png)

As a workaround put the values on a single line.

I'll keep thinking if it's possible to add more structure to the logging here.

**Comment by KirillOsenkov** [comment] 2018-11-29 21:16
OK I have an idea how to fix this.

When we print the metadata value that contains multiple lines we should split the value into individual lines and indent each line 8 spaces. This way the indentation will be correct in both the text log and the log viewer.

I may prepare a PR at some point, but probably not soon.

**Comment by jachin84** [comment] 2018-11-29 22:40
Thanks for taking a look so quickly!

**Comment by KirillOsenkov** [comment] 2021-02-14 03:03
I need to test this scenario to make sure #6155 fixes it properly.

**Comment by KirillOsenkov** [comment] 2021-02-26 20:45
Confirmed that #6155 fixes it properly:

![image](https://user-images.githubusercontent.com/679326/109352964-8b8d7900-7830-11eb-8ba0-324be2202ba3.png)

**Comment by KirillOsenkov** [comment] 2021-02-26 20:46
Compare with current behavior:

![image](https://user-images.githubusercontent.com/679326/109352997-9d6f1c00-7830-11eb-9de3-42604b1ddd25.png)

**Comment by KirillOsenkov** [comment] 2021-03-04 03:23
Fixed by https://github.com/dotnet/msbuild/pull/6155

**Closed by KirillOsenkov** 2021-03-04 03:23 UTC
Labels: Area: Logging
