### ISSUE TITLE
Can't build .sln with MSBUILDNOINPROCNODE=1

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#6818] opened 2021-09-05 17:50 UTC
MSBuild `16.11.0+0538acc04`

1. `dotnet new sln`
2. `set MSBUILDNOINPROCNODE=1`
3. `msbuild`

```
Build FAILED.

"C:\Temp\inproc\inproc.sln" (default target) (1) ->
  C:\Temp\inproc\inproc.sln(2,1): error MSB4025: The project file could not be loaded. Data at the root level is invali
d. Line 2, position 1.
```

**Comment by KirillOsenkov** [comment] 2021-09-05 17:54
@cdmihai could you please take a quick look to see if you know what's going on? 
I can't tell whether https://github.com/dotnet/msbuild/pull/6400 is related.

**Comment by cdmihai** [comment] 2021-09-07 18:49
#6400 didn't make it into the 16.11 release, so it's not that.

I can repro the bug for 16.11, but not for 17.0:

16.11
![image](https://user-images.githubusercontent.com/2255729/132395733-e5410168-057e-4275-8559-bdb496225bb4.png)


17.0
![image](https://user-images.githubusercontent.com/2255729/132395783-ded234cd-edc4-489d-9a86-702e6e6e438c.png)

**Comment by rainersigwald** [comment] 2021-09-07 21:47
Duplicate of #3517

**Closed by rainersigwald** 2021-09-07 21:47 UTC
Labels: Area: Engine
