### ISSUE TITLE
Copy task: IsMatchingSizeAndTimeStamp is a bottleneck

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#6001] opened 2021-01-04 06:03 UTC
https://source.dot.net/#Microsoft.Build.Tasks.Core/Copy.cs,8c737dc13878fc22

I've been profiling and IsMatchingSizeAndTimeStamp is showing up a lot:
![image](https://user-images.githubusercontent.com/679326/103505522-45f39780-4e0f-11eb-9e7e-a1dff25976e0.png)

We should investigate if we can use a single file system call that gets both existence and timestamp in a single call.

On Windows calling FindFirstFile is almost sure to be way faster and with lower overhead.

**Comment by BenVillalobos** [comment] 2021-01-06 16:59
Duplicate of #5972

**Closed by BenVillalobos** 2021-01-06 16:59 UTC
Labels: Area: Tasks, Performance-Scenario-Build, performance
