### ISSUE TITLE
MsBuild threats empty string value in property as null

### ISSUE THREAD

**Issue by pavlexander** [dotnet/msbuild#5887] opened 2020-11-16 11:53 UTC
### Issue Description
`MsBuild` threats empty string value in property as null. Essentially it means that you are not able to pass an empty string as a value and there is no way to differentiate between an empty string and a default `null` value

### Steps to Reproduce
I have a task configuration property `RelativePathOverride` defined like this:

```
  <PropertyGroup>
    <RelativePathOverride>..\..\</RelativePathOverride>
  </PropertyGroup>
```

and then used as

```
  <Target Name="CustomTaskTarget" AfterTargets="PostBuildEvent">
    <SimpleTask RelativePathOverride="$(RelativePathOverride)"/> 
  </Target>
```

The task code is following:

```
public class SimpleTask : Task
{
    public string RelativePathOverride { get; set; }
    
    public override bool Execute()
    {
        Log.LogMessage(MessageImportance.High, $"RelativePathOverride: {RelativePathOverride ?? "NULL"}");

        if (RelativePathOverride == null)
        {
            // default value
            RelativePathOverride = "..\\";
        }

    }
}
```

This works fine. However, the problem is that when I provide the empty value for the `RelativePathOverride` property then it's defaulted to `null` as well!

```
  <PropertyGroup>
    <RelativePathOverride></RelativePathOverride>
  </PropertyGroup>
```

This is wrong, because Empty value and null are completely different values. null means that there is no value at all, on the other hand, empty string means that sting has a value that happens to be of length 0.

### Expected Behavior
Empty value is passed as empty string to task property.

### Actual Behavior
Empty value is passed as `null` to task property.

### Analysis
No idea where there problem is, sorry. Also, this functionality been used for ages by other people so I guess nobody really considers this a defect.

In my logic - I want the empty value to be an empty value! This is very important because we are talking about a relative path. NULL value means that there is NO override provided, so the default will be hardcoded to `..\`. But since empty property value is also threated as null then this corrupts my logic..

### Versions & Configurations
- msbuild: 16.7.0.37604
- Microsoft Visual Studio Professional 2019: Version 16.7.7
-     <PackageReference Include="Microsoft.Build.Framework" Version="16.7.0" />
-     <PackageReference Include="Microsoft.Build.Utilities.Core" Version="16.7.0" />
- win 10 enterprise: Version 10.0.18363 Build 18363

**Comment by rainersigwald** [comment] 2020-11-16 21:35
This is happening "by design". It enables defining task invocations like

```xml
<MyTask Option="$(MyOption)" />
```

while not having to differentiate between null and empty string in the task body. As you point out, that is a potentially useful distinction--but since it hasn't been supported, adding the distinction now would be a breaking change for all the tasks that don't make it today.

In addition, since there's no way to _unset_ a property besides setting it to the empty string, this change would make it harder to override behavior defined via properties.

**Comment by pavlexander** [comment] 2020-11-17 08:55
@rainersigwald I understand.. Since it's a breaking change - would it be not possible to introduce a new property attribute to indicate that empty string values are allowed?

Personally, it will be faster for me to do a workaround at this point. But we could still improve the product whilst moving forward! So, maybe you could not threat this topic as a bug fix request but a feature request? :)

**Comment by BenVillalobos** [comment] 2020-11-18 17:16
Team Triage: Closing this out, as the change to make this happen would be fairly large when the workaround is a null check. If you feel strongly about this, feel free to start a discussion over in our [Discussion](https://github.com/dotnet/msbuild/discussions) page

**Closed by BenVillalobos** 2020-11-18 17:16 UTC
Labels: bug, untriaged
