### ISSUE TITLE
project that references a task project, builds on Visual studio but not with donet build

### ISSUE THREAD

**Issue by persiandeveloper** [dotnet/msbuild#6791] opened 2021-08-27 09:53 UTC
I have created a task project (.net standard 2.0), this is referenced by a .net 5 project and uses its task as below :

```
<Target Name="CopyTaskDLL" AfterTargets="CopyFilesToOutputDirectory">
  <Copy SourceFiles="$(OutDir)TaskA.DLL" DestinationFolder="$(TempFolder)"/>
  <--!To prevent ms build lock the dll the task.dll is copied to temp folder-->
</Target>

<Using TaskFactory = "TaskHostFactory" TaskName="TaskA" AssemblyFile="$(TempFolder)\TaskA.DLL"/>

<Target Name="TaskA" DependsOnTargets="CopyFilesToOutputDirectory"  AfterTargets="CopyFilesToOutputDirectory">
    <TaskA />
</Target >
```

It builds successfully in Visual Studio and runs the TaskA, however when I run the dotnet build, it fails  : 

`Could not run the "TaskA" task because MSBuild could not create or connect to a task host with runtime "CLR4" and architecture "x64".  Please ensure that (1) the requested runtime and/or architecture are available on the machine, and (2) that the required executable "C:\Program Files\dotnet\sdk\5.0.303\MSBuild.exe" exists and can be run.`

**Note**: 
Already tried to add the mentioned config [here] (https://stackoverflow.com/questions/61663658/why-is-msbuild-exe-missing-in-c-program-files-dotnet-sdk-3-1-201-causing-azure) to both projects but it did not work. 

dotnet --verision : 5.0.303

**Comment by persiandeveloper** [comment] 2021-08-28 17:24
I pushed it here https://github.com/persiandeveloper/custom-build-task/tree/use-props

**Comment by persiandeveloper** [comment] 2021-08-28 17:25
> What happens if you add `Architecture="x64"` (or x86) to your usingtask like so?
> 
> If that doesn't work, could you provide a simple repro project as a github repo? That way we can poke around and quickly see what's going on.

I pushed it here https://github.com/persiandeveloper/custom-build-task/tree/use-props

**Comment by BenVillalobos** [comment] 2021-08-30 21:40
Notes as I go:

`msbuild *.sln` works with 17.0 preview, `dotnet build *.sln` fails with 6.0.100 preview 7.

In the error message: 
`and (2) that the required executable "C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\MSBuild.exe" exists and can be run.`

is this just the error message, or are we attempting to look for a `.exe` where it should find the `.dll`? Seems like a red herring. cc @rainersigwald

**Comment by rainersigwald** [comment] 2021-08-30 21:42
I don't think we support taskhosts on core at the moment: dotnet/msbuild#5158

**Comment by BenVillalobos** [comment] 2021-08-30 21:56
As Rainer just reminded me offline, `TaskFactory="TaskHostFactory"` causes the task to run out of process, which isn't supported in `dotnet build` scenarios.

If you can get away with it, you can remove that metadata and your build should work fine. Closing this as a duplicate of https://github.com/dotnet/msbuild/issues/5158.

Feel free to comment here with any more questions!

**Closed by BenVillalobos** 2021-08-30 21:56 UTC
Labels: has-repro
