### ISSUE TITLE
[Bug]: Overrides of Predefined Targets Defined in the Project File are not Run in SDK projects

### ISSUE THREAD

**Issue by jrdodds** [dotnet/msbuild#9327] opened 2023-10-13 18:56 UTC
### Issue Description

The documentation at "[Override predefined targets](https://learn.microsoft.com/en-us/visualstudio/msbuild/how-to-extend-the-visual-studio-build-process?view=vs-2022#override-predefined-targets)" lists predefined targets that can be overridden, e.g. `BeforeBuild` and `AfterBuild`.

Overrides of these predefined targets are not run in an SDK style project (but are run in a Legacy style project).

The full list in the documentation is:

`BeforeCompile`
`AfterCompile`
`BeforeBuild`
`AfterBuild`
`BeforeRebuild`
`AfterRebuild`
`BeforeClean`
`AfterClean`
`BeforePublish`
`AfterPublish`
`BeforeResolveReferences`
`AfterResolveReferences`
`BeforeResGen`
`AfterResGen`

### Steps to Reproduce

1. Create a new C# console app project.
2. Modify the .csproj file to include the following:

```xml
  <Target Name="BeforeBeforeBuild" BeforeTargets="BeforeBuild">
    <Message Text=">> BeforeBeforeBuild target"/>
  </Target>

  <Target Name="AfterBeforeBuild" AfterTargets="BeforeBuild">
    <Message Text=">> AfterBeforeBuild target"/>
  </Target>

  <Target Name="BeforeBuild">
    <Message Text=">> BeforeBuild target"/>
    <Touch Files="touched.txt" AlwaysCreate="true"/>
  </Target>
```

3. Build the project with `-v:n`.

The log will show the messages from the `BeforeBeforeBuild` and `AfterBeforeBuild` targets but not the message from the `BeforeBuild` target override and the touched.txt file will not be created.

```
BeforeBeforeBuild:
  >> BeforeBeforeBuild target
AfterBeforeBuild:
  >> AfterBeforeBuild target
```

4. Move the `BeforeBuild` target override to a `Directory.Build.targets` file and the target will work.

With `-v:d` the log shows:

```
Overriding target "BeforeBuild" in project "***\ConsoleApp1.csproj" with target "BeforeBuild" from project "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets".
```

Apparently in Legacy style projects the 'Microsoft.Common.CurrentVersion.targets' file is imported before the content of the project file and in SDK style projects the 'Microsoft.Common.CurrentVersion.targets' file is imported after the content of the project file.

### Expected Behavior

From the documentation and prior behavior, a target override within the project file should work.

### Actual Behavior

The special pre-defined targets can't be overridden.

### Analysis

The "pre-definitions" of the targets occur too late in an SDK style project.

Possible resolutions:

- Move the pre-definitions of the targets from "Microsoft.Common.CurrentVersion.targets" to a file that is imported before the project content.
- Update the documentation appropriately.

The documentation could explain that in an SDK style project the overrides can't be in the project file.

My own practice is to use these predefined targets in `AfterTargets`, `BeforeTargets`, and `DependsOnTargets` attributes and to never override. (That largely derives from an issue where an override was overridden :slightly_frowning_face:.)

**Comment by rainersigwald** [comment] 2023-10-13 19:01
This is not a bug, and is called out (with solution) in a note in the docs page you link

> SDK-style projects have an implicit import of targets after the last line of the project file. This means that you cannot override default targets unless you specify your imports manually as described in [How to: Use MSBuild project SDKs](https://learn.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2022).

We should definitely have an analyzer for this though. Tagged https://github.com/dotnet/msbuild/issues/1680 as such.

**Comment by jrdodds** [comment] 2023-10-13 19:16
Yep. I was blind to the big callout note.

**Comment by rainersigwald** [comment] 2023-10-13 19:19
It's subtle and definitely a problem, but I think analyzers will give us a good way to surface it more clearly.

**Comment by AR-May** [comment] 2023-10-17 13:54
Team triage: We are closing this bug as a duplicate of #1680.

**Closed by AR-May** 2023-10-17 13:54 UTC
Labels: bug, needs-triage
