### ISSUE TITLE
[Feature Request]: Publish Microsoft.Build.UnitTests NuGet package for Task related test utilities

### ISSUE THREAD

**Issue by JanProvaznik** [dotnet/msbuild#10308] opened 2024-06-28 16:53 UTC
### Summary

Authors of MSBuild tasks should be able to use utility classes in MSBuild repo.

### Background and Motivation

I wanted to write a unit test for my custom task and create an test such as https://github.com/dotnet/msbuild/blob/a9c95c7251503f85493d3f3bb43780ffa8104589/src/Tasks.UnitTests/Copy_Tests.cs#L131
which would use [MockEngine](https://github.com/dotnet/msbuild/blob/a9c95c7251503f85493d3f3bb43780ffa8104589/src/UnitTests.Shared/MockEngine.cs#L35)
this is not possible now.

### Proposed Feature

Move Unit testing classes which can be reused for testing custom tasks to a project that will be published as a NuGet package.

**Comment by rainersigwald** [comment] 2024-06-28 17:01
A good idea but I'm going to close as a duplicate of #3569.

**Closed by rainersigwald** 2024-06-28 17:01 UTC
Labels: Feature Request
