### ISSUE TITLE
Optimize I/O in RAR AllowedAssemblyExtension lookups

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#5018] opened 2019-12-31 23:57 UTC
Currently we have the `.winmd` extension first:
```
AllowedAssemblyExtensions
    .winmd
    .dll
    .exe
```

This means that for every assembly in every RAR invocation RAR will try to find the `.winmd` file first. In an overwhelming majority of cases what we want is the `.dll`. 

I suggest reordering the `AllowedAssemblyExtensions` such that we probe for .dll first. This way we'll save an enormous amount of `File.Exists()` calls and our logs won't be as much littered with:

```
Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.Runtime.winmd", but it didn't exist.
```

**Comment by rainersigwald** [comment] 2020-02-24 17:08
Repurposing this bug based on the feedback we got in #5021. Offline discussion suggested that we can't take the easiest approach to looking for the DLL:

> ```
> [2/4 4:58 PM] @KirillOsenkov
>     @davkean points out that it's for C++, where if the .dll and .winmd are side-by-side you want to pick up the .winmd first -- does that sound about right?
> ​[2/4 4:58 PM] [redacted past MSBuild maintainer]
>     Since winmd files are their own thing, not much should conflict so they could go where ever relative to things like hintpath
> ​[2/4 4:58 PM] [redacted past MSBuild maintainer]
>     Let me look at the mail threads, just a sec
> [2/4 4:59 PM] @davkean
>     Chris I think I remember you adding it for C++ consumption
> ​[2/4 5:00 PM] [redacted past MSBuild maintainer]
>     We added it since apps could reference winmd files, I am trying to remember if the assemblyVersion can be the same between dll and winmd, then there would be an order question there
> ​[2/4 5:00 PM] @davkean
>     No in the C++ case if you pick the dll == badness
> ​[2/4 5:01 PM] @davkean
>     dll is native
> ​[2/4 5:01 PM] @davkean
>     winmd is managed
> ​[2/4 5:01 PM] @davkean
>     you want to pick the winmd, not the dll
> [2/4 5:01 PM] @davkean
>     maybe you can handle that case
> ​[2/4 5:01 PM] @davkean
>     fall back to winmd
> ​[2/4 5:01 PM] @davkean
>     in the case the managed header is missing
> ​[2/4 5:02 PM] @davkean
>     Now my recollection could be broken
> ​[2/4 5:02 PM] [redacted past MSBuild maintainer]
>     Maybe I am rusty on RAR but I dont think rar deals with native assemblies.
> ​[2/4 5:02 PM] @davkean
>     It doesn't
> ​[2/4 5:02 PM] @davkean
>     but in the winmd case
> ​[2/4 5:02 PM] @davkean
>     in the consuming C++ case
> ​[2/4 5:03 PM] @davkean
>     you have to look at the winmd
> ​[2/4 5:03 PM] @davkean
>     not the dll
> [2/4 5:03 PM] @davkean
>     I would test that case and figure out how/what breaks after this change
> ​[2/4 5:04 PM] @davkean
>     C# can reference C++ when it produces a winmd
> ​[2/4 5:04 PM] @davkean
>     so make sure that still works after this
> ​[2/4 5:04 PM] [redacted past MSBuild maintainer]
>     I cannot find any particular mail threads about the order of the search paths for winmd.  But I agree with David that you should test to make sure that the correct file is picked up.
> ...
> [2/4 5:12 PM] [redacted past MSBuild maintainer]
>     The only thing I could find was a comment where if we had dll and winmd sxs then we wanted to prefer the winmd.  That was it. Nothing concrete as to why.  
> ​[2/4 5:12 PM] [redacted past MSBuild maintainer]
>     There was a spec, but its on some long dead share.
> ​[2/4 6:18 PM] @davkean
>     I couldn't find additional context on this, so just using my memory to remember above so take it with a grain of salt
> ```

However, there may still be room for improvement here: we could potentially do some wildcard-based filesystem enumerations instead of one-at-a-time to reduce `File.Exists` calls. That wouldn't help the log chattiness, though.

**Comment by rokonec** [comment] 2020-12-03 15:58
@rainersigwald Do we have some current repro which would simulate the .winmd issue? 
Frankly, I know little about .winmd files and their usage.  What is strange, is that `{WinMDFoldersEx:$(TargetPlatformRegistryBase),$(TargetPlatformVersion)};` line from mentioned change is no longer there.
I was thinking about getting *.winmd in directory and test it, but that would be efficient only if there would not be hundreds on windm files in there. Do we have some idea about common 'counts' of those?

**Comment by rainersigwald** [comment] 2020-12-03 16:38
@rokonec The repro for that is the "normal" all-managed-references case. In that case we know we want the `.dll`, but we probe for a nonexistent `.winmd` file in various places, waiting until we fail to find it to probe for `.dll`.

This is done around this chunk of code (and maybe elsewhere):
https://github.com/dotnet/msbuild/blob/cd297218cc01e0fbbe4c1e27380f7d6983c5260d/src/Tasks/AssemblyDependency/Resolver.cs#L314-L331

What I was thinking in February was along the lines of 

```c#
var sorter = GetSorter(executableExtensions);

string pathPrefix = Path.Combine(directory, assemblyName.Name);

Sort(enumerateWildcardPattern(pathPrefix + "*"), sorter);

// resume existing behavior
```

We'd have to make sure that's safe--right now the exists check is a few layers deep

https://github.com/dotnet/msbuild/blob/cd297218cc01e0fbbe4c1e27380f7d6983c5260d/src/Tasks/AssemblyDependency/Resolver.cs#L184

So I'd need to be convinced that this doesn't change behavior. But since directory enumeration is pretty efficient compared to multiple existence probes it could be an improvement.

**Comment by rokonec** [comment] 2020-12-15 13:52
@rainersigwald When I tried to use ChangeWave it requires to add new project reference from `Microsoft.Build.Task` -> `Microsoft.Build`
Can we move ChangeWaves code into Microsoft.Build.Framework as that one seems to be currently referenced by both `Microsoft.Build.Task` and `Microsoft.Build`

**Comment by rainersigwald** [comment] 2020-12-15 15:04
@rokonec Yes, but also no: @BenVillalobos is doing just that in #5864. I bet we can merge that today and then you can rebase.

**Comment by BenVillalobos** [comment] 2020-12-15 19:06
@rainersigwald I just updated #5864 with the last doc update it needed. Should be good to go.

**Comment by BenVillalobos** [comment] 2020-12-17 00:09
@rokonec https://github.com/dotnet/msbuild/pull/5864 is merged, you can rebase now.

**Comment by rokonec** [comment] 2021-02-16 08:52
Changes in related PR broke [RPS](https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/302845)

**Comment by rokonec** [comment] 2021-02-22 19:19
For now I have abandoned changes from https://github.com/dotnet/msbuild/pull/6033

Reasoning:
- VS invokes RAR unexpectedly. For example, during opening WinForm designer it, at PRS sample projects, calls 8x RAR. Because folder-files  are cached per invocation it enumerates all related directories 8 times. This is just  one sample of surprising RAR usage by VS I have encounter, and I expect there might be others. To evaluate risk of regression of VS, all usages of RAR by VS would have to be investigated and estimated.
- Some implementation of Resolver abstract class has their own cached FIleExists implementation which behaves differently then   default FileExists and FileExists from mine PR. It would be very hard, to me, to estimate if change in behavior can break some people. If would be solvable by using current behavior for those Resolvers but it invalidate usability of my changes  further.
- Perf gain from these changes is not significant and is limited only to non SDK msbuild projects, which usage will most probably decrease over time.

Overall, given my current knowledge of msbuild ecosystem, I believe risk-benefit factor of these changes is not making a cut.

**Closed** 2021-02-23 16:03 UTC
Labels: Performance-Scenario-Build, Performance-Scenario-Solution-Open, Task: Resolve Assembly References (RAR), performance, size:3
