### ISSUE TITLE
[Bug]: Fail to load the project successfully with errors about "[MSBuild]::StableStringHash..."

### ISSUE THREAD

**Issue by v-Judy** [dotnet/msbuild#9765] opened 2024-02-21 07:02 UTC
### Issue Description

Fail to load the project successfully with errors about `[MSBuild]::StableStringHash`
![image](https://github.com/dotnet/msbuild/assets/108645282/2fff2424-49d5-416f-bf0a-b7d8049a5731)

### Steps to Reproduce

1. Install the latest 9.0.100-preview.2 SDK from https://github.com/dotnet/installer
2. Install the latest version of VSCode`v1.86.2` and C# Dev Kit`v1.3.10`.
3. Create a new console project and open it using VSCode.
4. Wait for the project load completely

### Expected Behavior

After the project load completely, the terminal without any errors or warnings.

### Actual Behavior

Fail to load the project successfully with errors about "[MSBuild]::StableStringHash..."
![image](https://github.com/dotnet/msbuild/assets/108645282/5d659842-7151-4a8b-ae8c-53629e3afc07)
```
[error] (C:\Users\v-wakang\BlazorServer\BlazorServer.csproj): The expression "[MSBuild]::StableStringHash(BlazorServer.csproj)" cannot be evaluated. Could not load type 'Microsoft.NET.StringTools.FowlerNollVo1aHash' from assembly 'Microsoft.NET.StringTools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
[error] Failed to load project 'C:\Users\v-wakang\BlazorServer\BlazorServer.csproj'. One or more errors occurred. (The expression "[MSBuild]::StableStringHash(BlazorServer.csproj)" cannot be evaluated. Could not load type 'Microsoft.NET.StringTools.FowlerNollVo1aHash' from assembly 'Microsoft.NET.StringTools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.  C:\Program Files\dotnet\sdk\9.0.100-preview.2.24120.18\Microsoft.Common.CurrentVersion.targets)
```

### Analysis

1. This issue reproduces on Windows/Linux/Mac OS.
2. This issue does not repro on the sdk `9.0.100-preview.2.24116.21`.
3. There is a known closed issue [#9538](https://github.com/dotnet/msbuild/issues/9538) on sdk 8.0.200, it fixed by [#9572](https://github.com/dotnet/msbuild/issues/9572)

### Versions & Configurations

dotnet --info:
```
.NET SDK:
Version:           9.0.100-preview.2.24120.16
Commit:            1415dfd3e2
Workload version:  9.0.100-manifests.01ad020e
MSBuild version:   17.10.0-preview-24120-03+53c4f4986

Runtime Environment:
OS Name:     Mac OS X
OS Version:  14.0
OS Platform: Darwin
RID:         osx-x64
Base Path:   /usr/local/share/dotnet/sdk/9.0.100-preview.2.24120.16/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      9.0.0-preview.2.24120.8
  Architecture: x64
  Commit:       2756c94062

.NET SDKs installed:
  9.0.100-preview.2.24120.16 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-preview.2.24120.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-preview.2.24120.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by ladipro** [comment] 2024-02-21 08:54
The latest release version of CDK is 1.3.10 and it contains CPS at commit 38bd321c which has changes up to Jan 10th.

@JanKrivanek it looks like #9721 was merged before CDK shipped the assembly load context fix. Should we revert?

**Comment by JanKrivanek** [comment] 2024-02-21 09:54
Yeah - too early :-/
Let's revert and wait for 1.4.2

**Comment by JanKrivanek** [comment] 2024-02-21 21:23
@v-Judy can you confirm the issue is not present with the same setup with C# DevKit 1.4.2?
We're going to temporarily revert the change and reintroduce once 1.3.x gets out of support, but want to be double sure that that's enough.
Thanks

**Comment by v-Judy** [comment] 2024-02-22 02:50
> @v-Judy can you confirm the issue is not present with the same setup with C# DevKit 1.4.2? 

This issue does not repro on the same setup with C# DevKit 1.4.2.

**Closed** 2024-02-22 06:18 UTC
Labels: bug, needs-triage
