### ISSUE TITLE
SDK did not generate a binding redirection for System.Runtime.CompilerServices.Unsafe

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/msbuild#7702] opened 2022-06-11 18:12 UTC
### Describe the bug

.NET SDK did not generate a binding redirection for System.Runtime.CompilerServices.Unsafe, in a project that targets .NET Framework 4.7.2 and references Microsoft.Extensions.Primitives 2.1.6.

### To Reproduce

Unify.csproj:

```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>exe</OutputType>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="2.1.6" />
  </ItemGroup>

</Project>
```

Program.cs:

```C#
using System;

namespace Unify
{
    class Program
    {
        static void Main() {
            _ = "hello".AsSpan().Slice(2, 3);
        }
    }
}
```

### Exceptions (if any)

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.MemoryExtensions.AsSpan(String text)
   at Unify.Program.Main() in C:\Projects\Kalle\Unify\Program.cs:line 8
```

### Further technical details

Microsoft.Extensions.Primitives/2.1.6 is the latest version of this package in the 2.1.\* series, which is supported for [ASP.NET Core 2.1 on .NET Framework](https://dotnet.microsoft.com/en-us/platform/support/policy/aspnetcore-2.1).

In the `bin\Debug\net472` directory:

* Microsoft.Extensions.Primitives.dll is `Microsoft.Extensions.Primitives, Version=2.1.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60` from the "Microsoft.Extensions.Primitives/2.1.6" package. On net472, this package depends on System.Memory (>= 4.5.1) and System.Runtime.CompilerServices.Unsafe (>= 4.5.2). The assembly depends on netstandard 2.0.0.0, System.Memory 4.0.1.0, and System.Runtime.CompilerServices.Unsafe 4.0.4.1.
* System.Memory.dll is `System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51` from the "System.Memory/4.5.1" package. On net472, this package depends on System.Buffers (>= 4.4.0), System.Numerics.Vectors (>= 4.4.0), and System.Runtime.CompilerServices.Unsafe (>= 4.5.0). The assembly depends on netstandard 2.0.0.0, System.Numerics.Vectors 4.1.3.0, System.Runtime.CompilerServices.Unsafe 4.0.4.0 ⚠, and System.Buffers 4.0.2.0.
* System.Buffers.dll is `System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51` from the "System.Buffers/4.4.0" package. On net472, this package does not depend on any packages. The assembly depends on netstandard 2.0.0.0.
* System.Numerics.Vectors.dll is `System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a` from the "System.Numerics.Vectors/4.4.0" package.  On net472, this package does not depend on any packages. The assembly depends on mscorlib 4.0.0.0 and System.Numerics 4.0.0.0.
* System.Runtime.CompilerServices.Unsafe.dll is `System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a` ⚠ from the "System.Runtime.CompilerServices.Unsafe/4.5.2" package. On net472, this package does not depend on any packages. The assembly depends on System.Runtime 4.0.0.0.

System.Memory.dll thus depends on System.Runtime.CompilerServices.Unsafe 4.0.4.0, but the directory contains System.Runtime.CompilerServices.Unsafe 4.0.4.1, which is a different version. .NET SDK should have generated a binding redirection for this, but it did not.

```
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.300
 Commit:    8473146e7d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.300\

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  2.1.526 [C:\Program Files\dotnet\sdk]
  6.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

No IDE.

**Comment by Forgind** [comment] 2022-06-15 23:42
Small note for reproducing this:
Build passes. Running Unify.exe afterwards (no arguments) failed.

**Comment by Forgind** [comment] 2022-06-16 00:38
I _think_ this is secretly a problem with Microsoft.Extensions.Primitives and not with MSBuild? I was trying to debug into this, and it appears we're finding that Microsoft.Extensions.Primitives has no dependencies...because it's externally resolved, and the external resolution claimed there were no dependencies. I don't know what external thing claimed that it has no dependencies, but that sounds it's probably the source of this?

I went a bit further and checked what happened if I set the property FindDependenciesOfExternallyResolvedReferences to true, and it successfully resolved System.Runtime.CompilerServices.Unsafe version 4.0.4.1—against expectation if it needs 4.0.4.0. That package appears to reference (both directly and indirectly) 4.0.4.1, so there's no way RAR could figure out that it needs 4.0.4.0 from what I've seen.

I almost wonder if there's something else that references S.R.CS.U 4.0.4.0? In any case, I don't think this is an MSBuild bug.

**Comment by baronfel** [comment] 2022-06-16 02:50
Can you clarify what you mean by 'externally resolved'? I think that has a precise meaning here that I don't want to infer.

What would we need to discover in order to point to the authoring of that package as incorrect?

**Comment by KalleOlaviNiemitalo** [comment] 2022-06-16 04:13
> I almost wonder if there's something else that references S.R.CS.U 4.0.4.0?

The System.Memory 4.0.1.0 assembly references System.Runtime.CompilerServices.Unsafe 4.0.4.0. Do you mean something other than that?

**Comment by KalleOlaviNiemitalo** [comment] 2022-06-16 04:29
> what happened if I set the property FindDependenciesOfExternallyResolvedReferences to true

The log I posted shows that the ResolveAssemblyReferences task did already set FindDependenciesOfExternallyResolvedReferences=true.

<https://github.com/dotnet/msbuild/blob/41abc5629965e3f9e41f1e67fdf78345c0c5cc4b/src/Tasks/Microsoft.Common.CurrentVersion.targets#L2292-L2300>

**Comment by KalleOlaviNiemitalo** [comment] 2022-06-16 06:43
MSBuild log section for the [ResolvePackageAssets target in Microsoft.PackageDependencyResolution.targets](https://github.com/dotnet/sdk/blob/ac00abef032d4d576a844d7f1287119a9d20166e/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.PackageDependencyResolution.targets#L231-L310):

```
23:31:28.403   1:7>Target "ResolvePackageAssets: (TargetId:65)" in file "C:\Program Files\dotnet\sdk\6.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets" from project "C:\Users\WDAGUtilityAccount\Unify\Unify.csproj" (target "ResolveLockFileReferences" depends on it):
                   Set Property: UseAppHostFromAssetsFile=true
                   Using "ResolvePackageAssets" task from assembly "C:\Program Files\dotnet\sdk\6.0.300\Sdks\Microsoft.NET.Sdk\targets\..\tools\net6.0\Microsoft.NET.Build.Tasks.dll".
                   Task "ResolvePackageAssets" (TaskId:46)
                     Task Parameter:EmitAssetsLogMessages=True (TaskId:46)
                     Task Parameter:MarkPackageReferencesAsExternallyResolved=True (TaskId:46)
                     Task Parameter:
                         PackageReferences=
                             Microsoft.Extensions.Primitives
                                     Version=2.1.6 (TaskId:46)
                     Task Parameter:ProjectLanguage=C# (TaskId:46)
                     Task Parameter:TargetFramework=net472 (TaskId:46)
                     Task Parameter:ProjectAssetsCacheFile=C:\Users\WDAGUtilityAccount\Unify\obj\Debug\net472\Unify.assets.cache (TaskId:46)
                     Task Parameter:ProjectPath=C:\Users\WDAGUtilityAccount\Unify\Unify.csproj (TaskId:46)
                     Task Parameter:DotNetAppHostExecutableNameWithoutExtension=apphost (TaskId:46)
                     Task Parameter:RuntimeIdentifier=win7-x86 (TaskId:46)
                     Task Parameter:ProjectAssetsFile=C:\Users\WDAGUtilityAccount\Unify\obj\project.assets.json (TaskId:46)
                     Task Parameter:CompilerApiVersion=roslyn4.2 (TaskId:46)
                     Output Item(s): 
                         ResolvedFrameworkAssemblies=
                             System.Numerics
                                     NuGetIsFrameworkReference=true
                                     NuGetPackageId=System.Numerics.Vectors
                                     NuGetPackageVersion=4.4.0
                                     NuGetSourceType=Package
                                     Pack=false
                                     Private=false
                             mscorlib
                                     NuGetIsFrameworkReference=true
                                     NuGetPackageId=System.Numerics.Vectors
                                     NuGetPackageVersion=4.4.0
                                     NuGetSourceType=Package
                                     Pack=false
                                     Private=false (TaskId:46)
                     Output Item(s): 
                         RuntimeCopyLocalItems=
                             C:\Users\WDAGUtilityAccount\.nuget\packages\microsoft.extensions.primitives\2.1.6\lib\netstandard2.0\Microsoft.Extensions.Primitives.dll
                                     AssetType=runtime
                                     CopyLocal=true
                                     DestinationSubPath=Microsoft.Extensions.Primitives.dll
                                     NuGetPackageId=Microsoft.Extensions.Primitives
                                     NuGetPackageVersion=2.1.6
                                     PathInPackage=lib/netstandard2.0/Microsoft.Extensions.Primitives.dll
                             C:\Users\WDAGUtilityAccount\.nuget\packages\system.buffers\4.4.0\lib\netstandard2.0\System.Buffers.dll
                                     AssetType=runtime
                                     CopyLocal=true
                                     DestinationSubPath=System.Buffers.dll
                                     NuGetPackageId=System.Buffers
                                     NuGetPackageVersion=4.4.0
                                     PathInPackage=lib/netstandard2.0/System.Buffers.dll
                             C:\Users\WDAGUtilityAccount\.nuget\packages\system.memory\4.5.1\lib\netstandard2.0\System.Memory.dll
                                     AssetType=runtime
                                     CopyLocal=true
                                     DestinationSubPath=System.Memory.dll
                                     NuGetPackageId=System.Memory
                                     NuGetPackageVersion=4.5.1
                                     PathInPackage=lib/netstandard2.0/System.Memory.dll
                             C:\Users\WDAGUtilityAccount\.nuget\packages\system.numerics.vectors\4.4.0\lib\net46\System.Numerics.Vectors.dll
                                     AssetType=runtime
                                     CopyLocal=true
                                     DestinationSubPath=System.Numerics.Vectors.dll
                                     NuGetPackageId=System.Numerics.Vectors
                                     NuGetPackageVersion=4.4.0
                                     PathInPackage=lib/net46/System.Numerics.Vectors.dll
                             C:\Users\WDAGUtilityAccount\.nuget\packages\system.runtime.compilerservices.unsafe\4.5.2\lib\netstandard2.0\System.Runtime.CompilerServices.Unsafe.dll
                                     AssetType=runtime
                                     CopyLocal=true
                                     DestinationSubPath=System.Runtime.CompilerServices.Unsafe.dll
                                     NuGetPackageId=System.Runtime.CompilerServices.Unsafe
                                     NuGetPackageVersion=4.5.2
                                     PathInPackage=lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll (TaskId:46)
                     Output Item(s): 
                         ResolvedCompileFileDefinitions=
                             C:\Users\WDAGUtilityAccount\.nuget\packages\microsoft.extensions.primitives\2.1.6\lib\netstandard2.0\Microsoft.Extensions.Primitives.dll
                                     ExternallyResolved=true
                                     HintPath=C:\Users\WDAGUtilityAccount\.nuget\packages\microsoft.extensions.primitives\2.1.6\lib\netstandard2.0\Microsoft.Extensions.Primitives.dll
                                     NuGetPackageId=Microsoft.Extensions.Primitives
                                     NuGetPackageVersion=2.1.6
                                     NuGetSourceType=Package
                                     PathInPackage=lib/netstandard2.0/Microsoft.Extensions.Primitives.dll
                                     Private=false
                             C:\Users\WDAGUtilityAccount\.nuget\packages\system.memory\4.5.1\ref\netstandard2.0\System.Memory.dll
                                     ExternallyResolved=true
                                     HintPath=C:\Users\WDAGUtilityAccount\.nuget\packages\system.memory\4.5.1\ref\netstandard2.0\System.Memory.dll
                                     NuGetPackageId=System.Memory
                                     NuGetPackageVersion=4.5.1
                                     NuGetSourceType=Package
                                     PathInPackage=ref/netstandard2.0/System.Memory.dll
                                     Private=false
                             C:\Users\WDAGUtilityAccount\.nuget\packages\system.runtime.compilerservices.unsafe\4.5.2\ref\netstandard2.0\System.Runtime.CompilerServices.Unsafe.dll
                                     ExternallyResolved=true
                                     HintPath=C:\Users\WDAGUtilityAccount\.nuget\packages\system.runtime.compilerservices.unsafe\4.5.2\ref\netstandard2.0\System.Runtime.CompilerServices.Unsafe.dll
                                     NuGetPackageId=System.Runtime.CompilerServices.Unsafe
                                     NuGetPackageVersion=4.5.2
                                     NuGetSourceType=Package
                                     PathInPackage=ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll
                                     Private=false (TaskId:46)
                     Output Item(s): AssetsFilePackageFolder=C:\Users\WDAGUtilityAccount\.nuget\packages\ (TaskId:46)
                     Output Item(s): 
                         PackageDependencies=
                             Microsoft.Extensions.Primitives
                             Microsoft.NETFramework.ReferenceAssemblies
                             Microsoft.NETFramework.ReferenceAssemblies.net472
                             System.Buffers
                             System.Memory
                             System.Numerics.Vectors
                             System.Runtime.CompilerServices.Unsafe (TaskId:46)
                   Done executing task "ResolvePackageAssets". (TaskId:46)
23:31:28.684   1:7>Done building target "ResolvePackageAssets" in project "Unify.csproj".: (TargetId:65)
```

The [ResolveLockFileRefences target in Microsoft.PackageDependencyResolution.targets](https://github.com/dotnet/sdk/blob/ac00abef032d4d576a844d7f1287119a9d20166e/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.PackageDependencyResolution.targets#L432-L482) then copies the ResolvedCompileFileDefinitions items to Reference items:

```
23:31:28.686   1:7>Target "ResolveLockFileReferences: (TargetId:67)" in file "C:\Program Files\dotnet\sdk\6.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets" from project "C:\Users\WDAGUtilityAccount\Unify\Unify.csproj" (target "ResolvePackageDependenciesForBuild" depends on it):
                   Using "JoinItems" task from assembly "C:\Program Files\dotnet\sdk\6.0.300\Sdks\Microsoft.NET.Sdk\targets\..\tools\net6.0\Microsoft.NET.Build.Tasks.dll".
                   Task "JoinItems" (TaskId:48)
                     Task Parameter:RightMetadata=* (TaskId:48)
                     Task Parameter:
                         Left=
                             C:\Users\WDAGUtilityAccount\.nuget\packages\microsoft.extensions.primitives\2.1.6\lib\netstandard2.0\Microsoft.Extensions.Primitives.dll
                                     ExternallyResolved=true
                                     HintPath=C:\Users\WDAGUtilityAccount\.nuget\packages\microsoft.extensions.primitives\2.1.6\lib\netstandard2.0\Microsoft.Extensions.Primitives.dll
                                     NuGetPackageId=Microsoft.Extensions.Primitives
                                     NuGetPackageVersion=2.1.6
                                     NuGetSourceType=Package
                                     PathInPackage=lib/netstandard2.0/Microsoft.Extensions.Primitives.dll
                                     Private=false
                             C:\Users\WDAGUtilityAccount\.nuget\packages\system.memory\4.5.1\ref\netstandard2.0\System.Memory.dll
                                     ExternallyResolved=true
                                     HintPath=C:\Users\WDAGUtilityAccount\.nuget\packages\system.memory\4.5.1\ref\netstandard2.0\System.Memory.dll
                                     NuGetPackageId=System.Memory
                                     NuGetPackageVersion=4.5.1
                                     NuGetSourceType=Package
                                     PathInPackage=ref/netstandard2.0/System.Memory.dll
                                     Private=false
                             C:\Users\WDAGUtilityAccount\.nuget\packages\system.runtime.compilerservices.unsafe\4.5.2\ref\netstandard2.0\System.Runtime.CompilerServices.Unsafe.dll
                                     ExternallyResolved=true
                                     HintPath=C:\Users\WDAGUtilityAccount\.nuget\packages\system.runtime.compilerservices.unsafe\4.5.2\ref\netstandard2.0\System.Runtime.CompilerServices.Unsafe.dll
                                     NuGetPackageId=System.Runtime.CompilerServices.Unsafe
                                     NuGetPackageVersion=4.5.2
                                     NuGetSourceType=Package
                                     PathInPackage=ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll
                                     Private=false (TaskId:48)
                     Task Parameter:LeftMetadata=* (TaskId:48)
                     Task Parameter:
                         Right=
                             System
                                     IsImplicitlyDefined=true
                                     Pack=false
                             System.Data
                                     IsImplicitlyDefined=true
                                     Pack=false
                             System.Drawing
                                     IsImplicitlyDefined=true
                                     Pack=false
                             System.Xml
                                     IsImplicitlyDefined=true
                                     Pack=false
                             System.Core
                                     IsImplicitlyDefined=true
                                     Pack=false
                             System.Runtime.Serialization
                                     IsImplicitlyDefined=true
                                     Pack=false
                             System.Xml.Linq
                                     IsImplicitlyDefined=true
                                     Pack=false
                             System.Numerics
                                     IsImplicitlyDefined=true
                                     Pack=false
                             System.IO.Compression.FileSystem
                                     IsImplicitlyDefined=true
                                     Pack=false
                             mscorlib
                                     Pack=false (TaskId:48)
                     Task Parameter:LeftKey=FileName (TaskId:48)
                   Done executing task "JoinItems". (TaskId:48)
                   Added Item(s): 
                       ResolvedCompileFileDefinitionsToAdd=
                           C:\Users\WDAGUtilityAccount\.nuget\packages\microsoft.extensions.primitives\2.1.6\lib\netstandard2.0\Microsoft.Extensions.Primitives.dll
                                   ExternallyResolved=true
                                   HintPath=C:\Users\WDAGUtilityAccount\.nuget\packages\microsoft.extensions.primitives\2.1.6\lib\netstandard2.0\Microsoft.Extensions.Primitives.dll
                                   NuGetPackageId=Microsoft.Extensions.Primitives
                                   NuGetPackageVersion=2.1.6
                                   NuGetSourceType=Package
                                   PathInPackage=lib/netstandard2.0/Microsoft.Extensions.Primitives.dll
                                   Private=false
                           C:\Users\WDAGUtilityAccount\.nuget\packages\system.memory\4.5.1\ref\netstandard2.0\System.Memory.dll
                                   ExternallyResolved=true
                                   HintPath=C:\Users\WDAGUtilityAccount\.nuget\packages\system.memory\4.5.1\ref\netstandard2.0\System.Memory.dll
                                   NuGetPackageId=System.Memory
                                   NuGetPackageVersion=4.5.1
                                   NuGetSourceType=Package
                                   PathInPackage=ref/netstandard2.0/System.Memory.dll
                                   Private=false
                           C:\Users\WDAGUtilityAccount\.nuget\packages\system.runtime.compilerservices.unsafe\4.5.2\ref\netstandard2.0\System.Runtime.CompilerServices.Unsafe.dll
                                   ExternallyResolved=true
                                   HintPath=C:\Users\WDAGUtilityAccount\.nuget\packages\system.runtime.compilerservices.unsafe\4.5.2\ref\netstandard2.0\System.Runtime.CompilerServices.Unsafe.dll
                                   NuGetPackageId=System.Runtime.CompilerServices.Unsafe
                                   NuGetPackageVersion=4.5.2
                                   NuGetSourceType=Package
                                   PathInPackage=ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll
                                   Private=false
                   Added Item(s): 
                       Reference=
                           C:\Users\WDAGUtilityAccount\.nuget\packages\microsoft.extensions.primitives\2.1.6\lib\netstandard2.0\Microsoft.Extensions.Primitives.dll
                                   ExternallyResolved=true
                                   HintPath=C:\Users\WDAGUtilityAccount\.nuget\packages\microsoft.extensions.primitives\2.1.6\lib\netstandard2.0\Microsoft.Extensions.Primitives.dll
                                   NuGetPackageId=Microsoft.Extensions.Primitives
                                   NuGetPackageVersion=2.1.6
                                   NuGetSourceType=Package
                                   PathInPackage=lib/netstandard2.0/Microsoft.Extensions.Primitives.dll
                                   Private=false
                           C:\Users\WDAGUtilityAccount\.nuget\packages\system.memory\4.5.1\ref\netstandard2.0\System.Memory.dll
                                   ExternallyResolved=true
                                   HintPath=C:\Users\WDAGUtilityAccount\.nuget\packages\system.memory\4.5.1\ref\netstandard2.0\System.Memory.dll
                                   NuGetPackageId=System.Memory
                                   NuGetPackageVersion=4.5.1
                                   NuGetSourceType=Package
                                   PathInPackage=ref/netstandard2.0/System.Memory.dll
                                   Private=false
                           C:\Users\WDAGUtilityAccount\.nuget\packages\system.runtime.compilerservices.unsafe\4.5.2\ref\netstandard2.0\System.Runtime.CompilerServices.Unsafe.dll
                                   ExternallyResolved=true
                                   HintPath=C:\Users\WDAGUtilityAccount\.nuget\packages\system.runtime.compilerservices.unsafe\4.5.2\ref\netstandard2.0\System.Runtime.CompilerServices.Unsafe.dll
                                   NuGetPackageId=System.Runtime.CompilerServices.Unsafe
                                   NuGetPackageVersion=4.5.2
                                   NuGetSourceType=Package
                                   PathInPackage=ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll
                                   Private=false
23:31:28.688   1:7>Done building target "ResolveLockFileReferences" in project "Unify.csproj".: (TargetId:67)
```

I think the ExternallyResolved=true metadata in the Reference item for System.Memory.dll means that, because this assembly came from the NuGet package System.Memory/4.5.1, NuGet has also added RuntimeCopyLocalItems items for assemblies from the packages on which that package depends, so the ResolveAssemblyReferences target doesn't need to look inside System.Memory.dll to find the names of additional assemblies that it would have to copy to the output directory. However, because AutoGenerateBindingRedirects is true, the ResolveAssemblyReferences target still needs to look inside System.Memory.dll to decide whether it needs a binding redirection.

**Comment by Forgind** [comment] 2022-06-16 17:54
Ok, so this is the biggest source of my confusion. Looking at System.Memory, 4.0.1.0 in ilspy, it claims to reference S.R.CS.U 4.0.4.1:
<img width="537" alt="image" src="https://user-images.githubusercontent.com/12969783/174134409-1d3f1958-81c2-47bb-ab61-bc4fdbfe0379.png">
Looking in NuGet package explorer agrees:
<img width="650" alt="image" src="https://user-images.githubusercontent.com/12969783/174134733-4dcfb816-1a9b-41a6-b0a5-ebbb963ad2ae.png">

The trick is that there are two versions of System.Memory (4.5.1 and 4.5.2) that are both 4.0.1.0 and reference different System.Runtime.CompilerServices.Unsafe versions. My next question is whether this repros with any not-bad System.Memory versions.

**Comment by KalleOlaviNiemitalo** [comment] 2022-06-16 18:12
System.Memory/4.5.0 contains `lib/netstandard2.0/System.Memory.dll` assembly version 4.0.1.0 and references System.Runtime.CompilerServices.Unsafe 4.0.4.0.

System.Memory/4.5.1 contains `lib/netstandard2.0/System.Memory.dll` assembly version 4.0.1.0 and references System.Runtime.CompilerServices.Unsafe 4.0.4.0.

System.Memory/4.5.2 I don't have on this computer, so it should not affect the build.

System.Memory/4.5.3 contains `lib/netstandard2.0/System.Memory.dll` assembly version 4.0.1.1 and references System.Runtime.CompilerServices.Unsafe 4.0.4.1. AFAIK, this version was not used for the build.

Are you seeing the same references that I listed above?

**Comment by Forgind** [comment] 2022-06-16 18:31
4.5.2 is the one that's version 4.0.1.0 but references 4.0.4.1.

I turned on fusion logging for the build:
<img width="290" alt="image" src="https://user-images.githubusercontent.com/12969783/174140772-e99c1e9c-36fe-4bd9-ba57-821d14f90747.png">
so it doesn't seem to be even looking for 4.0.1.0, but it does look for two other System.Memory versions. Not sure why it's interested in 4.0.1.2.

**Comment by Forgind** [comment] 2022-06-16 18:42
I think it downloads a version of System.Memory if necessary? From the fusion log again:
`LOG: Attempting download of new URL file:///C:/Users/forgind/Desktop/Archives/Bug-specific/7702/bin/Debug/net472/System.Memory.DLL.`

I tried calling Assembly.LoadFrom on that, and it returned System.Memory, version=6.0.0.0. No idea where that came from.

**Comment by KalleOlaviNiemitalo** [comment] 2022-06-16 18:48
Do you mean the System.Memory assembly used by MSBuild itself is interfering with ResolveAssemblyReference?

**Comment by Forgind** [comment] 2022-06-16 18:52
I don't think that's the problem. The 4.0.1.2 version didn't interfere with loading the 4.0.1.1 version, and I think the 6.0.0.0 thing is a lie, and it's really 4.0.1.0.

**Comment by Forgind** [comment] 2022-06-16 19:21
I traced this a bit further. ReferenceTable.FindAssociatedFiles calls something called FindDependenciesAndScatterFiles on the System.Memory 4.5.1 reference. That calls GetUnifiedAssemblyMetadata, which eventually calls AssemblyInformation.GetAssemblyMetadata and uses that to extract dependencies. That tries to make a temporary AssemblyInformation object. That makes a lot of native calls I don't understand.

First, it uses NativeMethods.IMetaDataDispenser.OpenScope to create _assemblyImport then uses _assemblyImport.EnumAssemblyRefs to get its dependencies. I have no idea how that part works. I think it has something to do with com? In any case, that call is only returning one reference: to netstandard2.0. We then apparently assume System.Memory doesn't have any other dependencies? I think I'm out of my depth on that part, though.

**Comment by KalleOlaviNiemitalo** [comment] 2022-06-16 19:39
This issue also reproduces with `dotnet build` of .NET SDK 6.0.301. In that, I assume AssemblyInformation is built with FEATURE_ASSEMBLYLOADCONTEXT and does not use IMetaDataDispenser.

What is the path of the System.Memory.dll file that it examines?

**Comment by Forgind** [comment] 2022-06-16 19:46
C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.memory\4.5.1\ref\netstandard2.0\System.Memory.dll

**Comment by KalleOlaviNiemitalo** [comment] 2022-06-16 20:15
The later package versions System.Memory/4.5.2, System.Memory/4.5.3, System.Memory/4.5.4, and System.Memory/4.5.5 do not contain any reference assemblies; only an empty `ref\netcoreapp2.1\_._` file. System.Memory/4.5.2 was built from <https://github.com/dotnet/corefx/tree/99ce22c306b07f99ddae60f443d23a983ae78f7b/src/System.Memory> and there was a related pull request… <https://github.com/dotnet/corefx/pull/33254>

**Comment by baronfel** [comment] 2022-06-16 20:17
It's due to the difference in assets between compile time and runtime assets. If you look in a project.assets.json for a project, you'll see that dependencies for that project have difference categories of assets:

```json
"System.Buffers/4.5.1": {
        "type": "package",
        "compile": {
          "ref/netstandard2.0/System.Buffers.dll": {}
        },
        "runtime": {
          "lib/netstandard2.0/System.Buffers.dll": {}
        }
      },
```

During compile time, any "compile" assets are passed to the compiler. For assemblies that provide ref assemblies the `ref` assemblies are the "compile" assets. The "runtime" assets are the full assemblies.  

I think the root of the problem is the ref assembly being incorrect in terms of dependencies. That's a really old version - I wonder if there's any chance of it being fixed. @richlander is this a 'you' question?

**Comment by Forgind** [comment] 2022-06-16 20:18
I verified that if you use the lib/ version with the correct list of dependencies, Unify.exe works!

**Comment by baronfel** [comment] 2022-06-16 20:20
@KalleOlaviNiemitalo based on the last comment in dotnet/sdk#2547, is it possible to update to a more recent version of the triggering dependency?

**Comment by KalleOlaviNiemitalo** [comment] 2022-06-16 20:21
Yes, I can update.
This feels like quite a trap though, something that I will have to consider if I make NuGet packages that include reference assemblies.

**Comment by baronfel** [comment] 2022-06-16 20:25
I'm inclined to agree - it was very surprising to me to read the logic behind not exposing the runtime dependencies in ref assemblies. I don't suppose dropping the full framework support you have is an option either? (mostly kidding)

**Comment by KalleOlaviNiemitalo** [comment] 2022-06-16 20:34
<https://github.com/dotnet/roslyn/blob/e4d1ce6e8a244f68ac87929b0a1c09c6c39b4cdb/docs/features/refout.md> says it's by design that reference assemblies don't include all the references. Well then, I think it's a mistake that the ResolveAssemblyReferences target looks at metadata of reference assemblies when it is asked to suggest binding redirections.

**Comment by KalleOlaviNiemitalo** [comment] 2022-06-17 10:30
Should this be closed as a duplicate of <https://github.com/dotnet/sdk/issues/2547>, or is there some fix that can be done at the MSBuild side? The ResolveAssemblyReferences target and the ResolveAssemblyReference task are defined in this repo.

**Comment by Forgind** [comment] 2022-06-17 16:43
That sounds correct to me. It doesn't sound like this was originally designed in what I would think is the most intuitive way, but that ship has sailed, so I don't think we can change that. Working within that structure, RAR is doing what is correct, so I don't think it should be changed.

**Comment by Forgind** [comment] 2022-06-17 16:44
Duplicate of dotnet/sdk#2547

**Closed by Forgind** 2022-06-17 16:44 UTC
Labels: Task: Resolve Assembly References (RAR), initial-investigation
