### ISSUE TITLE
resources relative above the project generate invalid namespace

### ISSUE THREAD

**Issue by trivalik** [dotnet/msbuild#6290] opened 2021-03-23 13:39 UTC
### Issue Description
Using resx files which are above current csproj are not working, the will add to namespace the relative dots "..".

### Steps to Reproduce

* build attached project in VS2019 16.9.2, if not fail, use "Run Custom Tool" on resx
[ResXGenAboveProject.zip](https://github.com/dotnet/msbuild/files/6190033/ResXGenAboveProject.zip)

### Expected Behavior

Namespace is generated which can be used, best would be same as the key on creating ResourceManager, in provided example "WindowsFormsDependentUponConventionTest.Properties".

### Actual Behavior
Namespace in resources.designer.cs with .. is generated:
`namespace WindowsFormsDependentUponConventionTest....Resources {`

**Comment by BenVillalobos** [comment] 2021-03-31 23:40
I'm able to reproduce your issue on 16.10 preview.

Steps:
1. Download repro
2. Build project
3. Right click on the resx file and click "Run Custom Tool"
4. See the generated designer file have `namespace WindowsFormsDependentUponConventionTest....Resources`.

@ryanbrandenburg we've chatted a while back about resources as they relate to asp.net, does this ring any bells for you? I recall this type of folder structure not being supported, not sure if you have any idea for winforms.

Notes to self:
Deploy a bootstrapped build and debug into msbuild when Run Custom Tool is called.

**Comment by BenVillalobos** [comment] 2021-04-01 20:53
Debugging into the msbuild process after hitting "Run Custom Tool", this is the list of targets that run:
![image](https://user-images.githubusercontent.com/4691428/113352677-773a1180-92f1-11eb-822a-fa4030628cfe.png)
 /cc: @davkean does this look like a standard design time build? also do you know what runs when "Run Custom Tool" is called? first pass doesn't seem like MSBuild controls that.

**Comment by davkean** [comment] 2021-04-01 21:24
Run Custom Tool calls a single file generator  in the RESX case and not targets. Those targets will be called _after_ the generation of the file.

We'd never previously allowed it to run against a linked file so looks like that restriction was removed for whatever reason but the generation was not fixed. @trivalik The easiest way to keep track of this, is via Help -> Send Feedback -> Report a Problem, otherwise, we can move this bug internally.

**Comment by BenVillalobos** [comment] 2021-04-01 21:34
@davkean thanks! closing this issue. See davkean's suggestion on reporting this problem.

**Closed** 2021-04-05 22:56 UTC
Labels: Initial Investigation, bug
