### ISSUE TITLE
[NETSDKE2E]With NET 9 alpha SDK installed, duplicate "Build succeeded" info displays in new terminal logger output in CLI.

### ISSUE THREAD

**Issue by vdanche** [dotnet/msbuild#9614] opened 2024-01-09 08:25 UTC
### Issue Description

With NET 9 alpha SDK installed, duplicate "Build succeeded" info displays in new terminal logger output in CLI.

### Steps to Reproduce

Affect build:
.NET 9.0.100-alpha.1.24058.10(runtime-9.0.0-alpha.1.24057.2) from [dotnet/installer: .NET SDK Installer (github.com)](https://github.com/dotnet/installer)
Affected Product Language:

Steps to reproduce:
1. dotnet new tool-manifest -o test
2. cd to the directory and then run "dotnet tool install dotnet-ef"
3. Create a new project(dotnet new console) and run dotnet ef dbcontext list

### Expected Behavior

the output message in step3 for old terminal logger output is displayed as below:
![image](https://github.com/dotnet/msbuild/assets/65637796/c7ab5b79-cc5a-43fc-b684-55d349d90d9a)

### Actual Behavior

Actual Result:
for new terminal logger output, it displayed as below, duplicate "Build succeeded" info displays
![image](https://github.com/dotnet/msbuild/assets/65637796/0e9740e6-a836-4fb3-a2ba-637ed0918743)

dotnet --info:
![image](https://github.com/dotnet/msbuild/assets/65637796/c7b584bc-7085-4fa6-9c6d-e2d4abdb2df3)

**Comment by vdanche** [comment] 2024-01-09 08:30
Additionally, this issue also happens with below scenario.
![image](https://github.com/dotnet/msbuild/assets/65637796/60566994-2641-426e-883d-30069a4d9ffa)

create a project e.g dotnet new wpf
publish project: dotnet publish --framework net9.0-windows

Note:
It does not happen when publish with "dotnet publish -r win-x64 --self-contained"
![image](https://github.com/dotnet/msbuild/assets/65637796/fbf60cca-895a-405d-bd93-c9a9a13c90b6)

**Comment by v-ainigao** [comment] 2024-01-09 08:54
This problem is also reproduced on Win ARM64.
![image](https://github.com/dotnet/msbuild/assets/106054229/844d84a3-1cfd-4e6f-956b-04a16569e148)

**Comment by v-xiaofchen** [comment] 2024-01-09 09:50
This problem is also reproduced on Win ARM64.

**Comment by baronfel** [comment] 2024-01-09 13:52
My guess is that the ef tool is doing one or more builds behind the scene as part of its internal logic, and these inner builds are what we are seeing here. We may need to work with that team to change the way they involve build to not be as visible to end users.

**Comment by vdanche** [comment] 2024-01-10 02:33
> Additionally, this issue also happens with below scenario. ![image](https://private-user-images.githubusercontent.com/65637796/295144228-60566994-2641-426e-883d-30069a4d9ffa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NTQyNjIsIm5iZiI6MTcwNDg1Mzk2MiwicGF0aCI6Ii82NTYzNzc5Ni8yOTUxNDQyMjgtNjA1NjY5OTQtMjY0MS00MjZlLTg4M2QtMzAwNjlhNGQ5ZmZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDAyMzI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MTg1YzIyMTE1YWE5MDBhNWU3NTUyYTY3ZDIyMTA5Y2M1NGU4YzMwODM0NzQwZTBjNGRlN2FkZjczNDYwMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YfStiA1tYk35tw9t17f4HjXtzBsP-z5WLlolMKeIFOU)
> 
> create a project e.g dotnet new wpf publish project: dotnet publish --framework net9.0-windows
> 
> Note: It does not happen when publish with "dotnet publish -r win-x64 --self-contained" ![image](https://private-user-images.githubusercontent.com/65637796/295144812-fbf60cca-895a-405d-bd93-c9a9a13c90b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NTQyNjIsIm5iZiI6MTcwNDg1Mzk2MiwicGF0aCI6Ii82NTYzNzc5Ni8yOTUxNDQ4MTItZmJmNjBjY2EtODk1YS00MDVkLWJkOTMtYzlhOWExM2M5MGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDAyMzI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmMGNkOTBkYzQ5YjM5ZThhYTI4Njc4YjZiMGZmOTZjMzBlYmI2ODAxZTI2NjZiZjk4Zjc2MDZkNWYwNjc3ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F-1gkHgZP8S7-j2OuzR52R-DLqPoPZX5W9Ur6ZzbJos)

@baronfel for this scenario, duplicate build succeeded info also happens

**Comment by baronfel** [comment] 2024-01-10 15:19
I looked at the `ef` case specifically, and they trigger builds of projects via the .NET CLI. The command line they construct is [here](https://github.com/dotnet/efcore/blob/main/src/dotnet-ef/Project.cs#L139-L167):

```
dotnet build <project file name> [optional TFM] [optional Configuration] [optional RID] /verbosity:quiet /nologo /p:PublishAot=false
```

Does TL respect `/verbosity:quiet` (aka 'silent')? If not we may want to consider making it do so.

**Comment by rainersigwald** [comment] 2024-01-10 15:21
> Does TL respect `/verbosity:quiet`

Not today, but we probably want that for `dotnet test` too.

**Comment by baronfel** [comment] 2024-01-10 15:23
Oh geez - the WPF build thing may be the same root problem. WPF does the inner build to compile the XAML, right?

**Comment by ChenhuiYuan01** [comment] 2024-01-11 09:28
This problem is also reproduced on Linux.
![Screenshot 2024-01-11 172630](https://github.com/dotnet/msbuild/assets/92560562/5acae0c6-9df1-4b87-9727-63de3063e7d7)

**Comment by JanKrivanek** [comment] 2024-02-23 11:59
So the WPF case is actually related to publishing and it is a double invocation of msbuild as well.

$ dotnet publish -tl --framework net8.0-windows
  --> -maxcpucount -verbosity:m **-target:Restore --property:_IsPublishing=true** -property:Configuration=Release -tl -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\8.0.200-preview.23620.12\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\8.0.200-preview.23620.12\dotnet.dll
 --> -maxcpucount -verbosity:m -nologo **-target:Publish --property:_IsPublishing=true** -property:TargetFramework=net8.0-windows -property:Configuration=Release -tl -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\8.0.200-preview.23620.12\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\8.0.200-preview.23620.12\dotnet.dll

It's given by the fact that [`PublishCommand`](https://github.com/dotnet/sdk/blob/3075c3bc8d8aa4e0ffcf2945459ef2ee383e3ae0/src/Cli/dotnet/commands/dotnet-publish/Program.cs#L11) actually extends `RestoreCommand` and hence the execution leads to 2 separate msbuild invocations:

https://github.com/dotnet/sdk/blob/3075c3bc8d8aa4e0ffcf2945459ef2ee383e3ae0/src/Cli/dotnet/commands/RestoringCommand.cs#L93-L111

So I have 2 outstanding questions:

1. Is it expected and desired that publish leads to 2 separate invocations (vs. just specifying `-restore`)? @dsplaisted?
2. In case of any tooling (and specifically our sdk) needs multiple invocations of msbuild - what is the balance between reporting the reality and hiding some of the invocations? @baronfel?

In case of publish - would we want to hide the whole restore call, we can probably append `-tl:false -v:q`?

**Comment by baronfel** [comment] 2024-02-23 13:41
@JanKrivanek I think we discovered the cause and am working on a fix over in https://github.com/dotnet/sdk/pull/38956.

Longer term, it would be useful if there was a way for MSBuild to unset specific properties for the Restore - if that capability existed then we could remove the separate restore code from the SDK entirely.

**Comment by JanKrivanek** [comment] 2024-02-23 13:50
Oh - great timing then :-)

How about the ef case (`dotnet ef dbcontext list`)? It feels 'by design'. TerminalLogger (and logging in general) can be disabled in one of the invocations - but is that really wanted? It sounds like the decision should be in the invoking context, not in msbuild.

**Comment by baronfel** [comment] 2024-02-23 14:06
> It sounds like the decision should be in the invoking context, not in msbuild.

Yes, this is a good rule. The invoking context is very often the SDK, so we need to make it smarter at the minimum.

**Comment by JanKrivanek** [comment] 2024-02-26 16:22
The restore case is going to be fixed by https://github.com/dotnet/sdk/pull/38956

**Comment by vdanche** [comment] 2024-03-07 08:43
In today's build:9.0.100-preview.3.24156.14 SDK，will check on tomorrow's build.
this issue still repro
![image](https://github.com/dotnet/msbuild/assets/65637796/18bbcf90-e3ab-432a-898c-bec65abfebab)

**Comment by vdanche** [comment] 2024-03-13 06:07
@baronfel  @JanKrivanek I see https://github.com/dotnet/sdk/pull/38956 is merged, but this bug still repro after checking on today's build 9.0.100-preview.3.24162.35
1.duplicate build succeed info after running "dotnet publish -f net9.0-windows" for winforms/wpf
![image](https://github.com/dotnet/msbuild/assets/65637796/41520cd2-7a56-4c7b-9f93-181f3bd4bf36)

2. run "dotnet ef dbcontext list"
![image](https://github.com/dotnet/msbuild/assets/65637796/587e2d02-5529-45e0-8728-95bb1e69e545)

**Comment by JanKrivanek** [comment] 2024-03-13 07:25
@vdanche The fix needs SDK side fix (the one merged) and MSBuild side fix (to respect the quiet glag passed by sdk) - that one is tracked under https://github.com/dotnet/msbuild/issues/9654

FYI @MichalPavlik

**Comment by vdanche** [comment] 2024-03-13 07:53
@JanKrivanek Thanks for your clarification. 
you mean, for issue1 (duplicate build succeed info after running "dotnet publish -f net9.0-windows" for winforms/wpf, we need to wait SDK side fix. not sure which version it will be fixed. As current bug is closed, want to know if need to file a new bug to track or only track it in current bug?

for issue2(dotnet ef dbcontext list), we can track https://github.com/dotnet/msbuild/issues/9654(open), right?

**Comment by JanKrivanek** [comment] 2024-03-13 09:01
#9654 should fix both cases actually - as restore/publish now passes quiet flag (after https://github.com/dotnet/sdk/pull/38956) and efcore call to msbuild has that already as well: https://github.com/dotnet/efcore/blob/368737c23224d3771b4db7b169c7bd80630adcdc/src/dotnet-ef/Project.cs#L184-L185


So both should display the status just once - once #9654 fix is created, merged and inserted into sdk - I cannot give any promisses on timing though (beyond it's currently scheduled in our monthly sprint)

**Comment by vdanche** [comment] 2024-03-13 09:30
> So both should display the status just once - once #9654 fix is created, merged and inserted into sdk - I cannot give any promisses on timing though (beyond it's currently scheduled in our monthly sprint)

got it, we'll keep tracking until https://github.com/dotnet/msbuild/issues/9654(open) fix is created, merged and inserted into sdk

**Comment by vdanche** [comment] 2024-04-11 08:29
@JanKrivanek today we found below scenario about dup "Build succeeded" info issue in new terminal logger output in CLI has been fixed on 9.0.100-preview.4.24210.38 SDK
![image](https://github.com/dotnet/msbuild/assets/65637796/1052edc9-e046-481a-a36a-a1a6047684d0)

But dup "Build succeeded" info issue still repro when publish winforms/wpf.
![image](https://github.com/dotnet/msbuild/assets/65637796/9951fee4-da82-4289-8478-711aa5e447c3)

**Comment by JanKrivanek** [comment] 2024-04-11 08:51
@AR-May - can you confirm once the https://github.com/dotnet/msbuild/pull/9810 makes it into the sdk?
(the sdk added `-quiet` flag to the restore derived commands in https://github.com/dotnet/sdk/pull/38956, the MSBuild added respecting that flag for terminal logger in https://github.com/dotnet/msbuild/pull/9810 - so we need that change to be inserted in sdk in order for the symptoms to disappear)

**Comment by AR-May** [comment] 2024-04-12 07:30
@JanKrivanek This has to be the sdk version with our fix: first, it [fixes](https://github.com/dotnet/msbuild/issues/9809#issuecomment-2049208800) some of the bugs related to my PR. Second, enough time went to insert the fix to the sdk and installer repos, I checked and there are recent enough insertions, so the bits have to be propagated. We will need to look what is wrong.

**Comment by JanKrivanek** [comment] 2024-04-12 11:29
@baronfel - the https://github.com/dotnet/sdk/pull/38956 adds the quiet verbosity only to the `getX` invocations leading to the separate restore execution. Thus the scenario here (publish with explicit TFM) is not handled. Should we actually add the quiet flag unconditionally?

On a separate note - we shaould pick up the https://github.com/dotnet/msbuild/issues/8817 as the inability to capture the first binolg wihtout rather user unfriendly approach (breaking the exectution on the process start) is sad here.

**Comment by vdanche** [comment] 2024-04-22 08:48
Checked on 9.0.100-preview.4.24221.5, dup "Build succeeded" info issue still repro when publish project not repro now.
![image](https://github.com/dotnet/msbuild/assets/65637796/a44d8d44-fa5e-4c55-aa1b-1335a6197d95)

**Closed** 2024-04-22 08:52 UTC
Labels: bug, Priority:1, triaged, Area: Terminal Logger
