### ISSUE TITLE
Allow trailing comma in .slnf Json files to match VS

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/msbuild#6371] opened 2021-04-25 04:56 UTC
VS is able to open .slnf files if the Json has a trailing comma.

MSBuild shows an error: 

```
Solution file error MSB5025: Json in solution filter file "C:\AspNetCore\src\Razor\razor.slnf" is incorrectly formatted.
```

See https://github.com/dotnet/aspnetcore/pull/32141 for an example

**Comment by rainersigwald** [comment] 2021-04-26 15:03
Duplicate of #6317

**Closed by rainersigwald** 2021-04-26 15:03 UTC
