### ISSUE TITLE
[Feature Request]: hours/minutes/seconds in build time

### ISSUE THREAD

**Issue by Forgind** [dotnet/msbuild#10446] opened 2024-07-25 18:52 UTC
### Summary

My computer is unfortunately pretty slow, so I get some long builds. Here's the latest example of an incremental build of the dotnet/sdk repo:
![image](https://github.com/user-attachments/assets/f5e48cbd-f7ac-4448-8716-b6d1f4b7fd48)

What would you think of having a breakpoint after which, instead of showing just seconds, we show minutes and seconds (`Build succeeded in 19 minutes and 29 seconds`) and a later breakpoint for hours (`Build succeeded in 5 hours 7 minutes and 15 seconds`). Would folks be in favor of something like that? If so, what do you think would be appropriate breakpoints? I was thinking like 200 seconds --> 3 minutes and 20 seconds and 100 minutes --> 1 hour and 40 minutes, but I just made that up based on what felt right to me. 60 seconds --> 1 minute and 60 minutes --> 1 hour might be better.

And if you like this idea, I can try to work on it at some point. I recognize that it's not particularly urgent.

### Background and Motivation

I want to know how long my builds took without doing math.

### Proposed Feature

Builds that do the math for me!

**Comment by baronfel** [comment] 2024-07-25 18:59
Good issue! Duplicate of https://github.com/dotnet/msbuild/issues/8782 though :)

**Closed by baronfel** 2024-07-25 18:59 UTC
Labels: needs-design, Feature Request
