### ISSUE TITLE
CopyTask: Fallback to SymbolicLinks if HardLinks fail

### ISSUE THREAD

**Issue by manfred-brands** [dotnet/msbuild#6247] opened 2021-03-12 09:55 UTC
The `UseHardlinksIfPossible` is great to prevent unnecessary copying, but doesn't work when the source and target are on different drives.

In our case we have NuGet packages with contentFiles set to copyToOutput=true.
The NuGet cache is on C: and the source code for some developers is on D:

We could switch to `UseSymboliclinksIfPossible` if it wasn't that most developers don't have permission to create them.
Also hard links are more resilient to someone cleaning the local NuGet cache.

It would be good if the Copy could fallback if both flags are set. At the moment it throws an error when both are set.
So try HardLink, if it not works, try SymbolicLink.

**Comment by manfred-brands** [comment] 2021-03-15 05:41
I managed to set this in the .csproj using conditions
```
    <OutDrive>$([System.IO.Path]::GetPathRoot($(OutDir)))</OutDrive>
    <NuGetDrive>$([System.IO.Path]::GetPathRoot($(NuGetPackageRoot)))</NuGetDrive>
    <CreateHardLinksForAdditionalFilesIfPossible Condition="'$(OutDrive)'=='$(NuGetDrive)'">true</CreateHardLinksForAdditionalFilesIfPossible>
    <CreateSymbolicLinksForAdditionalFilesIfPossible Condition="'$(OutDrive)'!='$(NuGetDrive)'">true</CreateSymbolicLinksForAdditionalFilesIfPossible>
```

But it would still be nice if Copy had such a fallback option built-in.

**Comment by rainersigwald** [comment] 2021-05-27 15:45
That's a nice workaround, but I think the feature request is reasonable. Marking up-for-grabs since I don't think it'll make it to the top of the core team's to-do list for quite a while.

**Comment by JaynieBai** [comment] 2022-11-30 08:55
I'd like to do this. Please assign it to me if the issue is still reasonable.

**Comment by rainersigwald** [comment] 2022-11-30 14:34
@JaynieBai go for it!

> We could switch to `UseSymboliclinksIfPossible` if it wasn't that most developers don't have permission to create them.

This shouldn't be the case anymore on modern Windows with #8157--it should be pretty common to be able to create symlinks on Windows now.

**Closed** 2022-12-12 02:08 UTC
Labels: help wanted, Area: Tasks
