### ISSUE TITLE
SDK-style solution file

### ISSUE THREAD

**Issue by marcusturewicz** [dotnet/msbuild#6810] opened 2021-09-03 02:53 UTC
We all know solution (.sln) files are not ideal:
- Hard to read
- Hard to version control
- Are overly verbose
- Use a non-standard format

An SDK-style solution file would provide the following benefits:
- Easier to read, and would consistent with other metadata .NET files e.g. csproj, Directory.build.props etc
- Easier to version control, as XML is
- Removing heavy use of Guids would reduce it's size
- Would be more approachable for new-comers.

There have been community attempts at this, most notably https://github.com/JeffCyr/MSBuild.SolutionSdk.

There has also been much talk about this on Tech Twitter in recent years:
- https://twitter.com/Nick_Craver/status/1176924151250071553

.NET 7 seems like a great time for this!

**Comment by MichaeIDietrich** [comment] 2021-09-04 08:35
Related disucssion: #1730

**Comment by rainersigwald** [comment] 2021-09-09 16:13
Duplicate of #1730

**Closed by rainersigwald** 2021-09-09 16:13 UTC
Labels: needs-triage
