### ISSUE TITLE
Conditional compilation ignored

### ISSUE THREAD

**Issue by anpin** [dotnet/msbuild#7457] opened 2022-03-10 15:11 UTC
### Issue Description
I'm trying to build this [PR](https://github.com/mono/SkiaSharp/pull/1960), but some projects are failing due to ignored constants 

### Steps to Reproduce
Try to build Uno.WinUI Gallery sample from the PR above.
 
binlog [msbuild.zip](https://github.com/dotnet/msbuild/files/8224457/msbuild.zip)

### Expected Behavior
Conditional compilation works

### Actual Behavior
Conditional compilation fails 

![image](https://user-images.githubusercontent.com/6060545/157691296-7f64ce2a-1237-4a85-a590-a3b078d0e6de.png)

### Analysis

no idea

### Versions & Configurations
Microsoft (R) Build Engine version 17.1.0+ae57d105c for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

17.1.0.7609

**Comment by BenVillalobos** [comment] 2022-03-10 19:11
We dug into this some and I noticed `SkiaSharpSample.Wasm.csproj` didn't contain `HAS_UNO` in `DefineConstants` at all.

I suspect `DefineConstants` is getting overridden somewhere in the build of your project. Is there any conflict/confusion between `DefineConstants` and `UnoDefineConstants`?

**Comment by anpin** [comment] 2022-03-11 06:06
@BenVillalobos bt the issue occurs in the project `SkiaSharp.Views.Uno.WinUI.Mobile.csproj` targeting `net6.0-ios` and `net6.0-maccatalyst`, moreover the project  is not referenced in `SkiaSharpSample.Wasm.csproj`. THe project in question seems to have all the constants defined 
![image](https://user-images.githubusercontent.com/6060545/157811438-039ca638-5332-48d2-ae79-fcd639acb9ef.png)

`UnoDefineConstants` simply adds itself to `DefineConstants` [here](https://github.com/unoplatform/uno/blob/56d3ba98ee6cab055dc8d7c4941ce4494e20e946/src/Common.targets) is the related task

**Comment by BenVillalobos** [comment] 2022-03-31 16:44
Team Triage: We double checked the command line args and `DefineConstants` in your binlog and `HAS_UNO` does look to be defined.

Does the error show up in a command line build, or only in VS?

**Comment by anpin** [comment] 2022-04-05 10:33
here is bin log from cli  [msbuild.zip](https://github.com/dotnet/msbuild/files/8417197/msbuild.zip)

please note that I have also updated `Uno.WinUI` packages 

looks similar, but also has some additional error message 
```

"D:\Work\Projects\SkiaSharp\samples\Gallery\Uno.WinUI\SkiaSharpSample.sln" (default target) (1) ->
"D:\Work\Projects\SkiaSharp\samples\Gallery\Uno.WinUI\SkiaSharpSample.Mobile\SkiaSharpSample.Mobile.csproj" (default target) (2) ->
"D:\Work\Projects\SkiaSharp\samples\Gallery\Uno.WinUI\SkiaSharpSample.Mobile\SkiaSharpSample.Mobile.csproj" (Build target) (2:2) ->
"D:\Work\Projects\SkiaSharp\samples\Gallery\Uno.WinUI\SkiaSharpSample.Mobile\SkiaSharpSample.Mobile.csproj" (_ComputeFilesToPublishForRuntimeIdentifiers target) (2:3) ->
"D:\Work\Projects\SkiaSharp\source\SkiaSharp.Views.Uno\SkiaSharp.Views.Uno.WinUI.Mobile\SkiaSharp.Views.Uno.WinUI.Mobile.csproj" (default target) (5:13) ->
(ValidateUnoUIAndroid target) ->
  D:\nuget\packages\uno.winui\4.1.9\buildTransitive\net6.0-android30.0\uno.winui.targets(199,6): error MSB4086: A numeric comparison was attempted on "$(_CurrentTrimmedAndroidSDLVersion)" that evaluates to "" instead of a number, in condition "'$(


"D:\Work\Projects\SkiaSharp\samples\Gallery\Uno.WinUI\SkiaSharpSample.sln" (default target) (1) ->
"D:\Work\Projects\SkiaSharp\samples\Gallery\Uno.WinUI\SkiaSharpSample.Mobile\SkiaSharpSample.Mobile.csproj" (default target) (2) ->
"D:\Work\Projects\SkiaSharp\samples\Gallery\Uno.WinUI\SkiaSharpSample.Mobile\SkiaSharpSample.Mobile.csproj" (Build target) (2:7) ->
"D:\Work\Projects\SkiaSharp\source\SkiaSharp.Views.Uno\SkiaSharp.Views.Uno.WinUI.Mobile\SkiaSharp.Views.Uno.WinUI.Mobile.csproj" (default target) (5:21) ->
(CoreCompile target) ->
ork\Projects\SkiaSharp\source\SkiaSharp.Views.Uno\SkiaSharp.Views.Uno.WinUI.Mobile\SkiaSharp.Views.Uno.WinUI.Mobile.csproj]
  CSC : error CS1705: Assembly 'Uno.UI' with identity 'Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' uses 'Microsoft.iOS, Version=15.2.303.55, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' which has a higher version th
an referenced assembly 'Microsoft.iOS' with identity 'Microsoft.iOS, Version=15.2.302.122, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' [D:\Work\Projects\SkiaSharp\source\SkiaSharp.Views.Uno\SkiaSharp.Views.Uno.WinUI.Mobile\SkiaSharp.Views.Un
o.WinUI.Mobile.csproj]


"D:\Work\Projects\SkiaSharp\samples\Gallery\Uno.WinUI\SkiaSharpSample.sln" (default target) (1) ->
"D:\Work\Projects\SkiaSharp\samples\Gallery\Uno.WinUI\SkiaSharpSample.Mobile\SkiaSharpSample.Mobile.csproj" (default target) (2) ->
"D:\Work\Projects\SkiaSharp\samples\Gallery\Uno.WinUI\SkiaSharpSample.Mobile\SkiaSharpSample.Mobile.csproj" (Build target) (2:8) ->
"D:\Work\Projects\SkiaSharp\source\SkiaSharp.Views.Uno\SkiaSharp.Views.Uno.WinUI.Mobile\SkiaSharp.Views.Uno.WinUI.Mobile.csproj" (default target) (5:23) ->
  CSC : error CS1705: Assembly 'Uno.UI' with identity 'Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' uses 'Microsoft.MacCatalyst, Version=15.2.303.55, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' which has a higher ve
rsion than referenced assembly 'Microsoft.MacCatalyst' with identity 'Microsoft.MacCatalyst, Version=15.2.302.122, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' [D:\Work\Projects\SkiaSharp\source\SkiaSharp.Views.Uno\SkiaSharp.Views.Uno.WinUI.M
obile\SkiaSharp.Views.Uno.WinUI.Mobile.csproj]
  D:\Work\Projects\SkiaSharp\source\SkiaSharp.Views.Uno\SkiaSharp.Views.Uno.iOS\SKSwapChainPanel.iOS.cs(14,11): error CS0246: The type or namespace name 'SKGLView' could not be found (are you missing a using directive or an assembly reference?) [D
:\Work\Projects\SkiaSharp\source\SkiaSharp.Views.Uno\SkiaSharp.Views.Uno.WinUI.Mobile\SkiaSharp.Views.Uno.WinUI.Mobile.csproj]


"D:\Work\Projects\SkiaSharp\samples\Gallery\Uno.WinUI\SkiaSharpSample.sln" (default target) (1) ->
"D:\Work\Projects\SkiaSharp\samples\Gallery\Uno.WinUI\SkiaSharpSample.Mobile\SkiaSharpSample.Mobile.csproj" (default target) (2) ->
"D:\Work\Projects\SkiaSharp\samples\Gallery\Uno.WinUI\SkiaSharpSample.Mobile\SkiaSharpSample.Mobile.csproj" (Build target) (2:9) ->
"D:\Work\Projects\SkiaSharp\source\SkiaSharp.Views.Uno\SkiaSharp.Views.Uno.WinUI.Mobile\SkiaSharp.Views.Uno.WinUI.Mobile.csproj" (default target) (5:25) ->
  D:\Work\Projects\SkiaSharp\source\SkiaSharp.Views.Uno\SkiaSharp.Views.Uno.Mac\SKXamlCanvas.macOS.cs(3,23): error CS0234: The type or namespace name 'Mac' does not exist in the namespace 'SkiaSharp.Views' (are you missing an assembly reference?)
[D:\Work\Projects\SkiaSharp\source\SkiaSharp.Views.Uno\SkiaSharp.Views.Uno.WinUI.Mobile\SkiaSharp.Views.Uno.WinUI.Mobile.csproj]
  D:\Work\Projects\SkiaSharp\source\SkiaSharp.Views\SkiaSharp.Views.Mac\SKGLView.cs(6,23): error CS0234: The type or namespace name 'GlesInterop' does not exist in the namespace 'SkiaSharp.Views' (are you missing an assembly reference?) [D:\Work\P
rojects\SkiaSharp\source\SkiaSharp.Views.Uno\SkiaSharp.Views.Uno.WinUI.Mobile\SkiaSharp.Views.Uno.WinUI.Mobile.csproj]
  CSC : error CS1705: Assembly 'Uno.UI' with identity 'Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' uses 'Microsoft.macOS, Version=12.1.303.55, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' which has a higher version
than referenced assembly 'Microsoft.macOS' with identity 'Microsoft.macOS, Version=12.1.302.122, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' [D:\Work\Projects\SkiaSharp\source\SkiaSharp.Views.Uno\SkiaSharp.Views.Uno.WinUI.Mobile\SkiaSharp.Vi
ews.Uno.WinUI.Mobile.csproj]
  D:\Work\Projects\SkiaSharp\source\SkiaSharp.Views.Uno\SkiaSharp.Views.Uno.Mac\SKXamlCanvas.macOS.cs(14,11): error CS0246: The type or namespace name 'SKCGSurfaceFactory' could not be found (are you missing a using directive or an assembly refere
nce?) [D:\Work\Projects\SkiaSharp\source\SkiaSharp.Views.Uno\SkiaSharp.Views.Uno.WinUI.Mobile\SkiaSharp.Views.Uno.WinUI.Mobile.csproj]


"D:\Work\Projects\SkiaSharp\samples\Gallery\Uno.WinUI\SkiaSharpSample.sln" (default target) (1) ->
"D:\Work\Projects\SkiaSharp\samples\Gallery\Uno.WinUI\SkiaSharpSample.Wasm\SkiaSharpSample.Wasm.csproj" (default target) (7) ->
  D:\Work\Projects\SkiaSharp\samples\Gallery\Uno.WinUI\SkiaSharpSample.Wasm\Program.cs(8,18): error CS0246: The type or namespace name 'App' could not be found (are you missing a using directive or an assembly reference?) [D:\Work\Projects\SkiaSha
rp\samples\Gallery\Uno.WinUI\SkiaSharpSample.Wasm\SkiaSharpSample.Wasm.csproj]


"D:\Work\Projects\SkiaSharp\samples\Gallery\Uno.WinUI\SkiaSharpSample.sln" (default target) (1) ->
"D:\Work\Projects\SkiaSharp\samples\Gallery\Uno.WinUI\SkiaSharpSample.Windows.Desktop\SkiaSharpSample.Windows.Desktop.csproj" (default target) (14) ->
(MarkupCompilePass1 target) ->
  D:\Work\Projects\SkiaSharp\samples\Gallery\Uno\SkiaSharpSample.Shared\MainPage.xaml : Xaml Internal Error error WMC9999: Type universe cannot resolve assembly: Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null. [D:\Work\Proje
cts\SkiaSharp\samples\Gallery\Uno.WinUI\SkiaSharpSample.Windows.Desktop\SkiaSharpSample.Windows.Desktop.csproj]


"D:\Work\Projects\SkiaSharp\samples\Gallery\Uno.WinUI\SkiaSharpSample.sln" (default target) (1) ->
"D:\Work\Projects\SkiaSharp\samples\Gallery\Uno.WinUI\SkiaSharpSample.Windows.Package\SkiaSharpSample.Windows.Package.wapproj" (default target) (15) ->
"D:\Work\Projects\SkiaSharp\samples\Gallery\Uno.WinUI\SkiaSharpSample.Windows.Desktop\SkiaSharpSample.Windows.Desktop.csproj" (publish target) (14:6) ->
(ValidateNoPublishTrimmed target) ->
  D:\nuget\packages\microsoft.windowsappsdk\1.0.0\build\Microsoft.WinUI.AppX.targets(306,5): error : Publishing with IL trimming is not yet supported. [D:\Work\Projects\SkiaSharp\samples\Gallery\Uno.WinUI\SkiaSharpSample.Windows.Desktop\SkiaSharpS
ample.Windows.Desktop.csproj]

    112 Warning(s)
    12 Error(s)
```

**Comment by jeromelaban** [comment] 2022-04-05 12:40
The build errors you are seeing (the catalyst and iOS ones) are caused by a discrepancy between the .NET 6 Mobile SDK used by Uno and the one used in the SkiaSharp build (RC1 Preview vs. Preview 14). We expect this will be fixed when RC1 gets released (along with the .NET SDK 6.0.300)

**Comment by BenVillalobos** [comment] 2022-04-05 18:59
Thanks for the heads up @jeromelaban! Closing this as it's not an msbuild issue

**Closed by BenVillalobos** 2022-04-05 18:59 UTC
Labels: bug
