### ISSUE TITLE
[Bug]: Typescript compiled in PreBuild event is not included in nuget package when running dotnet pack

### ISSUE THREAD

**Issue by jeppetn** [dotnet/msbuild#9659] opened 2024-01-18 08:06 UTC
### Issue Description

[TypescriptPackIssue.zip](https://github.com/dotnet/msbuild/files/13973614/TypescriptPackIssue.zip)
I have a Razor class library that contains multiple typescript files.

On build I compile these into a scripts.js file that should serve as static web assets in my nuget package.

Issue: When performing a dotnet pack then the compilation of typescript, resulting in creation of scripts.js, is not included the staticwebassets folder. This is true even if I compile the typescript in a PreBuild event, see it's created, wait a few seconds and then build/pack starts. So at the time of building/packing the file is existing.

However if the scripts.js is present before the dotnet pack then it is included.

### Steps to Reproduce

1. Open the attached project.
2. Run dotnet pack. Notice the scripts.js file is created and execution waits a few seconds and then the nuget package is created.
3. Open the nuget package and conclude that the scripts.js is not present in the folder named "staticwebassets".

Try running step 2 and 3 again without removing the scripts.js. Then conclude that the scripts.js is suddenly there.

### Expected Behavior

When running dotnet pack the typescript compiled during build is present in the created nuget package.

### Actual Behavior

When running dotnet pack the typescript compiled during build is **not** present in the created nuget package.

**Comment by JaynieBai** [comment] 2024-01-26 02:43
@jeppetn You need add the created item scripts.js in the target PreBuild. 
```
<Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="echo building ts" />
    <Exec Command="tsc" />
    <Exec Command="echo waiting a bit to guarantee the file is there" />

    <Exec Command="ping -n 6 127.0.0.1 > nul" />
    <Exec Command="echo waiting is over" />
    <ItemGroup>
      <Content Include="wwwroot\scripts\scripts.js" />
    </ItemGroup>
  </Target>
```

**Comment by jeppetn** [comment] 2024-01-26 10:16
@JaynieBai Ohh i tried that but using <None/> instead of <Content/>. 

Thanks for letting me know and sorry for taking your time! :)

Have a nice weekend.

**Comment by JaynieBai** [comment] 2024-01-29 06:49
Close this issue because it’s not a bug. A workaround has been provided. If something wrong, feel free to open it.

**Closed by JaynieBai** 2024-01-29 06:49 UTC
