### ISSUE TITLE
dotnet5 msbuild regressions

### ISSUE THREAD

**Issue by vchirikov** [dotnet/msbuild#5600] opened 2020-08-02 16:38 UTC
### Issue Description

* issue1  SdkResolverService issue can be a reason of: https://github.com/microsoft/MSBuildSdks/issues/195
    Microsoft.Build.Framework  packet can't load csproj that uses CentralPackageVersions if you use msbuild from dotnet 5.
   This works fine with dotnet 3.1
* issue2: `dotnet restore` (msbuild) returns error while restore is complete. 

### Steps to Reproduce

https://github.com/vchirikov/msbuild_issue_repro
There are 2 different issues, but maybe all of them connected.

### Expected Behavior
issue1: CentralPackageVersions is resolved correctly
issue2: `dotnet restore` returns 0

### Actual Behavior
issue1 exception:
```
'The SDK 'Microsoft.Build.CentralPackageVersions/2.0.52' specified could not be found
```
issue2 returns `-1` exit code

### Analysis

1) Recent changes in `SdkResolverService`

### Versions & Configurations

```
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.7.20366.6
 Commit:    0684df3a5b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.7.20366.6\

Host (useful for support):
  Version: 5.0.0-preview.7.20364.11
  Commit:  53976d38b1

.NET SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]
  3.1.400-preview-015203 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.7.20366.6 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.7.20365.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-fork.vchirikov [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.7.20364.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.7.20366.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by jeffkl** [comment] 2020-08-03 16:16
I'm not able to reproduce this.  Am I following the steps wrong?

```cmd
D:\msbuild_issue_repro>git remote -v
origin  https://github.com/vchirikov/msbuild_issue_repro.git (fetch)
origin  https://github.com/vchirikov/msbuild_issue_repro.git (push)

D:\msbuild_issue_repro>C:\Users\jeffkl\Downloads\dotnet-sdk-5.0.100-preview.7.20366.6-win-x64\dotnet.exe restore
  Determining projects to restore...
  Restored D:\msbuild_issue_repro\issue1\msbuild_issue_repro.csproj (in 9.53 sec).
  Restored D:\msbuild_issue_repro\issue2\issue2.csproj (in 9.53 sec).
```

**Comment by vchirikov** [comment] 2020-08-03 18:41
@jeffkl 
try run under debug. Problem is that msbuild return 1 (failed) after actual restore.
You can see it with binlog or diag (if you change arguments in issue1 project.

```
C:\code\vchirikov\msbuild_issue_repro [master ≡]> dotnet restore
  Determining projects to restore...
  Restored C:\code\vchirikov\msbuild_issue_repro\issue1\msbuild_issue_repro.csproj (in 218 ms).
  Restored C:\code\vchirikov\msbuild_issue_repro\issue2\issue2.csproj (in 218 ms).
C:\code\vchirikov\msbuild_issue_repro [master ≡]> dotnet run --project .\issue1\
  Determining projects to restore...
  Restored C:\code\vchirikov\msbuild_issue_repro\issue2\issue2.csproj (in 176 ms).
  Restored C:\code\vchirikov\msbuild_issue_repro\issue1\msbuild_issue_repro.csproj (in 176 ms).
Unhandled exception. CliWrap.Exceptions.CommandExecutionException: Underlying process reported a non-zero exit code (1).

Command:
  C:\Program Files\dotnet\dotnet.exe restore

You can suppress this validation by calling `WithValidation(CommandResultValidation.None)` on the command.
   at CliWrap.Command.ExecuteAsync(ProcessEx process, CancellationToken cancellationToken)
   at msbuild_issue_repro.Program.Main(String[] args) in C:\code\vchirikov\msbuild_issue_repro\issue1\Program.cs:line 34
   at msbuild_issue_repro.Program.<Main>(String[] args)
```
And this is -v:diag

![image](https://user-images.githubusercontent.com/40987940/89215879-1297ad00-d5d2-11ea-9d01-707811f7c003.png)

**Comment by vchirikov** [comment] 2020-08-03 18:50
For reproducing issue 1 you should comment https://github.com/vchirikov/msbuild_issue_repro/blob/30ce422c10ae77e3cbec0279f868737eb4cc9e3d/issue1/Program.cs#L1
this define

**Comment by vchirikov** [comment] 2020-08-08 17:45
@BenVillalobos can you reproduce the issue?

**Comment by BenVillalobos** [comment] 2020-08-11 00:17
I'm able to reproduce _most_ of what you're seeing. 

## Version
`dotnet --version`
```
C:\src\github\msbuild_issue_repro>dotnet --version
5.0.100-preview.7.20366.6

C:\src\github\msbuild_issue_repro>where dotnet
C:\Program Files\dotnet\dotnet.exe
```
## Repro
### `dotnet restore`
```
C:\src\github\msbuild_issue_repro>dotnet restore
  Determining projects to restore...
  Restored C:\src\github\msbuild_issue_repro\issue2\issue2.csproj (in 247 ms).
  Restored C:\src\github\msbuild_issue_repro\issue1\msbuild_issue_repro.csproj (in 247 ms).
```

### `dotnet run --project issue1\`
```
C:\src\github\msbuild_issue_repro>dotnet run --project issue1\
  Determining projects to restore...
  Restored C:\src\github\msbuild_issue_repro\issue2\issue2.csproj (in 255 ms).
  Restored C:\src\github\msbuild_issue_repro\issue1\msbuild_issue_repro.csproj (in 255 ms).
Unhandled exception. CliWrap.Exceptions.CommandExecutionException: Underlying process reported a non-zero exit code (1).

Command:
  C:\Program Files\dotnet\dotnet.exe restore

You can suppress this validation by calling `WithValidation(CommandResultValidation.None)` on the command.
   at CliWrap.Command.ExecuteAsync(ProcessEx process, CancellationToken cancellationToken)
   at msbuild_issue_repro.Program.Main(String[] args) in C:\src\github\msbuild_issue_repro\issue1\Program.cs:line 34
   at msbuild_issue_repro.Program.<Main>(String[] args)
```
The difference in our repros seem to be that I get a successful restore. My underlying command also doesn't carry the `-v:diag` for some reason.

### `dotnet run --project issue1\ -v:diag`
![image](https://user-images.githubusercontent.com/4691428/89841952-2343a800-db29-11ea-9386-a247d69876e5.png)

### `dotnet run --project issue1\` (for repro 1)
```
C:\src\github\msbuild_issue_repro>dotnet run --project issue1\
Unhandled exception. Microsoft.Build.Exceptions.InvalidProjectFileException: The SDK 'Microsoft.Build.CentralPackageVersions/2.0.79' specified could not be found.  C:\src\github\msbuild_issue_repro\Directory.Build.targets
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ProjectErrorUtilities.VerifyThrowInvalidProject[T1](Boolean condition, String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, T1 arg0)
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject[T1](IElementLocation elementLocation, String resourceName, T1 arg0)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCacheBase projectRootElementCache, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, EvaluationContext evaluationContext, Boolean interactive)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, ProjectCollection projectCollection)
   at msbuild_issue_repro.Program.Main(String[] args) in C:\src\github\msbuild_issue_repro\issue1\Program.cs:line 30
   at msbuild_issue_repro.Program.<Main>(String[] args)
```

Will be looking more into this, just wanted to confirm that I can repro most of this.

**Comment by vchirikov** [comment] 2020-08-11 06:39
> Will be looking more into this, just wanted to confirm that I can repro most of this.

yes, you reproduced everything.

1)  SdkResolverService issue
2) `dotnet restore` - works fine from cmd and returned 0  
    `dotnet restore` - from another program it returns non-zero exit code.

**Comment by BenVillalobos** [comment] 2020-08-18 23:33
Spent some time digging into this today and noticed a few things.

One issue here is that there was a relevant breaking change done with the migration to dotnet 5 where nuget took a dependency on `System.Runtime` version 5.0, which isn't compatible when on `netcoreapp3.1`. A workaround for this issue in your case is to target `net5.0` instead of `netcoreapp3.1`.

Another issue here is the error behind the scenes isn't getting routed properly. You should be getting 
```
The NuGet-based SDK resolver failed to run because NuGet assemblies could not be located.  Check your installation of MSBuild or set the environment variable "MSBUILD_NUGET_PATH" to the folder that contains the required NuGet assemblies. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
```

Still investigating this.

**Comment by BenVillalobos** [comment] 2020-08-18 23:36
Another note: Instead of manually finding MSBuild, you should be [using MSBuildLocator](https://docs.microsoft.com/en-us/visualstudio/msbuild/updating-an-existing-application?view=vs-2019#use-microsoftbuildlocator). Though note the issue linked earlier.

**Comment by theolivenbaum** [comment] 2020-08-31 14:39
Hitting the same issue with our [C# to JS compiler](https://h5.rocks) starting since I installed the latest VS2019 preview update today (Version 16.8.0 Preview 2.0), where it is failing to locate the correct NuGet custom SDK target (which is available on disk if I check the .nuget folder on my computer).

![image](https://user-images.githubusercontent.com/8791811/91732346-67feb400-eba8-11ea-912e-18e7a05e406a.png)

**Comment by theolivenbaum** [comment] 2020-08-31 15:22
I can also confirm uninstalling VS2019 preview and the associated .NET 5.0 SDK (effective rolling back to the .NET Core SDK 3.1.401) fixes the compilation problem.

If you need to reproduce, there is an empty dotnet new template for h5 here: https://www.nuget.org/packages/h5.template

**Comment by vchirikov** [comment] 2020-09-28 09:33
@BenVillalobos any news?

**Comment by BenVillalobos** [comment] 2020-10-06 20:52
@vchirikov Unfortunately not. Other than calling `MSBuildLocator.RegisterDefaults()` _should_ be enough to set things up properly for you. I tested this with your repro project and hit the issue with `Microsoft.Build.CentralPackageVersions/2.0.79` not being found.

The strange thing is that it certainly **looks** like it's being loaded properly:
![image](https://user-images.githubusercontent.com/4691428/95257945-e79c2600-07d9-11eb-9317-738269fb3e47.png)

![sdkresult](https://user-images.githubusercontent.com/4691428/95258246-524d6180-07da-11eb-83ca-c8738358c5d7.png)

**Comment by BenVillalobos** [comment] 2020-10-06 21:00
I may have spoken too soon. It seems this is fixed in a newer version. I decided to verify this on a newer msbuild / net core combo and here's what I see.
```
C:\src\git\repros\5600\updated_msbuild_issue_repro>dotnet run --project issue1
  Determining projects to restore...
  All projects are up-to-date for restore.
Done. Result: 0
```


**dotnet --version**
```
5.0.100-rc.2.20479.15
```

**dotnet msbuild -version** (locally deployed)
```
Microsoft (R) Build Engine version 16.8.0-dev-20506-01+aed5e7ed0 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.8.0.5060
```

**Comment by vchirikov** [comment] 2020-10-07 08:35
> @vchirikov is this the expected output of your program?

yes, but you changed tfm. The original issue was how to load a **`netcoreapp3.1`** project that uses a custom SDK if the dotnet5 sdk is also presented on the computer (MSBuild from net5, but we are trying to load netcoreapp3.1 app),

I tested this issue again, with current dotnet 5.0 RC (tfm is `netcoreapp3.1`). Now I've got another exception (`dotnet run --project issue1`):

```
Microsoft.Build.Exceptions.InvalidProjectFileException: 'Invalid static method invocation syntax: "[MSBuild]::GetTargetFrameworkIdentifier('$(TargetFramework)')". Method '[MSBuild]::GetTargetFrameworkIdentifier' not found. Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, `b`)). Check that all parameters are defined, are of the correct type, and are specified in the right order.  C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets'

```

Same exception if I change the tfm to net5.0.
I've updated the repro to use the latest `Microsoft.Build` packages (16.7.0).

p.s. versions:
```bash
> dotnet --version
5.0.100-rc.1.20452.10
> dotnet msbuild -version
Microsoft (R) Build Engine version 16.8.0-preview-20451-02+51a1071f8 for .NET
16.8.0.45102
```

**Comment by jhelmink** [comment] 2021-01-20 01:42
I've just seen what I think is a similar issue on my TeamCity CI build server. I set my web project target to .NET 5.0 and upgraded all my dotnet packages to the latest 5.0.2. Installed the [SDK 5.0.102](https://dotnet.microsoft.com/download/dotnet/5.0) on the build server. However after TeamCity successfully deployed to my host, I discovered they don't support .NET 5.0 yet. I reverted back to the latest .NET Core 3.1.11 packages in my project, and reverted to target .NET Core 3.1.

When redeploying using TeamCity I got this error message when trying to access the webserver: `FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.` despite my project not having any .NET 5.0 dependencies. This build used `Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET`

I uninstalled the SDK from my build server, redeployed and it worked again, now using `Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Core`

Hope that helps, let me know if you want any of the dotnet publish build logs.

**Comment by BenVillalobos** [comment] 2021-05-21 21:53
@jhelmink does your project have a global.json?

@vchirikov I noticed your project didn't have one, I was able to get successful builds/runs by using MSBuildLocator to find MSBuild and creating a global.json that explicitly looks for a 3.x sdk.

**Comment by vchirikov** [comment] 2021-05-24 09:17
> @vchirikov I noticed your project didn't have one, I was able to get successful builds/runs by using MSBuildLocator to find MSBuild and creating a global.json that explicitly looks for a 3.x sdk.

I wrote it before:

> The original issue was how to load a netcoreapp3.1 project that uses a custom SDK if the dotnet5 sdk is also presented on the computer (MSBuild from net5, but we are trying to load netcoreapp3.1 app),

and you didn't answer the question, create global.json is not an answer. I'll try to explain it. Imagine you have a build tool which uses msbuild sdk (you are the owner of this tool), you compiled it with net5 and want to load an external netcoreapp3.1 project (you aren't owner of this project) to it. So creating a global.json is not an option.

**Comment by gandharv-kapoor** [comment] 2022-02-07 22:04
Any update on this? Seeing the same issue.

**Comment by dsplaisted** [comment] 2022-02-08 20:13
> The original issue was how to load a netcoreapp3.1 project that uses a custom SDK if the dotnet5 sdk is also presented on the computer (MSBuild from net5, but we are trying to load netcoreapp3.1 app),

Let's say you have a tool (call it A) that uses MSBuild APIs to load another project (call that project B).

If tool A is targeting .NET Core 3.1, then it will not work if it tries to use the MSBuild version from the .NET 5 SDK.  It will try to load code written for .NET 5 in a process that's running in .NET Core 3.1.

It sounds to me like a lot of the issues reported here are caused by this.  You would either need to update tool A to target .NET 5, or find a way to have tool A load the .NET Core 3.1 SDK version of MSBuild instead of the .NET 5 version.  That's where global.json may help.

Project B, which is being evaluated by tool A, can still target .NET Core 3.1 or a previous version.  That sounds like what you're describing here:

> Imagine you have a build tool which uses msbuild sdk (you are the owner of this tool), you compiled it with net5 and want to load an external netcoreapp3.1 project (you aren't owner of this project) to it.

Note 1: It looks like in the [repro](https://github.com/vchirikov/msbuild_issue_repro/tree/master/issue1), the project is actually loading itself, so Tool A and Project B are actually the same project in that case.

Note 2: As mentioned previously, we recommend using [MSBuildLocator](https://docs.microsoft.com/en-us/visualstudio/msbuild/updating-an-existing-application?view=vs-2019#use-microsoftbuildlocator) for tools like this.

Does that help?

**Comment by vchirikov** [comment] 2022-02-09 09:37
> You would either need to update tool A to target .NET 5, or find a way to have tool A load the .NET Core 3.1 SDK version of MSBuild instead of the .NET 5 version. That's where global.json may help.

> Same exception if I change the tfm to net5.0.
and
> external netcoreapp3.1 project (you aren't owner of this project)

I think it's clear that I can't place `global.json` to project B, the build tool (project A) can't change directory/files at project B.

> Does that help?

No, Sorry, but I don't want to spend time digging and explaining a bug with a response time of more than 1.5 years.

**Comment by tuscen** [comment] 2022-02-09 19:07
We have a project with ASP.NET MVC5 where we are using `CentralPackageVersions` and VS2019 and VS2022 are affected by this issue, whereas VS 2017 and the latest Rider aren't.

**Closed** 2022-11-16 18:28 UTC
Labels: bug, author-responded
