### ISSUE TITLE
[Bug]: MSBuild.exe does not build deps.json file

### ISSUE THREAD

**Issue by manojsitapara** [dotnet/msbuild#9222] opened 2023-09-18 08:14 UTC
### Issue Description

I am currently working on a console application in .NET Core, and it previously had a reference to the "MyThirdPartyLibrary.dll" library. However, we recently removed this reference from our project.

Our build process relies on automated builds using MSBuild.exe rather than Visual Studio. The problem I'm encountering is that when I build the solution from Visual Studio, I can observe that the deps.json file is updated correctly, and it removes the reference to "MyThirdPartyLibrary.dll." However, when I build the solution using MSBuild.exe, the deps.json file is not updated, and it still contains a reference to "MyThirdPartyLibrary.dll."

I'm looking for guidance on how to resolve this issue or if there's a viable workaround available.

### Steps to Reproduce

Steps to Reproduce:

1. Download the provided source code for the sample console application. ([MSBuildIssueSourceCode.zip](https://github.com/dotnet/msbuild/files/12645763/MSBuildIssue.zip))

2. Open the solution in Visual Studio 2019.

3. Build the solution using Visual Studio.

4. After building, you will notice that the deps.json file is created by Visual Studio, and it contains a reference to "MyThirdPartyLibrary.dll."

5. Now, remove the "MyThirdPartyLibrary.dll" library reference from the solution, but do not make any changes to any of the C# files.

6. Build the solution using MSBuild.exe with the following command:

   ```
   msbuild.exe H:\Work\Source\POC\MSBuildIssue\MSBuildIssue.sln
   ```

7. After executing the MSBuild command, you will observe that the deps.json file is not updated, and it still contains a reference to "MyThirdPartyLibrary.dll."

### Expected Behavior

When building the solution using MSBuild.exe after removing the reference to "MyThirdPartyLibrary.dll" from the project, the deps.json file should be updated to reflect the removal of the reference. This means that the reference to "MyThirdPartyLibrary.dll" should no longer be present in the deps.json file after the build process is complete.

### Actual Behavior

deps.json file is not updated, and it still contains a reference to "MyThirdPartyLibrary.dll."

### Versions & Configurations

Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

`16.11.2.50704`

**Comment by YuliiaKovalova** [comment] 2023-09-18 11:53
can be related to https://github.com/dotnet/sdk/issues/23935

**Comment by manojsitapara** [comment] 2023-09-18 13:22
@YuliiaKovalova  it is not related to that issue, My issue is different. Please do not close the ticket and provide us some work around to fix it

**Comment by manojsitapara** [comment] 2023-09-18 15:26
> > it is not related to that issue, My issue is different
> 
> What makes you think that?

Can you please suggest any workaround to fix the issue?

**Comment by rainersigwald** [comment] 2023-09-19 13:43
Duplicate of https://github.com/dotnet/sdk/issues/23935

**Closed by rainersigwald** 2023-09-19 13:43 UTC
Labels: bug, needs-triage

**Comment by manojsitapara** [comment] 2023-10-10 10:48
@rainersigwald This issue isn't identical. In my situation, I had a third-party library reference in my project that was subsequently removed. However, the deps.json file didn't get updated as expected. I'm uncertain why the ticket was closed, especially since I provided a sample console application to reproduce the issue. Could you please reconsider reopening it to assist us in resolving the problem? Your help would be greatly appreciated.
