### ISSUE TITLE
CA0063 and CA0064 suddenly error instead of warning in 16.8

### ISSUE THREAD

**Issue by acuntex** [dotnet/msbuild#5938] opened 2020-12-07 10:37 UTC
### Issue Description
After installing .NET 5 on our build servers, we noticed that CA0063 and CA0064 suddenly changed from warning to error, making it a breaking change.
The .NET 5 installer replaced MSBuild 16.X with 16.8.

This also happens if a developer updates visual studio 2019 with the installer to the newest version.

### Steps to Reproduce
Create a .csproj with code analysis enabled, but with a missing ruleset file.
```
    <RunCodeAnalysis>true</RunCodeAnalysis>
    <CodeAnalysisRuleSet>..\..\build\CodeAnalysis.ruleset</CodeAnalysisRuleSet>
```

### Expected Behavior
CA0063 and CA0064 are warnings, as they were in 16.7 and below.

### Actual Behavior
CA0063 and CA0064 are errors in 16.8.

### Versions & Configurations
Microsoft (R)-Build-Engine, Version 16.8.2+25e4d540b

**Comment by rainersigwald** [comment] 2020-12-09 17:01
@mavasani can you help us route this?

**Comment by mavasani** [comment] 2020-12-09 17:22
This is duplicate of https://developercommunity2.visualstudio.com/t/After-168-update-getting-lot-of-code-an/1251574?preview=true. Please see the [solution](https://developercommunity2.visualstudio.com/t/After-168-update-getting-lot-of-code-an/1251574?preview=true#T-N1255914) for workaround in 16.8. Customer should also consider moving away from legacy code analysis, i.e. remove `<RunCodeAnalysis>true</RunCodeAnalysis>` or set it to false.

**Comment by acuntex** [comment] 2020-12-09 17:57
@mavasani That bug seems to be something completely different.

The problem is that two codes (CA0063 and CA0064) were previously (< 16.7) warnings, and are suddenly now (16.8) a hard error.

This means that a breaking change occurred within a major version. Once a developer clicks on "Update" in Visual Studio or something like .NET 5 gets installed on a build server, the project can't be built anymore because of this breaking change.

**Comment by mavasani** [comment] 2020-12-09 18:02
> That bug seems to be something completely different.

@acuntex Two things to point out:
1. `<RunCodeAnalysis>true</RunCodeAnalysis>` is triggering [legacy code analysis](https://docs.microsoft.com/visualstudio/code-quality/migrate-from-legacy-analysis-to-net-analyzers), which has been deprecated for more than a year now. It will be removed from VS with next major release of VS, and we have been asking customers to move off it as soon as they can.
1. The feedback ticket cited above is the same issue as this - All CA warnings coming from legacy code analysis are escalated errors in 16.8, they used to be reported as warnings by default in 16.7. This is a known regression in 16.8, which has been fixed in 16.9, but did not meet the 16.8 servicing bar as the regression is in a legacy, deprecated feature with a simple workaround.

**Comment by acuntex** [comment] 2020-12-09 18:07
Yes, you can remove this flag easily, which we already did for our main branch.

But if you support fixing older versions, you now have to either do back ports this fix for all old versions or you have to provide separate build machines that have an older version of MSBuild (e.g. MSBuild 16.7) installed.

If it was a major version breaking change, there would be still a possibility do have the old version installed.

C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe	<-- Current Version (Either 16.7 or 16.8, but not both)
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin\MSBuild.exe	<-- Older 15.0 Version

**Comment by rainersigwald** [comment] 2020-12-10 19:37
Closing:

> This is duplicate of https://developercommunity2.visualstudio.com/t/After-168-update-getting-lot-of-code-an/1251574?preview=true.

**Closed by rainersigwald** 2020-12-10 19:37 UTC
Labels: bug, untriaged
