### ISSUE TITLE
Visual Studio Fast Up To Date build not working - CopyComplete marker is touched when no files are copied

### ISSUE THREAD

**Issue by Scottj1s** [dotnet/msbuild#6576] opened 2021-06-16 17:54 UTC
**Visual Studio Version**: 16.10.2

**Summary**:
With Fast Up To Date builds enabled, a subsequent build should not invoke MSBuild if no inputs have changed.  

**Steps to Reproduce**:

1. Launch VS command prompt
2. Clone https://github.com/microsoft/CsWinRT/ repo
3. cd into 'src' and run build.cmd
4. After a successful baseline build, run 'devenv cswinrt.sln'
5. Enable verbose build diagnostics 
  Tools|Options|Projects and Solutions|Build And Run
  Set "MSBuild project build output verbosity:" to Diagnostic
6. Enable verbose Up To Date diagnostics
  Tools|Options|Projects and Solutions|SDK-Style Projects
  Up do Date Checks
  Check "Don't call MSBuild if a project appearst to be up to date."
  Set "Logging Level:" to Verbose
7. Right-click the Projections\Test project node and run several builds

**Expected Behavior**:
After the first build, Fast Up To Date should detect that no inputs are newer than outputs and not invoke MSBuild

**Actual Behavior**:
MSBuild is invoked every time.  Excerpt of the build spew for target "_CopyFilesMarkedCopyLocal" below indicates the cause.  Even though the Copy task reports "Did not copy from file" for every file, the WinUI.csproj.CopyComplete marker is still touched, causing the dependent Test project to be reported as "not up to date" and triggering an MSBuild.

**Root Cause**:
The reason appears to be a bug in the [Copy task implementation](https://devdiv.visualstudio.com/DevDiv/_git/DotNet-msbuild-Trusted?path=%2Fsrc%2FTasks%2FCopy.cs&_a=contents&version=GBmain).  DoCopyIfNecessary initializes success to true, and returns that value when it also reports "Did not copy from file...".  Calls to DoCopyIfNecessary set a local copyComplete to true and based on that value, add an entry to destinationFilesSuccessfullyCopied and ultimately the output parameter CopiedFiles.  The _CopyFilesMarkedCopyLocal target in Microsoft.Common.CurrentVersion.targets binds CopiedFiles to the item ReferencesCopiedInThisBuild, which is used to conditionally touch the CopyUpToDateMarker.  So even if no files are copied, the marker is still touched.

**Build Spew**:
Target "_CopyFilesMarkedCopyLocal" in file "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets":
  Set Property: CreateHardLinksForCopyLocalIfPossible=false
  Set Property: CreateSymbolicLinksForCopyLocalIfPossible=false
  Task "Copy"
    Task Parameter:UseHardlinksIfPossible=False
    Task Parameter:SkipUnchangedFiles=True
    Task Parameter:
        DestinationFiles=
            bin\x64\Release\net5.0\Windows.dll
            bin\x64\Release\net5.0\WinRT.Runtime.dll
            bin\x64\Release\net5.0\cswinrt.pdb
            bin\x64\Release\net5.0\WinRT.Runtime.pdb
            bin\x64\Release\net5.0\Windows.pdb
    Task Parameter:
        SourceFiles=
            d:\git\cswinrt2\src\Projections\Windows\bin\x64\Release\net5.0\Windows.dll
            d:\git\cswinrt2\src\WinRT.Runtime\bin\Release\net5.0\WinRT.Runtime.dll
            d:\git\cswinrt2\src\_build\x64\Release\cswinrt\bin\cswinrt.pdb
            d:\git\cswinrt2\src\WinRT.Runtime\bin\Release\net5.0\WinRT.Runtime.pdb
            d:\git\cswinrt2\src\Projections\Windows\bin\x64\Release\net5.0\Windows.pdb
    Task Parameter:OverwriteReadOnlyFiles=False
    Task Parameter:UseSymboliclinksIfPossible=False
    Did not copy from file "d:\git\cswinrt2\src\WinRT.Runtime\bin\Release\net5.0\WinRT.Runtime.dll" to file "bin\x64\Release\net5.0\WinRT.Runtime.dll" because the "SkipUnchangedFiles" parameter was set to "true" in the project and the files' sizes and timestamps match.
    Did not copy from file "d:\git\cswinrt2\src\_build\x64\Release\cswinrt\bin\cswinrt.pdb" to file "bin\x64\Release\net5.0\cswinrt.pdb" because the "SkipUnchangedFiles" parameter was set to "true" in the project and the files' sizes and timestamps match.
    Did not copy from file "d:\git\cswinrt2\src\WinRT.Runtime\bin\Release\net5.0\WinRT.Runtime.pdb" to file "bin\x64\Release\net5.0\WinRT.Runtime.pdb" because the "SkipUnchangedFiles" parameter was set to "true" in the project and the files' sizes and timestamps match.
    Did not copy from file "d:\git\cswinrt2\src\Projections\Windows\bin\x64\Release\net5.0\Windows.pdb" to file "bin\x64\Release\net5.0\Windows.pdb" because the "SkipUnchangedFiles" parameter was set to "true" in the project and the files' sizes and timestamps match.
    Did not copy from file "d:\git\cswinrt2\src\Projections\Windows\bin\x64\Release\net5.0\Windows.dll" to file "bin\x64\Release\net5.0\Windows.dll" because the "SkipUnchangedFiles" parameter was set to "true" in the project and the files' sizes and timestamps match.
    Output Item(s): 
        FileWritesShareable=
            bin\x64\Release\net5.0\Windows.dll
            bin\x64\Release\net5.0\WinRT.Runtime.dll
            bin\x64\Release\net5.0\cswinrt.pdb
            bin\x64\Release\net5.0\WinRT.Runtime.pdb
            bin\x64\Release\net5.0\Windows.pdb
    Output Item(s): 
        ReferencesCopiedInThisBuild=
            bin\x64\Release\net5.0\Windows.dll
            bin\x64\Release\net5.0\WinRT.Runtime.dll
            bin\x64\Release\net5.0\cswinrt.pdb
            bin\x64\Release\net5.0\WinRT.Runtime.pdb
            bin\x64\Release\net5.0\Windows.pdb
  Done executing task "Copy".
  Task "Touch"
    Task Parameter:AlwaysCreate=True
    Task Parameter:Files=d:\git\cswinrt2\src\Projections\WinUI\obj\x64\Release\net5.0\WinUI.csproj.CopyComplete
    Touching "d:\git\cswinrt2\src\Projections\WinUI\obj\x64\Release\net5.0\WinUI.csproj.CopyComplete".
    Output Item(s): FileWrites=d:\git\cswinrt2\src\Projections\WinUI\obj\x64\Release\net5.0\WinUI.csproj.CopyComplete
  Done executing task "Touch".
Done building target "_CopyFilesMarkedCopyLocal" in project "WinUI.csproj".

...

FastUpToDate: Latest write timestamp on input marker is 6/16/2021 10:12:36 AM on 'd:\git\cswinrt2\src\Projections\WinUI\obj\x64\Release\netstandard2.0\WinUI.csproj.CopyComplete'. (Test)
FastUpToDate: Write timestamp on output marker is 6/16/2021 10:11:52 AM on 'd:\git\cswinrt2\src\Projections\Test\obj\x64\Release\netstandard2.0\Test.csproj.CopyComplete'. (Test)
FastUpToDate: Input marker is newer than output marker, not up to date. (Test)

**Comment by BenVillalobos** [comment] 2021-06-21 21:52
I can't get a successful build after running `build.cmd` and `devenv cswinrt.sln` and building the test project:

![image](https://user-images.githubusercontent.com/4691428/122831914-6b7e3b80-d29f-11eb-89e3-64db85e44ea7.png)

Am I missing something?

**Comment by BenVillalobos** [comment] 2021-06-21 22:51
I don't see a repro in a minimal case (ProjA references ProjB, both console projects): 
[6576-repro.zip](https://github.com/dotnet/msbuild/files/6689861/6576-repro.zip)

Open ProjA\ProjA.sln, set all required verbosities. Run build on ProjA multiple times. No repro. Tested on 16.10

**Comment by rainersigwald** [comment] 2021-07-01 15:27
This appears to be by design for `CopiedFiles`, and not a bug:

https://github.com/dotnet/msbuild/blob/cdc5faeda066a83b084c96b8a455ad0a5e8713ab/src/Tasks.UnitTests/Copy_Tests.cs#L1013-L1016

So we may have to add a new output to `Copy` along the lines of `bool ActuallyDidAtLeastOneCopy` or `ITaskItem[] FilesNotUpToDate` and check _that_ in the Touch task

https://github.com/dotnet/msbuild/blob/cdc5faeda066a83b084c96b8a455ad0a5e8713ab/src/Tasks/Microsoft.Common.CurrentVersion.targets#L4700-L4706

I'm not sure of the impact of this problem, though, and I don't think it's a major contributor to incremental-build problems in CsWinRT, so I'd still like to investigate that specifically. FUTD should be avoiding this situation pretty much always if I'm understanding it correctly.

**Comment by BenVillalobos** [comment] 2021-07-17 00:40
After doing my own investigation,
> This appears to be by design for CopiedFiles, and not a bug:

Unfortunately this is the case and horribly misleading.

I did notice that in my simple repro I could get ProjA to consistently build after rebuilding

![image](https://user-images.githubusercontent.com/4691428/126019519-041bbea3-794d-4f5d-b8e8-1ae703a2bded.png)
It seems like FUTD in VS doesn't apply on a rebuild->build? @swesonga do you know if this is by design?

When it did run, however, we still hit the issue with `Copy` not actually copying anything but still updating copycomplete:

![image](https://user-images.githubusercontent.com/4691428/126019569-d6675ec5-7c6b-43ab-8903-fe18c8fa00bd.png)

> FUTD should be avoiding this situation pretty much always if I'm understanding it correctly.

Looks like this is a two phase problem.
1. Why is VS calling MSBuild on a project that's up to date?	
2. Why is MSBuild updating the `.CopyComplete` file when nothing is actually copied?
	1. The fix here is as Rainer suggested, create some other parameter that tells us _something_ was copied, or contains what was actually copied. The latter sounds more useful.

**Comment by drewnoakes** [comment] 2021-07-17 03:45
> It seems like FUTD in VS doesn't apply on a rebuild->build? @swesonga do you know if this is by design?

It's by design. The check isn't invoked for rebuild at all. Rebuild should, by definition, build regardless of being up to date or not.

**Comment by BenVillalobos** [comment] 2021-07-19 16:01
@drewnoakes That much makes sense for Rebuild, but what about a build _after_ a rebuild? Here's what I think should happen:

1. Rebuild
2. Build (FUTD kicks in)

What actually happens:
1. Rebuild
2. Build (build actually runs)

**Comment by drewnoakes** [comment] 2021-07-22 22:44
@BenVillalobos do you have a repro for that scenario? I cannot repro it in the following steps:

1. Create new .NET Console App
2. Build
3. Rebuild
4. Build (up to date)

**Comment by BenVillalobos** [comment] 2021-07-22 22:57
@drewnoakes Should be the project here: https://github.com/dotnet/msbuild/issues/6576#issuecomment-865394702

**Comment by BenVillalobos** [comment] 2021-07-27 18:09
Closing as of https://github.com/dotnet/msbuild/pull/6698

**Closed by BenVillalobos** 2021-07-27 18:09 UTC
Labels: Partner request, bug, under-investigation
