### ISSUE TITLE
dotnet 6 build apple m1 max slow

### ISSUE THREAD

**Issue by last-Programmer** [dotnet/msbuild#7133] opened 2021-12-08 02:36 UTC
When i try to build dotnet 6 console application in m1 max computer it takes longer than that takes on Windows/Linux Computers

Here is the summary build  time of dotnet6 console application

Windows :  39 seconds
Linux : 33 seconds
m1 max arm64: 50 seconds

Not sure what is causing build to be slower in m1 max macs

Any steps to debug the problem?

Thanks in advance

**Comment by evenlee** [comment] 2022-08-29 10:15
I notice this recently too,  build same  .netcore 3.1 solution, my 5800x hachintosh jsut need up to 12 seconds, but M1 Max Macbook Pro takes up to 48 seconds,  also tested on Windows: Thinkpad T14(5850u/32G RAM) with VS 2022, only need up to 16 seconds, may be msbuild is still native supported

**Comment by rainersigwald** [comment] 2022-08-29 14:37
This is definitely not expected. Would it be possible to share a [binary log of your build](https://aka.ms/msbuild/binlog)? ⚠️Note the warnings about the contents of the log and please make sure you're not sharing more than you're comfortable with.

**Comment by evenlee** [comment] 2022-08-30 14:44
I met errors when using  **dotnet build -bl** on Mac , the reason is I have a .net 6 winform app and a .net 4.5 lib project in the solution, the wired thing is when I click build button in  VS for Mac, no errors, do you know how to leverage command to make same behavior as build button in VS for Mac

**Comment by evenlee** [comment] 2022-09-07 13:43
[output_from_msbuild_failed_M1Max.log](https://github.com/dotnet/msbuild/files/9506640/output_from_msbuild_failed_M1Max.log)
[output_from_vs_2022_build_M1Max.log](https://github.com/dotnet/msbuild/files/9506641/output_from_vs_2022_build_M1Max.log)
[output_from_vs_2022_intel_mac.log](https://github.com/dotnet/msbuild/files/9506642/output_from_vs_2022_intel_mac.log)
dotnet build --version
MSBuild version 17.3.0+92e077650 for .NET

As I  mentioned, I have a winform project(fix error by adding `<EnableWindowsTargeting>true</EnableWindowsTargeting>`
 in project file) and a .Net 4.5 lib project, the error comes from the .NET 4.5 lib project

**Comment by evenlee** [comment] 2022-09-07 13:52
[msbuild.binlog.zip](https://github.com/dotnet/msbuild/files/9506744/msbuild.binlog.zip)
seems the binary log cannot be drop to here directly, please unzip it for details

**Comment by evenlee** [comment] 2022-09-10 04:57
I did more testing, seems the issue is the .NETFramework 4.5 lib project, if I remove it and related projects depended on it, the rebuild time is almost same in both M1Max Mac and Intel Mac, but if included it, the M1Max Mac will take to much time, may be you can build .net core project and add a .NET Framework4.5/4.8  project in VS on windows, then rebuild in M1Max Mac or for details.

**Comment by rainersigwald** [comment] 2022-11-16 17:41
Team triage: It looks like there are two issues at play here. @last-Programmer reported a general slowdown in `dotnet build` scenarios, which @AR-May is not able to reproduce. If you're still seeing unexpectedly slow builds on ARM Macs, please share logs or a repro case that builds faster than on Intel.

@evenlee, on the other hand, is seeing slower builds _within Visual Studio for Mac_ when building a .NET Framework 4.5 project that does not use the new .NET SDK. That is a different codepath in Visual Studio for Mac, and we think that issue would best be investigated by the VSMac team. Please file a bug with them at https://docs.microsoft.com/visualstudio/mac/report-a-problem, ideally with a repro case and logs showing the build time differences. You may also be able to get better behavior by converting your project to use the .NET SDK, which can target .NET Framework 4.5.

I'm going to close this bug since we haven't been able to reproduce the originally reported performance issue and the other issue needs investigation by the VSMac folks.

**Closed by rainersigwald** 2022-11-16 17:41 UTC
Labels: performance, Performance-Scenario-Build, OS: macOS, Architecture: ARM64
